import { readFile, writeFile } from "node:fs/promises";
import { z } from "zod";
import { staffImportPreviewInput, staffImportApplyInput, staffImportReceiptSchema, staffImportDetailSchema, staffImportListSchema, staffImportSummarySchema } from "../shared/staff-imports";
const doc = JSON.parse(await readFile("docs/openapi.json", "utf8"));
const ref = (name: string) => ({ $ref: "#/components/schemas/" + name });
const json = (schema: unknown) => ({ "application/json": { schema } });
for (const [name, schema] of Object.entries({ StaffImportReceipt: staffImportReceiptSchema, StaffImportDetail: staffImportDetailSchema, StaffImportList: staffImportListSchema, StaffImportSummary: staffImportSummarySchema }))
  doc.components.schemas[name] = z.toJSONSchema(schema, { io: "input" });
const access = "Actual current password session with active account, completed onboarding and current MFA proof is mandatory. PIN and bearer access are denied. Current owner/admin/manager role and exact explicit unit scope are checked after account locks. Managers can create employee accounts only; administrators cannot create administrators; no import grants owner. Creator-private evidence remains private even from another owner/admin. Every publication checks actual session expiry after serialization and any audit. All responses are private, no-store. ";
const id = { in: "path", name: "id", required: true, schema: { type: "string", format: "uuid" } };
const csrf = [{ in: "header", name: "Origin", required: true, schema: { type: "string" } }, { in: "header", name: "X-CSRF-Token", required: true, schema: { type: "string" } }];
const errors = Object.fromEntries(Object.entries({ 400: "Malformed request or CSV", 401: "Actual session expired or changed", 403: "Current role or complete captured scope denied", 404: "Private import or retained source unavailable", 409: "Definitive conflict, expired pending preview, legacy receipt unavailable, changed history cursor or configured source budget reached", 413: "Source/body size limit", 422: "Retained evidence integrity error", 429: "Request limit", 500: "Unexpected failure. Preserve the exact apply retry identity.", 503: "Temporary contention. Retain the same batch ID/sourceHash when retrying an apply." }).map(([status, description]) => [status, { description, content: json(ref("Error")) }]));
function operation(method: "get" | "post", path: string, summary: string, description: string, result: string | null, input?: z.ZodType, parameters: unknown[] = []) {
  const value: any = { operationId: method + "_" + path.replace(/[{}]/g, "").replaceAll("/", "_").slice(1), summary, description: access + description, security: [{ Session: [] }],
    parameters: [...parameters, ...(method === "post" ? csrf : [])], responses: { "200": { description: "Current-authorized result", content: result ? json(ref(result)) : { "text/csv": { schema: { type: "string" } } } }, ...errors } };
  if (input) value.requestBody = { required: true, content: json(z.toJSONSchema(input, { io: "input" })) };
  doc.paths[path] = { ...(doc.paths[path] ?? {}), [method]: value }; return value;
}
operation("get", "/imports/staff/template", "Download the blank staff CSV template", "Exact ordered columns name,email,role,unitIds,jobIds. Pipe-separated UUIDs remain explicit. No default roles, account values or credentials.", null);
operation("post", "/imports/staff/preview", "Retain and review a create-only employee import", "The strict CSV body keeps the existing400000 JavaScript-character limit plus1600000 UTF-8 bytes; invalid Unicode roundtrips reject. The existing512KiB HTTP JSON limit still applies. Exact ordered headers,1–500 rows and4096 parser record bound. Parsed names/emails normalize through the existing staff schema. Current jobs and units are locked and validated; existing emails cannot be overwritten. No account is created by preview. Exact original UTF-8/BOM/CRLF bytes and normalized rows are retained permanently. A preview-only organization advisory lock serializes the serialized-source budget check and insertion before account locks. The configured budget defaults to64MiB of sum(octet_length(source_base64)) across all retained organization sources, is validated1MiB–1GiB, and has no unlimited bypass. Exceeding it returns409 and preserves history. This budget is not a disk-space estimate.", "StaffImportDetail", staffImportPreviewInput);
operation("post", "/imports/staff/{id}/apply", "Create reviewed accounts once or recover the same retained receipt", "Account/session locks precede the private batch lock. Exact sourceHash and current complete captured role/unit authority are required. Pending previews must still be within24 hours after lock waits; current job/unit/email validation, all account/membership writes, the immutable receipt and audits commit atomically. No passwords, PINs, setup links or sessions are created. The same batch ID/sourceHash returns the identical stored receipt200 after current proof, before mutable preview age/email/job checks, without another import.applied audit. Existing created/notice fields remain. Preserve this exact identity after transport loss,408,429 or5xx. Legacy applied rows without a stored receipt remain honest409; no account IDs are reconstructed. Legacy pending previews may create genuine new receipts but cannot recover absent original CSV.", "StaffImportReceipt", staffImportApplyInput, [id]);
operation("get", "/imports/staff", "List creator-private retained staff imports", "Newest first, up to50 per page. Historical visibility requires current authority for every captured role and explicit unit, independent of current job activity or later changes to created accounts. The opaque cursor binds creator/org/current role+units/page size and the visible cohort's insert/apply revision from the same repeatable-read snapshot.409 requires discarding partial pages and reloading the entire list. No status filter.", "StaffImportList", undefined,
  [{ in: "query", name: "limit", schema: { type: "integer", minimum: 1, maximum: 50, default: 50 } }, { in: "query", name: "cursor", schema: { type: "string", minLength: 1, maxLength: 640, pattern: "^[A-Za-z0-9_-]+$" } }]);
operation("get", "/imports/staff/{id}", "Read retained staff import rows and original creation receipt", "Receipt identities are captured actual create results in original CSV row order. They describe original creation, not current employee state. sourceAvailable=false labels legacy imports whose source was never retained. receiptState distinguishes pending, retained and legacy_unavailable.", "StaffImportDetail", undefined, [id]);
const source = operation("get", "/imports/staff/{id}/source", "Download exact retained staff CSV text", "Literal original UTF-8 bytes, including BOM and line endings, under generated stjw-staff-import-<UUID>-source.txt. No reserialization or spreadsheet formula transformation.404 if original source was never retained; sourceHash alone is not used to reconstruct it.", null, undefined, [id]);
source.responses["200"] = { description: "Exact original source bytes", content: { "text/plain": { schema: { type: "string" } } }, headers: { "X-STJW-Source-SHA256": { schema: { type: "string", pattern: "^[a-f0-9]{64}$" } } } };
const suggest = doc.paths["/imports/suggest"].post;
suggest.description = "Actual current owner/admin/manager password session with active account, completed onboarding and current MFA proof is mandatory. PIN and bearer access are denied; responses are private, no-store. Existing optional advisory header classification only: reviewed column labels, fixed existing question/model/SDK behavior. This advisory endpoint has no selected-unit context and does not validate proposed employee rows. Current management proof precedes cache lookup/provider work and is refreshed before cached/provider results or provider errors publish. Network work holds no database transaction. A successful fresh audit and final session check are atomic. Cached results are also currently authorized. Advice cannot import data, grant access or create accounts.";
await writeFile("docs/openapi.json", JSON.stringify(doc, null, 2) + "\n");
console.log("Staff import evidence API documented: 6 paths plus existing advice proof.");
