import { staffUpdateInput } from '../shared/staff-editing';
import {staffScheduleCreateInput,staffScheduleUpdateInput,staffScheduleCancelInput} from '../shared/staff-scheduling';
import { unitChangeInput, unitSaveInput } from "../shared/organization";
import { readFile } from "node:fs/promises";
import { financePreviewInput, financePublishInput, financeComparisonInput } from "../shared/finance";
import { gradeImportPreviewInput, gradeImportApplyInput } from "../shared/grade-imports";
import { writeFile } from 'node:fs/promises';
import { z } from 'zod';
import { clockInput, staffInput, requestInput, loginInput, passwordSchema } from '../shared/contracts';
import { payrollHoursReportSchema } from '../shared/payroll-hours';
import { payrollReviewSchema } from '../shared/payroll-review';
import { createPayrollViewSchema, updatePayrollViewSchema, deletePayrollViewSchema, savedPayrollViewSchema, payrollViewListSchema, resolvedPayrollViewSchema } from '../shared/payroll-views';
import { workforceReportV2Schema, workforceReportQueryV2Schema } from '../shared/workforce-reports-v2';
import { staffCreateInput, staffCreateResultSchema, credentialChangeChallengeSchema, completeCredentialsInput, completeCredentialsResultSchema } from '../shared/temporary-credentials';
import { preferencesPatchSchema } from '../shared/preferences';
import {eventCreateInput,eventUpdateInput,messageInput,messageUpdateInput} from '../shared/community';
import * as school from '../shared/school';
import * as attendance from '../shared/attendance';
import * as admissions from '../shared/admissions';
import * as grading from '../shared/grading';
import * as care from '../shared/care';
import * as dismissal from '../shared/dismissal';
import {correctionInput,correctionReviewInput} from '../shared/time-records';
const schemas:Record<string,unknown>={};
for(const [name,schema] of Object.entries({ClockCommand:clockInput,Staff:staffInput,Request:requestInput,Schedule:staffScheduleCreateInput,Login:loginInput})) schemas[name]=z.toJSONSchema(schema,{io:'input'});
schemas.StaffCreate=z.toJSONSchema(staffCreateInput,{io:'input'});
schemas.StaffCreateResult=z.toJSONSchema(staffCreateResultSchema);
schemas.StaffUpdate=z.toJSONSchema(staffUpdateInput,{io:'input'});
schemas.CredentialChangeChallenge=z.toJSONSchema(credentialChangeChallengeSchema);
schemas.CompleteInitialCredentials=z.toJSONSchema(completeCredentialsInput,{io:'input'});
schemas.InitialCredentialsCompleted=z.toJSONSchema(completeCredentialsResultSchema);
schemas.Error={type:'object',required:['error'],properties:{error:{type:'string'},incident:{type:'string',format:'uuid'}}};
const json=(schema:unknown)=>({'application/json':{schema}});
const ref=(name:string)=>({$ref:`#/components/schemas/${name}`});
const object=(properties:Record<string,unknown>,required=Object.keys(properties))=>({type:'object',properties,required,additionalProperties:false});
const str={type:'string'},uuid={type:'string',format:'uuid'};
const instant={type:'string',format:'date-time'},milliseconds={type:'integer',minimum:0};
const array=(items:unknown)=>({type:'array',items});
schemas.StaffRecord=object({id:uuid,name:str,email:{type:'string',format:'email'},role:{type:'string',enum:['developer','owner','admin','manager','finance','employee']},active:{type:'boolean'},created_at:instant,unit_ids:array(uuid),job_ids:array(uuid),setup_complete:{type:'boolean'},requires_credential_change:{type:'boolean'},require_password_change:{type:'boolean'},require_pin_change:{type:'boolean'},revision:{type:'string',pattern:'^[a-f0-9]{64}$'}});
schemas.StaffDirectory=object({rows:array(ref('StaffRecord'))});
schemas.WorkforceBucket=object({key:instant,label:str,workMs:milliseconds,breakMs:milliseconds});
schemas.WorkforceStaffTotal=object({id:uuid,name:str,workMs:milliseconds,breakMs:milliseconds});
schemas.WorkforceSegment=object({id:uuid,kind:{type:'string',enum:['work','break']},started_at:instant,ended_at:{anyOf:[instant,{type:'null'}]},revision:{type:'integer',minimum:1},shift_id:uuid,user_id:uuid,employee_name:str,job_id:uuid,job_title:str,unit_id:uuid,unit_name:str,duration_ms:milliseconds,duration_seconds:{type:'number',minimum:0}});
schemas.WorkforceReportQuery=object({start:{type:'string',format:'date'},end:{type:'string',format:'date'},group:{type:'string',enum:['hour','day','week','month','year']},unitId:uuid,userId:uuid,columns:{type:'string',maxLength:500,description:'Optional CSV column selector also echoed when supplied to the JSON endpoint; does not filter JSON fields.'}},['start','end','group']);
schemas.WorkforceReport=object({workMs:milliseconds,breakMs:milliseconds,buckets:array(ref('WorkforceBucket')),staff:array(ref('WorkforceStaffTotal')),rows:{type:'array',maxItems:20000,items:ref('WorkforceSegment')},timezone:{type:'string',description:'Organization IANA timezone used for local date bounds and calendar buckets.'},asOf:instant,query:ref('WorkforceReportQuery'),notice:str});
schemas.WorkforceReportV2=z.toJSONSchema(workforceReportV2Schema,{io:'output'});
schemas.WorkforceReportQueryV2=z.toJSONSchema(workforceReportQueryV2Schema,{io:'input'});
const paths:Record<string,any>={};
function add(path:string,method:string,summary:string,access:string,input?:unknown,options:{public?:boolean;status?:number;csv?:boolean;query?:any[];token?:boolean}={}) {
 const operation:any={operationId:method+path.replace(/[^a-zA-Z]/g,'_'),summary,description:access,security:options.public?[]:[{Session:[]},...(options.token?[{AgentBearer:[]}]:[])],responses:{[String(options.status??200)]:{description:'Successful operation',content:options.csv?{'text/csv':{schema:str}}:json({type:'object'})},'400':{description:'Invalid input',content:json(ref('Error'))},'401':{description:'Sign-in required or expired',content:json(ref('Error'))},'403':{description:'Origin, CSRF, scope, or role denied',content:json(ref('Error'))},'409':{description:'Conflicting state or duplicate record',content:json(ref('Error'))},'429':{description:'Attempt limit reached',content:json(ref('Error'))}}};
 const params:any[]=[...(options.query??[])];
 for(const match of path.matchAll(/\{([^}]+)\}/g))params.push({name:match[1],in:'path',required:true,schema:uuid});
 if(!['get','head'].includes(method)){params.push({name:'Origin',in:'header',required:true,schema:str,description:'Exact configured APP_ORIGIN'});if(!options.public)params.push({name:'X-CSRF-Token',in:'header',required:true,schema:str,description:'Session token from GET /me; API bearer tokens cannot write.'});operation.requestBody={required:true,content:json(input??object({}))};}
 if(params.length)operation.parameters=params;
 (paths[path]??={})[method]=operation;
}
const q=(name:string,schema:unknown,required=false)=>({name,in:'query',required,schema});
const reports=[q('start',{type:'string',format:'date'},true),q('end',{type:'string',format:'date'},true),q('group',{type:'string',enum:['hour','day','week','month','year'],default:'day'}),q('unitId',uuid),q('userId',uuid)];
add('/payroll/hours','get','Read employee and job hours for payroll preparation','Current reporting role and actual browser proof or reports:read token. Exact microsecond aggregates and six-decimal hours after aggregation. Includes work, breaks, unique shifts, segment and ongoing-segment counts, source report and capture time. Explicit assigned units plus manager own records. This is not payroll approval or a gross/net pay calculation.',undefined,{query:reports,token:true});
add('/payroll/hours/export','get','Download current payroll hours as Excel, CSV or JSON','Rechecks current reporting authority before publication; exports are audited and private/no-store. Excel contains employee/job/totals/source/provenance sheets. CSV row_kind separates employee/job/total rows: do not sum different row kinds together. Downloads read fresh sources and may differ from a prior screen. XLSX is generated in a fixed bounded worker. No pay policies are inferred.',undefined,{token:true,query:[...reports,q('format',{type:'string',enum:['csv','xlsx','json'],default:'csv'})]});
paths['/payroll/hours'].get.responses['200'].content=json(z.toJSONSchema(payrollHoursReportSchema));
paths['/payroll/hours/export'].get.responses['200'].content={'text/csv':{schema:str},'application/json':{schema:z.toJSONSchema(payrollHoursReportSchema)},'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':{schema:{type:'string',format:'binary'}}};
add('/payroll/review','get','Compare recorded hours with the preceding calendar period','Current reporting role and password session or reports:read bearer proof. Both periods share one database capture instant and repeatable-read transaction. Exact signed microsecond deltas, employee union, zero-baseline percentage handling and explicit incomplete/future labels. Equal calendar-day count does not imply equal elapsed hours across DST. No wages, payroll approval or closeout.',undefined,{query:reports,token:true});
paths['/payroll/review'].get.responses['200'].content=json(z.toJSONSchema(payrollReviewSchema));
add('/payroll/review/export','get','Download a current recorded-hours comparison','Current proof is rechecked before publication. CSV/JSON exports are audited and recapture sources; a download can differ from an earlier screen. Exact arithmetic and period provenance remain explicit.',undefined,{query:[...reports,q('format',{type:'string',enum:['csv','json'],default:'csv'})],token:true});
paths['/payroll/review/export'].get.responses['200'].content={'text/csv':{schema:str},'application/json':{schema:z.toJSONSchema(payrollReviewSchema)}};
add('/payroll/views','get','List personal payroll filter views','Current reporting role and password or reports:read bearer proof. Only the current account and organization; at most25 active definitions. Availability is checked against current scope and selected active employees. Saved definitions are not retained report data.',undefined,{token:true});
paths['/payroll/views'].get.responses['200'].content=json(z.toJSONSchema(payrollViewListSchema,{io:'input'}));
add('/payroll/views','post','Create a personal payroll view','Current password session only. Name, filters and client-generated UUID; identical create retries are safe. At most25 active views. Current account-first authority, session expiry and audit commit in one transaction.',z.toJSONSchema(createPayrollViewSchema,{io:'input'}),{status:201});
paths['/payroll/views'].post.responses['201'].content=json(z.toJSONSchema(savedPayrollViewSchema,{io:'input'}));
add('/payroll/views/{id}','patch','Update a personal payroll view','Current password session, ownership and expected revision required. Stale revision conflicts; unavailable selected scope rejects without broadening.',z.toJSONSchema(updatePayrollViewSchema,{io:'input'}));
paths['/payroll/views/{id}'].patch.responses['200'].content=json(z.toJSONSchema(savedPayrollViewSchema,{io:'input'}));
add('/payroll/views/{id}','delete','Remove a personal payroll view while retaining evidence','Current password session, ownership and expected revision required. Soft deletion advances the revision and retains audit evidence.',z.toJSONSchema(deletePayrollViewSchema,{io:'input'}));
paths['/payroll/views/{id}'].delete.responses['200'].content=json(object({id:uuid,revision:{type:'integer',minimum:2},deleted:{type:'boolean',const:true}}));
add('/payroll/views/{id}/resolve','get','Resolve a personal payroll view against current dates and scope','Current password session or reports:read bearer proof. Relative dates use the database clock and organization timezone at opening. Missing, deactivated or inaccessible explicit selections remain unavailable; never substitute all employees or units. Fixed dates and maximum report bounds still apply.',undefined,{token:true});
paths['/payroll/views/{id}/resolve'].get.responses['200'].content=json(z.toJSONSchema(resolvedPayrollViewSchema,{io:'input'}));
add('/health','get','Database readiness','Public; exposes only status and application version.',undefined,{public:true});
add('/config','get','Public workspace label','Public; demo flag and name only.',undefined,{public:true});
add('/auth/login','post','Sign in with email and password, or only a PIN','No public signup. PIN mode does not require email. An ambiguous shared PIN cannot select an account; use password sign-in to replace temporary credentials. Temporary credentials return a private ten-minute credential-change challenge without an app session. The challenge includes independent requirePasswordChange/requirePinChange flags; only the selected replacements are required before workspace access. PIN sessions last 5 minutes and only access /me, /clock, and logout, including for developers and owners. Password sign-in opens permitted management features and can require the optional authenticator challenge.',ref('Login'),{public:true});
paths['/auth/login'].post.responses['200'].content=json({oneOf:[object({ok:{const:true,type:'boolean'}}),object({challenge:{type:'string',minLength:32,maxLength:100},expiresAt:instant}),ref('CredentialChangeChallenge')]});
add('/auth/setup','post','Consume private account setup link','Single-use link expires after 24 hours. Invalidates other sessions and API tokens. Denied while either selected credential replacement is pending; setup links cannot bypass onboarding.',object({token:{type:'string',minLength:32,maxLength:100},password:z.toJSONSchema(passwordSchema)}),{public:true});
add('/auth/credentials/complete','post','Complete required credential replacements','Requires the private challenge returned by either temporary login mode. Provide exactly the replacement fields required by the challenge: password (8–128 characters), PIN (6–8 digits), or both. Each replacement must differ from its assigned value. Unrequested fields are rejected and the corresponding stored credential is preserved. Account-before-challenge locking rechecks current proof and expiry, revokes previous credential proofs/sessions/tokens, and commits the selected replacements with the audit. No app session is issued: sign in again with the current password. If the response is lost, try the new credentials; an already-used challenge cannot run again. Exact Origin, JSON and attempt limits apply; no ordinary-session CSRF header is required.',ref('CompleteInitialCredentials'),{public:true});
paths['/auth/credentials/complete'].post.responses['200'].content=json(ref('InitialCredentialsCompleted'));
add('/auth/logout','post','End current browser session','Authenticated browser.');
add('/auth/pin','post','Set or replace personal PIN','Password session and current password required.',object({password:{type:'string',maxLength:128},pin:{type:'string',pattern:'^\\d{6,8}$'}}));
add('/me','get','Read verified identity and workspace permissions','Browser session; returns actor, organization, units, permissions, and module status.');
add('/me/preferences','patch','Save personal appearance, navigation and dashboard preferences','Current actual password session required. Partial updates merge with current account preferences and repeat session proof before commit. Theme light/dark/system; nine palettes and custom accent; contrast, text size, spacing, navigation density, corners, reduced motion, artwork, depth, home, dashboard card order/visibility, and complete workspaceNavOrder/organizationNavOrder permutations. Omitted orders remain unchanged. Unknown, duplicate, missing or wrong-group navigation IDs are rejected on writes. Stored legacy navigation gains current defaults without changing valid existing appearance choices. Preferences grant no access rights.',z.toJSONSchema(preferencesPatchSchema,{io:'input'}));
add('/clock','get','Read own open shift and assigned jobs','Current password or restricted PIN session; no employee identity override. Account, role, memberships and the actual session proof are refreshed under account-first locks. Password MFA is checked when enabled; PIN keeps its existing clock-only scope. Proof is checked again before publication.');
add('/clock','post','Apply own clock transition','Current password or restricted PIN session with account-first locking and final proof validation. Server supplies time and identity after the account lock. Transition, receipt and audit commit together; expiry or audit failure rolls them back. Reuse commandId only for retries of the identical command, including uncertain responses or 503. Exact receipt replay still requires current authority.',ref('ClockCommand'));
add('/board','get','Read currently clocked-in staff','Owner/admin/finance: organization; manager: assigned units.');
add('/staff','get','Read permitted staff directory','Reporting roles; organization/unit restrictions. Agent scope staff:read.',undefined,{token:true});
paths['/staff'].get.responses['200'].content=json(ref('StaffDirectory'));
add('/staff','post','Create staff account with private setup or temporary credentials','Current verified password session, management role and explicit unit/role restrictions. Only developers and owners can create administrators; administrators can create lower roles. Staff domain must match configured domain. Omit initialCredentials for the default private setup link. Developer/owner/admin may supply password and PIN with independent requirePasswordChange and requirePinChange booleans, both defaulting to true. All four policies are supported. Values are hashed, only the selected replacements are required, and a retained PIN must be unique. The response contains policy metadata but neither credential nor a setup link. Account, assignments and audits are atomic; current authority and final session are rechecked.',ref('StaffCreate'),{status:201});
paths['/staff'].post.responses['201'].content=json(ref('StaffCreateResult'));
add('/staff/{id}','patch','Update employee account and assignments','Management scope required; self account edits forbidden; employee must be clocked out. Supply expectedRevision from the latest staff-directory row to prevent overwriting newer profile or job changes. A stale form returns409 and must reload. Only a developer may manage an existing owner or another developer. Ordinary forms cannot provision new owner/developer roles. Successful changes revoke target sessions and API tokens. Use the separate assignment-only route for eligible self/peer jobs and safe additions during an open shift.',ref('StaffUpdate'));
add('/staff/{id}/setup-link','post','Issue replacement private setup link','Management scope; invalidates previous unused links. Share privately.');
add('/jobs','get','Read accessible job definitions','Password session; assigned-unit scope for non-organization-wide roles.');
add('/jobs','post','Create job definition','Management role with unit access.',object({unitId:uuid,title:{type:'string',minLength:2,maxLength:100}}),{status:201});
add('/requests','get','Read own requests and review queue','Employees/finance: own; owner/admin/manager: permitted review scope. Latest 300 records.');
add('/requests','post','Submit time off, schedule, or correction request','Current active password account and one of own exact assigned units; account and membership locks recheck access within the write transaction.',ref('Request'),{status:201});
add('/requests/{id}/review','post','Record approval or decline','Current active password account with management role, scoped unit access and a different requester. Account and membership locks precede the pending request lock; changed role or assignment is rechecked before recording a decision. Does not change punches, schedule, or PTO balance.',object({status:{enum:['approved','declined']},note:{type:'string',minLength:3,maxLength:1000}}));
add('/schedules','get','Read current or cancelled scheduled shifts','Current active password account; employees see own records, managers exact assigned units plus their own, owner/admin/finance organization-wide. Current memberships reloaded under account lock. At most 32 elapsed days and 2,000 rows; larger results rejected.',undefined,{query:[q('start',{type:'string',format:'date-time'},true),q('end',{type:'string',format:'date-time'},true),q('includeCancelled',{type:'boolean',default:false})]});
add('/schedules','post','Create versioned scheduled staff shift','Current owner/admin/manager password role; exact unit access, active employee and current assigned active job. Required command UUID/reason, no overlap, at most 24 elapsed hours. Clock records are unchanged. Atomic immutable history, receipt and audit.',ref('Schedule'),{status:201});
add('/schedules/{id}','patch','Review a schedule change','Current owner/admin/manager; current source and target unit access. Fixed employee identity, expected version, command UUID and reason. Revalidates current job assignment and overlaps after employee lock. Cancelled shifts cannot be edited.',z.toJSONSchema(staffScheduleUpdateInput,{io:'input'}));
add('/schedules/{id}/cancel','post','Cancel a scheduled shift while retaining evidence','Current scoped owner/admin/manager, expected version, command UUID and reason. Existing inactive/unassigned staff shifts may still be cancelled. No clock, request or payroll mutation.',z.toJSONSchema(staffScheduleCancelInput,{io:'input'}));
add('/schedules/{id}/history','get','Read retained staff schedule revisions','Current password identity and schedule scope; employee sees own history. Managers need explicit access to every historical unit unless reading their own record. Twenty revisions per page; earlier records retained. Version-one migration baselines identify unavailable earlier edits.',undefined,{query:[q('beforeVersion',{type:'integer',minimum:1,maximum:2147483647})]});
add('/reports','get','Summarize recorded work and break duration','Own history for employees; reporting roles scoped by explicit unit. Current active account, role, memberships and actual session or scoped bearer proof are refreshed under locks, with final credential-expiry check before publication. Password sessions honor current MFA; bearer tokens need reports:read. Temporary-onboarding accounts and PIN sessions are denied. Inclusive local dates; at most 367 days (hourly 32), 20,000 segments. Existing arithmetic is at millisecond resolution.',undefined,{query:reports,token:true});
paths['/reports'].get.responses['200'].content=json(ref('WorkforceReport'));
add('/reports/export','get','Export selected report segment columns','Same current account/unit/session/bearer proof as JSON reports, including final expiry checks. Formula-safe CSV. duration_seconds is clipped to range/asOf at existing millisecond resolution. Export audit and final proof share the source transaction; failure publishes no CSV and rolls back the audit.',undefined,{query:[...reports,q('columns',str)],token:true,csv:true});
for(const path of ['/reports','/reports/export'])paths[path].get.responses['503']={description:'Temporary report transaction conflict; retry the read.',content:json(ref('Error'))};
add('/reports/v2','get','Read exact recorded workforce durations','Explicit version2; v1 endpoints remain unchanged. Current password or reports:read bearer proof is refreshed under account-first locks and checked again at publication. PIN access is denied. One repeatable-read source transaction, exact six-digit UTC timestamps and integer microsecond strings; no per-segment rounding. Inclusive local dates:367 maximum,32 hourly. At most20,000 segments and1,024 buckets; strict query rejects unknown/repeated parameters. Open source ends remain null. Zero-duration points at the range start are included; points at the exclusive end are excluded. Recorded durations do not configure payroll.',undefined,{query:reports,token:true});
paths['/reports/v2'].get.responses['200'].content=json(ref('WorkforceReportV2'));
add('/reports/v2/export','get','Download exact workforce CSV or JSON evidence','Same actual current proof and repeatable-read source as version2 JSON. Default CSV uses unique allowlisted columns, UTF-8 BOM, CRLF and spreadsheet protection; timestamps retain UTC6 and durations use integer microsecond strings. format=json downloads the complete fresh report with query, timezone, range, asOf, exact rows and totals; columns is forbidden for JSON. Export audit and final expiry proof share one transaction; failure publishes no file. Response headers identify precision and the exact sampled asOf. Existing v1 CSV bytes remain unchanged.',undefined,{query:[...reports,q('columns',{type:'string',minLength:1,maxLength:500}),q('format',{type:'string',enum:['csv','json'],default:'csv'})],token:true,csv:true});
paths['/reports/v2/export'].get.responses['200'].content['application/json']={schema:ref('WorkforceReportV2')};
paths['/reports/v2/export'].get.responses['200'].headers={
 'X-STJW-Report-Version':{schema:{type:'string',const:'2'}},'X-STJW-Duration-Unit':{schema:{type:'string',const:'microsecond'}},'X-STJW-Report-As-Of':{schema:{type:'string',format:'date-time',description:'Exact UTC instant with six fractional digits.'}}
};
for(const path of ['/reports/v2','/reports/v2/export'])paths[path].get.responses['503']={description:'Temporary report transaction conflict; retry this read.',content:json(ref('Error'))};
add('/audit','get','Read recent organization audit events','Owner/admin/finance password session.',undefined,{query:[q('limit',{type:'integer',minimum:1,maximum:500,default:100})]});
add('/imports/staff/template','get','Download blank staff CSV template','Management role. Headers: name,email,role,unitIds,jobIds.',undefined,{csv:true});
add('/imports/staff/preview','post','Validate staff CSV without creating accounts','Management role; 500 rows, 400,000 characters; assigned-unit and role checks.',object({csv:{type:'string',maxLength:400000}}));
add('/imports/staff/{id}/apply','post','Confirm a previously validated staff import','Same actor and exact sourceHash, valid for 24 hours, single use. Transaction revalidates all rows.',object({sourceHash:{type:'string',minLength:64,maxLength:64}}));
add('/imports/suggest','post','Ask Jev for advisory dataset classification','Management role; reviewed column headers only. Does not import or authorize data.',object({headers:{type:'array',minItems:1,maxItems:40,items:{type:'string',minLength:1,maxLength:80,pattern:'^[a-zA-Z0-9 _./()%:-]+$'}}}));
add('/tokens','get','List scoped agent credential metadata','Owner password session; raw values are never returned again.');
add('/tokens','post','Create expiring read-only agent credential','Owner password session. Returned token is shown once.',object({name:{type:'string',minLength:2,maxLength:80},scopes:{type:'array',minItems:1,maxItems:2,items:{enum:['reports:read','staff:read']}},days:{type:'integer',minimum:1,maximum:90}}));
add('/tokens/{id}/revoke','post','Revoke agent credential','Owner password session.');
const community='Password sessions only; tenant/record access applies. PIN and agent credentials cannot access these routes.';
add('/calendar/events','get','List visible calendar events',community+' Personal events belong to their creator; shared events follow organization/unit scope. Cancelled events are excluded. Maximum 2,000 events.',undefined,{query:[q('from',{type:'string',format:'date-time'},true),q('to',{type:'string',format:'date-time'},true)]});
add('/calendar/export','get','Download visible standalone events as iCalendar',community+' Explicit download, no subscription or external send. Current active account, password session and exact unit memberships are rechecked under locks. Personal events only for creator; organization events for active staff; owner/admin can view unit events. Cancelled events and academic timetable are excluded. Maximum 367 elapsed days and 2,000 events, with overflow rejected. UTC occurrences retain stable UID/revision; escaped UTF-8 content. Export audit records range/count/hash, not event text.',undefined,{query:[q('from',{type:'string',format:'date-time'},true),q('to',{type:'string',format:'date-time'},true),q('audience',{enum:['all','personal','unit','organization'],default:'all'})]});
paths['/calendar/export'].get.responses['200']={description:'Authorized standalone event file.',content:{'text/calendar':{schema:{type:'string'}}}};
add('/calendar/events','post','Create an event or recurring series',community+' Only managers publish unit events; owner/admin publish organization events. Daily/weekly series has at most 52 occurrences within 366 days. Local start time is preserved across DST.',z.toJSONSchema(eventCreateInput,{io:'input'}),{status:201});
add('/calendar/events/{id}','patch','Edit one calendar occurrence',community+' Current version required. Audience cannot change because historical content keeps the original boundary.',z.toJSONSchema(eventUpdateInput,{io:'input'}));
add('/calendar/events/{id}/cancel','post','Cancel one occurrence',community+' Version checked; cancellation and history retained.',object({version:{type:'integer',minimum:1}}));
add('/calendar/events/{id}/history','get','Read event revision history',community+' Same record visibility as the event.');
add('/messages/directory','get','List permitted internal recipients',community+' Active colleagues in shared units, plus administrators. Owner/admin can address all active colleagues. Names and IDs only.');
add('/messages','get','Read own message folder',community+' Drafts and sent belong to sender; inbox/archive belong to recipient.',undefined,{query:[q('folder',{enum:['inbox','sent','drafts','archive'],default:'inbox'}),q('offset',{type:'integer',minimum:0,maximum:10000,default:0})]});
add('/messages','post','Save an internal message draft',community+' Recipients revalidated; no delivery until explicit send.',z.toJSONSchema(messageInput,{io:'input'}),{status:201});
add('/messages/{id}','get','Read a private message',community+' Only sender reads drafts. Only sender and recipients read sent messages. Read receipts returned to sender.');
add('/messages/{id}','patch','Update own unsent draft',community+' Current version required. Sent content is immutable.',z.toJSONSchema(messageUpdateInput,{io:'input'}));
add('/messages/{id}/send','post','Deliver the reviewed draft inside STJW',community+' Version required; current recipient access rechecked. Repeated sends of the same version return the original delivery. No external email is sent.',object({version:{type:'integer',minimum:1}}));
add('/messages/{id}/state','patch','Set own message read/archive state',community+' Recipient of a delivered message only. At least one field required.',{...object({read:{type:'boolean'},archived:{type:'boolean'}},[]),minProperties:1});

const schoolAccess='Password sessions only. PIN and agent tokens are denied. Tenant and unit checks apply. School office grants are separate from workforce roles.';
const office=schoolAccess+' Owner/admin or explicit school office grant with current unit membership required.';
const teaching=schoolAccess+' Assigned teacher with current unit membership, or school office access required.';
const zj=(schema:z.ZodType)=>z.toJSONSchema(schema,{io:'input'});
const unitQuery=[q('unitId',uuid,true)],yearQuery=[...unitQuery,q('yearId',uuid,true)];
add('/school/access','get','Read school units and office/teacher access',schoolAccess);
add('/school/staff','get','List staff eligible for classroom assignment',office,undefined,{query:unitQuery});
add('/school/office-grants','get','List school office grants',schoolAccess+' Owner/admin only.');
add('/school/office-grants','post','Grant or revoke school office access',schoolAccess+' Owner/admin only; granting requires active unit membership.',object({unitId:uuid,userId:uuid,enabled:{type:'boolean'}}));
add('/school/years','get','List school years',teaching,undefined,{query:unitQuery});
add('/school/years','post','Create a school year',office,zj(school.schoolYearInput),{status:201});
add('/school/terms','get','List terms in a school year',office,undefined,{query:yearQuery});
add('/school/terms','post','Create a term within its school year',office,zj(school.termInput),{status:201});
add('/school/students','get','Search the office student directory',office+' 100 rows per page.',undefined,{query:[...unitQuery,q('search',str),q('offset',{type:'integer',minimum:0})]});
add('/school/students','post','Create a student record',office,zj(school.studentInput),{status:201});
add('/school/students/{id}','get','Read a scoped student record',teaching+' Teacher view excludes birth date, private restrictions, household and pickup permissions. Teacher relationships must be current.');
add('/school/students/{id}','patch','Update student profile',office+' Version required.',zj(school.studentUpdateInput));
add('/school/students/{id}/enrollments','post','Create or update year enrollment',office+' Dates must fit the school year; updates require current version.',zj(z.object({enrollment:school.enrollmentInput,version:z.number().int().positive().optional()}).strict()));
add('/school/students/{id}/contacts','post','Set student contact permissions',office+' Guardian, communication and pickup permissions are independent. Existing links require current version.',zj(school.contactInput));
add('/school/households','get','List active households',office+' Up to 1,000 rows.',undefined,{query:unitQuery});
add('/school/households','post','Create a household',office,zj(school.householdInput),{status:201});
add('/school/households/{id}','get','Read household members',office);
add('/school/households/{id}','patch','Update or archive household',office,zj(school.householdUpdateInput));
add('/school/households/{id}/members','post','Link or unlink a household member',office+' Membership does not grant contact/pickup permission.',zj(z.object({personId:z.uuid(),role:z.enum(['student','guardian','other']),remove:z.boolean().default(false)}).strict()));
const personOffice=office+' Actual current password-session proof, active account/onboarding/MFA state and exact office authority are rechecked in the transaction and before publishing. Person writes, private history and metadata audit commit atomically; retryable database contention returns503. No inferred family or pickup permission.';
add('/school/people','get','List contact people',personOffice+' Returns up to 1,000 rows; larger directories return422 instead of a partial list.',undefined,{query:unitQuery});
add('/school/people','post','Create a contact person',personOffice+' A manual create has no idempotency receipt; after an uncertain response inspect the directory before creating again.',zj(school.personInput),{status:201});
add('/school/people/{id}','patch','Update a contact person',personOffice+' Exact version required. Student-linked identities use the student workflow; existing applicant editing remains allowed. Omitted email/phone clear those fields, and even an unchanged manual edit advances its version.',zj(school.personUpdateInput));
add('/school/courses','get','List courses',office,undefined,{query:unitQuery});
add('/school/courses','post','Create a course',office,zj(school.courseInput),{status:201});
add('/school/sections','get','List accessible classes',teaching,undefined,{query:[...unitQuery,q('yearId',uuid)]});
add('/school/sections','post','Create class and teacher assignments',office,zj(school.sectionInput),{status:201});
add('/school/sections/{id}','get','Read roster and curriculum',teaching);
add('/school/sections/{id}','patch','Update class and teaching assignments',office,zj(school.sectionUpdateInput));
add('/school/sections/{id}/roster','post','Enroll student in a dated class roster',office+' Capacity and overlapping homeroom assignments are checked transactionally.',zj(school.rosterInput));
add('/school/sections/{id}/curriculum','post','Add a curriculum unit',teaching,zj(school.curriculumInput),{status:201});
add('/school/curriculum/{id}','patch','Update or archive curriculum unit',teaching,zj(school.curriculumInput.extend({version:z.number().int().positive(),archived:z.boolean()}).strict()));
add('/school/history/{id}','get','Read private school change history',office+' General finance/audit access does not expose this history.');
add('/school/attendance/config','get','Read attendance configuration',teaching,undefined,{query:unitQuery});
add('/school/attendance/config','put','Update attendance configuration',office+' Confirmed rules required outside synthetic demo mode.',zj(attendance.attendanceSettingsInput));
add('/school/attendance/codes','post','Create attendance code',office,zj(attendance.attendanceCodeInput),{status:201});
add('/school/attendance/codes/{id}','patch','Update a versioned attendance code',office+' Existing marks preserve original code snapshots.',zj(attendance.attendanceCodeInput.extend({version:z.number().int().positive()}).strict()));
add('/school/attendance/days','get','List instructional calendar exceptions',teaching,undefined,{query:yearQuery});
add('/school/attendance/days','put','Set a school-day exception',office,zj(attendance.attendanceDayInput));
add('/school/attendance/sessions','post','Open or retrieve a dated class roll call',teaching+' No future dates or closed/noninstructional days. Captures roster from dated class and school enrollment.',zj(attendance.attendanceOpenInput));
add('/school/attendance/sessions/{id}','get','Read captured roster, marks and closeout status',teaching);
add('/school/attendance/sessions/{id}','put','Save a draft or submit complete attendance',teaching+' Current version and complete captured roster required. Submitted changes require school office access and a reason. Code-required notes enforced at submission.',zj(attendance.attendanceSaveInput));
add('/school/attendance/sessions/{id}/reconcile','post','Refresh roster from dated enrollment',office+' Preserves removed marks and reopens roll call as draft.',object({version:{type:'integer',minimum:1},reason:{type:'string',minLength:5,maxLength:1000}}));
add('/school/attendance/sessions/{id}/history','get','Read immutable attendance revisions',teaching);
const dayQuery=[...yearQuery,q('date',{type:'string',format:'date'},true),q('period',str,true)];
add('/school/attendance/overview','get','Review homeroom coverage and absences',office+' Missing submissions are distinct from absence. Denominator follows dated enrollment, including historically enrolled inactive students.',undefined,{query:dayQuery});
add('/school/attendance/export','get','Export submitted attendance records',office+' Formula-safe CSV; audited.',undefined,{query:dayQuery,csv:true});
add('/school/attendance/closeouts','post','Close reviewed daily attendance',office+' Fresh fingerprint/version, all students reported and explicit unexcused-absence acknowledgment required. Closed days reject attendance changes.',zj(attendance.attendanceCloseInput));
add('/school/attendance/closeouts/{id}/reopen','post','Reopen a closed day for correction',office+' Version and reason required.',object({version:{type:'integer',minimum:1},reason:{type:'string',minLength:10,maxLength:1000}}));


const timeAccess='Current password session and current MFA proof required, with final expiry check on reads, writes and successful retries. PIN and agent tokens are denied. Employees read their own shifts; reporting roles need access to every captured and current unit in a whole shift. Correction histories with broader original/proposed job-unit scope are separately filtered. Creator identity alone grants no retained access.';
add('/time-records','get','List scoped recorded shifts and pending correction counts',timeAccess+' 100 rows per page, at most 367 days.',undefined,{query:[q('start',{type:'string',format:'date'},true),q('end',{type:'string',format:'date'},true),q('userId',uuid),q('offset',{type:'integer',minimum:0,maximum:100000,default:0})]});
add('/time-records/{id}','get','Read current shift and visible correction history',timeAccess);
add('/time-corrections','post','Propose a correction to a completed shift',timeAccess+' Employee or scoped manager; complete ordered contiguous segments, assigned/recorded jobs, no future timestamps or overlap. Preserve unchanged source boundaries exactly: up to6 fractional digits are accepted only when equal to an original locked boundary; newly edited instants use at most3. commandId retries must use identical input. Nothing changes until approval.',zj(correctionInput),{status:201});
add('/time-corrections/{id}/review','post','Approve and apply or decline a correction',timeAccess+' Scoped manager other than proposer and affected employee. Approval revalidates source revision, jobs and overlaps, appends new segments and selects the new shift revision. Original segments stay unchanged. Identical review retries return the original decision.',zj(correctionReviewInput));
add('/time-corrections/{id}/cancel','post','Cancel own pending correction',timeAccess+' Proposer and current version required.',object({version:{type:'integer',minimum:1}}));

add('/school/admissions/settings','get','Read unit admissions checklist template',office,undefined,{query:unitQuery});
add('/school/admissions/settings','put','Version and confirm admissions checklist',office+' Requires explicit confirmation before offers, acceptance or enrollment. Existing applications must explicitly refresh a changed template.',zj(admissions.admissionSettingsInput));
add('/school/admissions','get','List applications and stage counts',office+' 50 rows per page; counts use selected unit and year.',undefined,{query:[...yearQuery,q('search',str),q('status',{enum:admissions.admissionStages}),q('offset',{type:'integer',minimum:0,maximum:100000,default:0})]});
add('/school/admissions','post','Record inquiry and optional new contact',office+' commandId retries require identical input. Existing student identity is reused for re-enrollment. No contact permissions are granted.',zj(admissions.admissionCreateInput),{status:201});
add('/school/admissions/{id}','get','Read application and private review history',office);
add('/school/admissions/{id}','patch','Update application contact, requested grade and office notes',office+' Current application version and reason required.',zj(admissions.admissionEditInput));
add('/school/admissions/{id}/stage','post','Record an admissions decision',office+' Valid transitions only. Offered/accepted stages require current confirmed policy and completed or waived required items. Enrolled stage is available only through reviewed conversion.',zj(admissions.admissionStageInput));
add('/school/admissions/{id}/checklist','post','Review an application checklist item',office+' Current version required. Complete/waived items require an evidence reference or waiver reason; files are not uploaded by this route.',zj(admissions.admissionChecklistInput));
add('/school/admissions/{id}/refresh-checklist','post','Apply the current checklist to an existing application',office+' Requires application and policy versions plus a reason. New or changed items become pending; offered/accepted applications return to review.',object({version:{type:'integer',minimum:1},policyVersion:{type:'integer',minimum:0},reason:{type:'string',minLength:10,maxLength:2000}}));
add('/school/admissions/{id}/enroll','post','Convert accepted application into dated school enrollment',office+' Requires current confirmed checklist and complete required items. Reuses applicant identity, preserves existing contact permissions and grants no guardian/pickup authority. New communication permission must be explicit. Concurrent retries cannot duplicate enrollment.',zj(admissions.admissionEnrollInput));

add('/school/grading/settings','get','Read grading policy configuration',teaching,undefined,{query:unitQuery});
add('/school/grading/settings','put','Version and confirm school grading rules',office+' New gradebooks snapshot this policy. Existing gradebooks retain their original policy and version. No actual STJW scale is assumed.',zj(grading.gradingSettingsInput));
add('/school/gradebooks','get','List class gradebooks, terms and current grading configuration',teaching,undefined,{query:[q('sectionId',uuid,true)]});
add('/school/gradebooks','post','Open or retrieve class-term gradebook',teaching+' Captures dated enrollment and a confirmed policy. One gradebook per class/term; 1–200 students.',zj(grading.gradebookOpenInput),{status:201});
add('/school/gradebooks/{id}','get','Read scores, calculations, roster validity and review metadata',teaching+' Up to 500 assignments, 100 recent private history entries and 50 release summaries. Old releases remain stored. Percentages are strings; exact rational arithmetic determines labels before display rounding.');
add('/school/grade-assignments','post','Create an assignment with a dated roster',teaching+' Open book/current version required. commandId retries require the same actor and input. maxPointsUnits is hundredths of one point.',zj(grading.gradeAssignmentInput),{status:201});
add('/school/grade-assignments/{id}','patch','Revise or archive an assignment',teaching+' Open book, current book/assignment versions and reason required. Due-date eligibility is reconciled while preserving old scores.',zj(grading.gradeAssignmentEditInput));
add('/school/grade-assignments/{id}/scores','put','Save a complete captured assignment score batch',teaching+' Exact expected roster required. Points use integer hundredths. Exempt/incomplete work requires a note; extra credit follows the captured policy. Changes are privately audited.',zj(grading.gradeScoresInput));
add('/school/gradebooks/{id}/review','post','Submit, lock or reopen a gradebook',teaching+' Only school office locks/reopens. Complete grading and current roster required before submission/locking; missing work and absent calculations need explicit acknowledgment. Locks create immutable snapshots; reopening preserves them.',zj(grading.gradebookReviewInput));
add('/school/gradebooks/{id}/reconcile','post','Reconcile gradebook enrollment and assignment eligibility',office+' Open book/current version/reason required. Removed scores remain recorded; newly eligible students begin ungraded.',zj(grading.gradebookReconcileInput));
add('/school/gradebooks/{id}/releases/{releaseId}','get','Read one immutable reviewed gradebook result',teaching+' Access is rechecked against the class. Historical snapshot retains policy, inputs, output and reviewer.');
add('/school/gradebooks/{id}/export','get','Export class results and calculation provenance',teaching+' Formula-safe CSV; audited. Includes book/policy versions, status and roster validity.',undefined,{csv:true});

const careAccess=schoolAccess+' School office access or explicit program assignment with current unit membership required; classroom assignment alone does not grant access.';
add('/care/access','get','List assigned care programs and office units',careAccess);
add('/care/programs','post','Create care program and assign staff',office+' Explicit capacity, instructions and confirmation. No inferred school policies or staffing ratios.',zj(care.careProgramInput),{status:201});
add('/care/programs/{id}','get','Read scoped roster and current child occupancy',careAccess+' Staff see current dated enrollment plus children still checked in. No birth dates or household details.');
add('/care/programs/{id}','patch','Update care program configuration and staff',office+' Current version required. Cannot archive with open child sessions or reduce capacity below occupancy.',zj(care.careProgramInput));
add('/care/programs/{id}/enrollments','post','Create or update dated care enrollment',office+' Current version required; 500 retained child enrollments per program. Enrollment is independent of academic registration.',zj(care.careEnrollmentInput));
add('/care/check-in','post','Record staff receipt of a child',careAccess+' Confirmed active program/current enrollment/current program version required; server clock, capacity, child lock and actor-bound idempotency.',zj(care.careCheckinInput));
add('/care/sessions/{id}/pickup','get','Read current pickup permissions for an open session',careAccess+' Explicit pickup flags and expiry, contact and person versions, restrictions and holds. A guardian flag alone is insufficient.');
add('/care/sessions/{id}/check-out','post','Record verified handoff to a permitted adult',careAccess+' Current contact/person versions and staff identity/release confirmations required. Any contact restriction or child hold blocks release. Original evidence immutable after checkout; retry returns original result.',zj(care.careCheckoutInput));
add('/care/students/{id}/hold','get','Read child pickup hold',office);
add('/care/students/{id}/hold','put','Place or resolve child pickup hold',office+' Current version and reason required; private append-only history.',zj(care.careHoldInput));
const careQuery=[q('programId',uuid,true),q('from',{type:'string',format:'date'},true),q('to',{type:'string',format:'date'},true),q('studentId',uuid)];
add('/care/timesheets','get','Report exact child care time and release evidence',office+' Date boundaries use organization timezone; elapsed time clipped to the range and as-of instant. Maximum 5,000 sessions; narrow overly broad queries.',undefined,{query:careQuery});
add('/care/timesheets/export','get','Download child timesheet CSV with provenance',office+' Formula-safe CSV. Includes exact milliseconds, versions, actors, pickup verification and time window; not a billing calculation.',undefined,{query:careQuery,csv:true});
const dismissalAccess=schoolAccess+' Explicit dismissal assignment/current unit membership or school office access required. School teacher and childcare grants do not imply dismissal access.';
add('/dismissal/access','get','List scoped dismissal units',dismissalAccess);
add('/dismissal/settings','get','Read dismissal instructions and staff assignments',dismissalAccess,undefined,{query:unitQuery});
add('/dismissal/settings','put','Configure and confirm dismissal instructions and staff',office+' Version/reason required; independent grants. New days capture policy; access changes apply immediately.',zj(dismissal.dismissalSettingsInput));
add('/dismissal/runs','get','List dismissal days',dismissalAccess,undefined,{query:[...unitQuery,q('offset',{type:'integer',minimum:0,maximum:10000})]});
add('/dismissal/runs','post','Open today with captured school enrollment',office+' Confirmed instructions/current school year required; one run per unit/day and actor-bound command retry. Every enrolled child starts unaccounted for. Maximum 1,000 children.',zj(dismissal.dismissalOpenInput));
add('/dismissal/runs/{id}','get','Read expected roster, queue, bus manifests and closeout state',dismissalAccess+' Current enrollment fingerprint detects drift. Released records and prior closeouts persist.');
add('/dismissal/runs/{id}/plans','post','Set reviewed daily pickup or bus plans',office+' Entry versions and reason required. Already-resolved children cannot change plans; called children return to present.',zj(dismissal.dismissalPlanInput));
add('/dismissal/runs/{id}/entries/{studentId}/action','post','Record presence, call, absence resolution or verified release',dismissalAccess+' Office-only absence/return from absence. Pickup uses current permission/identity/expiry/hold checks; bus requires verified unchanged driver/vehicle arrival and explicit boarding. Calls do not release. Today/open/current roster required except office absence resolution and call cancellation can resolve roster drift. Exact command retries supported.',zj(dismissal.dismissalEntryInput));
add('/dismissal/runs/{id}/entries/{studentId}/pickup','get','Read current pickup and child hold evidence',dismissalAccess+' Child must belong to this dismissal record. No birth date or household access.');
add('/dismissal/runs/{id}/buses','post','Add an approved driver and vehicle for this day',office+' Maximum 100 buses.',zj(dismissal.dismissalBusInput));
add('/dismissal/runs/{id}/buses/{busId}','patch','Change a bus before any recorded boardings',office+' Version/reason required. Resets arrival verification; prior calls must be cancelled and made again.',zj(dismissal.dismissalBusInput));
add('/dismissal/runs/{id}/buses/{busId}/arrival','post','Verify actual driver and vehicle arrival',dismissalAccess+' Identity method and explicit driver/vehicle checks required. Versioned/idempotent; no child release.',zj(dismissal.dismissalBusArrivalInput));
add('/dismissal/runs/{id}/reconcile','post','Reconcile dated enrollment with the dismissal denominator',office+' Open today/version/reason. Preserve removed records and immutable handoffs. Present or called children cannot silently disappear.',zj(dismissal.dismissalReconcileInput));
add('/dismissal/runs/{id}/review','post','Close a fully accounted day or reopen today',office+' Reviewed fingerprint/version/reason required. No unresolved expected children; closing stores an immutable snapshot. Earlier releases/closeouts are preserved.',zj(dismissal.dismissalReviewInput));
add('/dismissal/runs/{id}/closures/{closureId}','get','Read preserved closeout evidence',office);
add('/dismissal/runs/{id}/export','get','Export dismissal roster and release provenance',office+' Formula-safe CSV; export audited. Includes removed/expected records, run and entry versions, roster validity and handoff evidence.',undefined,{csv:true});
const spec={openapi:'3.1.0',info:{title:'STJW workspace API',version:'0.1.0',description:'Implemented workforce, calendar, messaging, school, attendance, admissions, grading, report cards, timetable, care/dismissal, report-library, imported financial analysis and compensation routes. Staff-directory and workforce-report reads have explicit response schemas; most other responses remain open and their service contracts require further documentation. Canonical input validation is in shared contracts and server modules. Parent portals, authoritative accounting, cumulative academic policy calculations and Google integration are not exposed.'},servers:[{url:'https://stjw-web-production.up.railway.app/api'},{url:'http://localhost:3000/api'}],paths,components:{schemas,securitySchemes:{Session:{type:'apiKey',in:'cookie',name:'__Host-stjw',description:'Production cookie; development uses stjw_session.'},AgentBearer:{type:'http',scheme:'bearer',description:'Expiring owner-issued read-only scoped token; never put in query strings.'}}}};
const gradeImportAccess='Password session; current owner/admin, school-office grant or assigned teacher in the unit. Preview and receipt remain private to their creator. Academic/account/grant/gradebook locks recheck access and captured roster.';
add('/school/grade-assignments/{id}/import-template','get','Download versioned assignment score CSV',gradeImportAccess,undefined,{csv:true});
add('/school/grade-assignments/{id}/import-previews','post','Preview complete captured-roster score import',gradeImportAccess+' Exact columns, 200 rows, 400000 characters, current template versions and five-character reason required.',zj(gradeImportPreviewInput));
add('/school/grade-assignments/{id}/import-previews','get','List personal grade previews and receipts',gradeImportAccess);
add('/school/grade-imports/{id}','get','Read private score change preview and receipt',gradeImportAccess);
add('/school/grade-imports/{id}/source','get','Download original imported CSV as text attachment',gradeImportAccess);
add('/school/grade-imports/{id}/apply','post','Apply reviewed scores atomically with immutable receipt',gradeImportAccess+' Exact source and plan hashes; expires after 24 hours. Retry returns the same receipt. Stale grades, roster changes, duplicate students and incomplete rosters are rejected.',zj(gradeImportApplyInput));
const financeAccess='Password session; current active developer/owner/admin/finance role. Exact unit and organization scope; previews private to creator. Immutable imported source versions remain separate from accounting books; publishing a source does not post ledger journals.';
add('/finance/template','get','Download financial report CSV template',financeAccess,undefined,{csv:true});
add('/finance/reports','get','List financial report collections',financeAccess,undefined,{query:[q('unitId',uuid,true),q('archived',{type:'string',enum:['true','false']})]});
add('/finance/previews','post','Preview a financial source or correction',financeAccess,zj(financePreviewInput),{status:201});
add('/finance/previews/{id}','get','Read a private financial preview',financeAccess);
add('/finance/previews/{id}/publish','post','Publish reviewed immutable financial source',financeAccess,zj(financePublishInput));
add('/finance/reports/{id}','get','Read financial collection and version history',financeAccess);
add('/finance/reports/{id}/versions/{version}','get','Read or download a financial source version',financeAccess,undefined,{query:[q('format',{type:'string',enum:['json','csv','source']})]});
paths['/finance/reports/{id}/versions/{version}'].get.parameters.find((p:any)=>p.name==='version').schema={type:'integer',minimum:1};
add('/finance/reports/{id}/archive','post','Archive or restore a report collection',financeAccess,object({stateVersion:{type:'integer',minimum:1},archived:{type:'boolean'},reason:{type:'string',minLength:3,maxLength:1000}}));
add('/finance/reports/{id}/history','get','Read private archive/restore evidence',financeAccess);
add('/finance/compare','post','Compare immutable financial report versions',financeAccess,zj(financeComparisonInput));
add('/finance/compare/export','post','Export financial comparison with provenance',financeAccess,zj(financeComparisonInput),{query:[q('format',{type:'string',enum:['csv','json']})]});
const factorAccess='Password session required. MFA optional for all roles. Enrollment and changes require fresh current-password proof; factor changes revoke sessions and API credentials atomically.';
const passwordProof=object({password:{type:'string',minLength:1,maxLength:128}}), code={type:'string',minLength:6,maxLength:40};
add('/auth/mfa','get','Read authenticator enrollment status',factorAccess);
add('/auth/mfa/enroll','post','Start private authenticator enrollment',factorAccess,passwordProof);
add('/auth/mfa/confirm','post','Confirm enrollment and reveal recovery codes once',factorAccess,object({id:uuid,code:{type:'string',pattern:'^\\d{6}$'}}));
add('/auth/mfa/verify','post','Complete password sign-in second factor', 'Public endpoint with one-use password challenge. Valid authenticator or recovery code required; no browser session before completion.',object({challenge:{type:'string',minLength:32,maxLength:100},code}),{public:true});
for(const action of ['disable','recovery-codes'])add('/auth/mfa/'+action,'post',action==='disable'?'Disable optional authenticator':'Replace recovery codes',factorAccess,object({password:{type:'string',minLength:1,maxLength:128},code}));
const organizationAccess='Current active owner/admin password account. Organizational hierarchy grants no access: manager unit memberships and domain grants remain explicit. Account and organization locks, exact preview, expected revisions and atomic audit are required for writes.';
add('/organization/structure','get','Read organization hierarchy and direct unit counts',organizationAccess);
add('/organization/units/preview','post','Preview creation or reorganization of one unit',organizationAccess,zj(unitChangeInput));
add('/organization/units/save','post','Apply reviewed unit metadata with immutable command receipt',organizationAccess,zj(unitSaveInput));
add('/organization/units/{id}/history','get','Read retained unit metadata and hierarchy changes',organizationAccess);
const {compensationPreviewInput,compensationSaveInput,compensationImportInput}=await import('../shared/compensation');
const compensationAccess='Current active owner/admin/finance password account only; managers and staff have no pay-record access. Explicit owner decision. Exact dated amounts are records, not earned wage calculations. Actual matching password-session proof is mandatory after canonical sorted actor/target SHARE locks, with completed onboarding and enrolled MFA proof; repeat after result serialization and audit before commit. Paired operations acquire the canonical compensation pair mutex before accounts. Current pay authority is organization-wide; removal of a unit membership alone does not remove a current financial role. PIN/bearer remain denied. All responses are private, no-store. Historical command fingerprint and receipt formats are preserved; exact replay requires fresh/final proof before checking mutable source. Shared account locks recheck roles and target assignment. Effective dates inclusive, no overlapping non-void entries, previous entries retained. Atomic schedule/history/command/audit writes, fixed expected revision and reviewed preview hash.';
add('/compensation/staff','get','List employee identities for private pay records',compensationAccess);
add('/compensation/jobs','get','List assigned jobs and retained historical pay records',compensationAccess,undefined,{query:[q('userId',uuid,true)]});
for(const path of ['record','history','export'])add('/compensation/'+path,'get',path==='record'?'Read employee job pay record':path==='history'?'Read ten private pay-record versions with cursor pagination':'Export exact recorded pay rates as CSV or JSON',compensationAccess,undefined,{query:[q('userId',uuid,true),q('jobId',uuid,true),...(path==='export'?[q('format',{type:'string',enum:['csv','json']})]:[])]});
add('/compensation/preview','post','Preview exact employee job rate changes',compensationAccess,zj(compensationPreviewInput));
add('/compensation/save','post','Save reviewed compensation revision with retry receipt',compensationAccess,zj(compensationSaveInput));
add('/compensation/template','get','Download editable CSV for one employee and job',compensationAccess,undefined,{query:[q('userId',uuid,true),q('jobId',uuid,true)]});
add('/compensation/import-preview','post','Review a full employee job rate schedule from CSV',compensationAccess+' Maximum 200 rows and 64,000 UTF-8 bytes. Retained IDs and record version required. Blank rateId creates a reviewed new ID. Existing entries cannot be omitted; void them explicitly. The original submitted CSV is verified against the proposed rates again at save and retained privately with the immutable version.',zj(compensationImportInput));
add('/compensation/history-source','get','Download original submitted pay import text',compensationAccess+' Text attachment with original UTF-8 source and verified SHA-256. Source bytes are excluded from the paginated history catalog.',undefined,{query:[q('userId',uuid,true),q('jobId',uuid,true),q('version',{type:'integer',minimum:1},true)]});
paths['/compensation/history'].get.parameters.push(q('beforeVersion',{type:'integer',minimum:1}));
await writeFile('docs/openapi.json',JSON.stringify(spec,null,2)+'\n');
console.log(`Documented ${Object.keys(paths).length} implemented API paths.`);

// Extend the base contract with all later domains on every regeneration.
await import('./api-report-library');
await import('./api-care-transfers');
await import('./api-school-imports');
await import('./api-report-cards');
await import('./api-timetable');
await import('./api-attendance-reports');
await import('./api-schedule-requests');
await import('./api-report-snapshots');
await import('./api-timetable-export');
await import('./api-standing-policies');
await import('./api-gpa-policies');
await import('./api-standing-decisions');
await import('./api-gpa-decisions');
await import('./api-time-adjustments');
await import('./api-import-workbooks');
await import('./api-staff-imports');
await import('./api-organization-branding');
await import('./api-readable-reports');
await import('./api-accounting');
await import('./api-editing');
await import('./api-workforce-live');
const complete=JSON.parse(await readFile('docs/openapi.json','utf8')); console.log('Complete API inventory: '+Object.keys(complete.paths).length+' paths.');
