import{readFile,writeFile}from'node:fs/promises';import{z}from'zod';import{meetingInput,timetableSaveInput,timetableCancelInput,timetableRoomInput}from'../shared/timetable';
const doc=JSON.parse(await readFile('docs/openapi.json','utf8')),base=doc.paths['/report-library'].post;
function add(method:string,path:string,summary:string,description:string,schema?:any){const op:any={operationId:method+'_'+path.replace(/[^a-zA-Z0-9]/g,'_'),summary,description,security:[{Session:[]}],responses:base.responses,parameters:[...path.matchAll(/{([^}]+)}/g)].map(m=>({in:'path',name:m[1],required:true,schema:{type:'string',format:'uuid'}}))};if(schema)op.requestBody={required:true,content:{'application/json':{schema:z.toJSONSchema(schema)}}};doc.paths[path]??={};doc.paths[path][method]=op;}
const scope='Password session required. Office writes need current school-office unit scope; teachers read only currently assigned classes in their current units. ';
add('get','/school/timetable','Read instructional class occurrences',scope+'Required unitId/yearId/from/to (inclusive dates, at most 367 days). Optional sectionId/teacherId, office-only exact studentNumber, and format=json|csv. Student identities are not returned. CSV includes meeting ID and version.');
add('get','/school/timetable/calendar','Read class events for the standalone calendar',scope+'Required from/to inclusive dates, at most 43 days. Current office or teacher class scope. Read-only calendar-shaped events; no student roster. No calendar-event mutation is available for these derived events.');
add('get','/school/timetable/meetings','List meeting patterns including canceled records',scope+'Office-only. Required unitId and yearId.');
add('get','/school/timetable/rooms','List unit timetable rooms',scope+'Required unitId.');
add('post','/school/timetable/rooms','Create an explicit room resource',scope+'Office-only. Case-insensitive organization-unique name. Room belongs to this unit; free-text class room labels are not reservations.',timetableRoomInput);
add('post','/school/timetable/preview','Preview instructional dates and scheduling conflicts',scope+'Office-only. Returns current revision, occurrence count/date bounds, conflict explanations and teacher assignment count. No business mutation. Requires confirmed instructional weekdays. DST-ambiguous/nonexistent endpoints reject. Cross-unit private class names are redacted.',meetingInput);
add('post','/school/timetable/save','Save a reviewed recurring class meeting',scope+'Office-only. Current preview revision, expected meeting version if editing, reviewed=true and actor command ID. Whole-timetable teacher/student/room/class conflict validation under an organization lock. Dated roster places reserve students even if enrollment/profile is inactive; every assigned teacher reserves time. Atomic mutation/history/receipt. Same-command retries return their original result after current scope check.',timetableSaveInput);
add('post','/school/timetable/{id}/cancel','Cancel a current meeting pattern',scope+'Office-only. Expected version, reason and actor command ID. Retains immutable school history and existing attendance.',timetableCancelInput);
add('get','/school/timetable/{id}/history','Read timetable plan revisions',scope+'Office-only. Latest 100 private school history records including prior plans and reasons.');
for(const path of ['/school/timetable','/school/timetable/calendar','/school/timetable/meetings','/school/timetable/rooms']) {const names=path.endsWith('/calendar')?['from','to']:path.endsWith('/rooms')?['unitId']:path.endsWith('/meetings')?['unitId','yearId']:['unitId','yearId','from','to'];doc.paths[path].get.parameters=names.map(name=>({in:'query',name,required:true,schema:{type:'string',format:['from','to'].includes(name)?'date':'uuid'}}));}
for(const name of ['sectionId','teacherId','studentNumber','format'])doc.paths['/school/timetable'].get.parameters.push({in:'query',name,schema:{type:'string',...(name.endsWith('Id')?{format:'uuid'}:{}),...(name==='format'?{enum:['json','csv']}:{})}});
await writeFile('docs/openapi.json',JSON.stringify(doc,null,2)+'\n');console.log(Object.keys(doc.paths).length+' documented paths');
