import{readFile,writeFile}from'node:fs/promises';import{z}from'zod';import{previewSchoolImportInput,applySchoolImportInput,schoolImportKinds}from'../shared/school-imports';
const doc=JSON.parse(await readFile('docs/openapi.json','utf8')),base=doc.paths['/report-library'].post;
function add(method:string,path:string,summary:string,description:string,schema?:any,unitQuery=false){const op:any={operationId:method+'_'+path.replace(/[^a-zA-Z0-9]/g,'_'),summary,description,security:[{Session:[]}],responses:base.responses,parameters:[...path.matchAll(/{([^}]+)}/g)].map(m=>({in:'path',name:m[1],required:true,schema:m[1]==='kind'?{type:'string',enum:schoolImportKinds}:{type:'string',format:'uuid'}}))};if(unitQuery)op.parameters.push({in:'query',name:'unitId',required:true,schema:{type:'string',format:'uuid'}});if(schema)op.requestBody={required:true,content:{'application/json':{schema:z.toJSONSchema(schema)}}};doc.paths[path]??={};doc.paths[path][method]=op;}
const scope='Current actual password session and school-office access to the unit required. Account, onboarding, optional MFA, role, explicit memberships and office grant are rechecked and locked in the transaction; final wall-clock session expiry is checked before publishing a response or committing evidence, including already-applied retries. PIN/bearer and omitted proof are denied. Academic mutations keep the academic advisory lock before domain locks. Private to the creating account; another owner cannot retrieve or apply its preview. ';
add('get','/school/imports/template/{kind}','Download a school CSV template',scope+'Exact ordered headers, UTF-8; seven CSV kinds: students, enrollments, roster, households, household_members, contacts, people. populated=true includes current family or eligible person-profile records, capped at 500 with no silent truncation. Response is text/csv.',undefined,true);
doc.paths['/school/imports/template/{kind}'].get.parameters.push({in:'query',name:'populated',required:false,schema:{type:'string',enum:['true','false'],default:'false'}});
doc.paths['/school/imports/template/{kind}'].get.responses={...base.responses,'200':{description:'Blank CSV template',content:{'text/csv':{schema:{type:'string'}}}}};
add('post','/school/imports/preview','Validate a school CSV without applying records',scope+'Select unit plus year or class when required by kind. Family records require exact UUIDs and versions; contacts additionally require the matching student number. Every contact permission is explicit. Expiry and restriction changes require keep/replace/clear; new pickup grants require an explicit expiry or no-expiry choice. Membership grants no contact or portal permissions. Maximum 500 rows, 400000 UTF-8 bytes, 4096-character records. Row errors remain reviewable and block apply. Person profiles use exact IDs/versions and explicit keep/replace/clear email/phone actions. Creates never match or merge names/emails; student/applicant identities are ineligible. No accounts, family links or student permissions are created. Original UTF-8 source retained privately. Preview expires after 24 hours; 60 previews/account/hour.',previewSchoolImportInput);
add('get','/school/imports','List your 50 latest school previews and receipts',scope+'Latest first in the selected unit. No other account data.',undefined,true);
add('get','/school/imports/{id}','Open your school preview or application receipt',scope+'Original preview and single application receipt retained; current source access rechecked.');
add('post','/school/imports/{id}/apply','Apply every reviewed school CSV change atomically',scope+'Require source/plan hashes and reviewed=true. Recheck current role/unit/office grant, retained source integrity, exact identities, selected record versions and source state. Academic advisory lock precedes domain row locks. Contacts recheck people, student enrollment/roster, permission and pickup-hold snapshots. Household memberships never change contact permissions; contacts never release a child or remove pickup holds. Person profiles prelock all existing targets with UPDATE NOWAIT before changes; contention rolls back and returns retryable503. Name/email/phone only; changed-row receipts retain exact new/current person IDs and resulting versions. All changes, private history and receipt commit together. A fresh batch must remain unexpired by database clock after writes, audit and materialization; expiry rolls back the entire transaction. Authorized applied receipts replay before expiry/source-drift validation. Conflict requires a new preview. Unchanged rows do not write. Retry returns the original immutable receipt after current access validation.',applySchoolImportInput);
add('get','/school/imports/identities/export','Download exact family and student identity references',scope+'Unit-scoped CSV with record type, UUID, name, student number and current versions. At most 5000 people and 5000 households; larger directories rejected. Current access is locked and export audited.',undefined,true);
doc.paths['/school/imports/identities/export'].get.responses={...base.responses,'200':{description:'Formula-protected identity CSV',content:{'text/csv':{schema:{type:'string'}}}}};
add('get','/school/imports/{id}/source','Download retained original school import text',scope+'Rechecks locked current role, unit and office grants; verifies SHA-256 and exact retained UTF-8 bytes. Text attachment preserves source BOM and line endings. Older previews without retained original text return 404. Export is audited.');
doc.paths['/school/imports/{id}/source'].get.responses={...base.responses,'200':{description:'Exact original UTF-8 text attachment',content:{'text/plain':{schema:{type:'string'}}}},'404':{description:'Private preview or retained original source unavailable'}};
await writeFile('docs/openapi.json',JSON.stringify(doc,null,2)+'\n');console.log(Object.keys(doc.paths).length+' documented paths');
