import{readFile,writeFile}from'node:fs/promises';import{z}from'zod';import{openReportCardInput,saveReportCardInput,reconcileReportCardInput,issueReportCardInput,reopenReportCardInput}from'../shared/report-cards';
const doc=JSON.parse(await readFile('docs/openapi.json','utf8')),base=doc.paths['/report-library'].post;
function add(method:string,path:string,summary:string,description:string,schema?:any){const op:any={operationId:method+'_'+path.replace(/[^a-zA-Z0-9]/g,'_'),summary,description,security:[{Session:[]}],responses:base.responses,parameters:[...path.matchAll(/{([^}]+)}/g)].map(m=>({in:'path',name:m[1],required:true,schema:{type:'string',format:'uuid'}}))};if(schema)op.requestBody={required:true,content:{'application/json':{schema:z.toJSONSchema(schema)}}};doc.paths[path]??={};doc.paths[path][method]=op;}
const scope='Password session and current active school-office access to the student unit required. Class teacher/workforce roles alone are insufficient for multi-class academic records. ';
add('get','/school/report-cards','List school-year students and their report cards',scope+'50-student pages, unitId/yearId required, optional search and offset.');doc.paths['/school/report-cards'].get.parameters=[...['unitId','yearId'].map(name=>({in:'query',name,required:true,schema:{type:'string',format:'uuid'}})),{in:'query',name:'search',schema:{type:'string',maxLength:120}},{in:'query',name:'offset',schema:{type:'integer',minimum:0,maximum:100000}}];
add('post','/school/report-cards/open','Open a student report for selected school-year terms',scope+'One record per student/year/term set, irrespective of term input order. 1–8 terms, at most 200 class/term source cells. Default UI selects the full year. Current classes and historical reviewed classes remain accountable. Captures only this student’s reviewed results, not classmates or assignment notes.',openReportCardInput);
add('get','/school/report-cards/{id}','Read draft, current source comparison and issued-copy history',scope+'Source fingerprint comparison does not automatically rewrite the captured draft or an issued copy.');
add('post','/school/report-cards/{id}/save','Save report presentation, comments and inclusion decisions',scope+'Draft only, expected version plus actor command ID. Every captured source cell must remain represented. No grade editing or inferred averaging.',saveReportCardInput);
add('post','/school/report-cards/{id}/reconcile','Refresh explicitly reviewed report sources',scope+'Draft only, current source hash, expected version and reason. Existing comments/exclusions remain attached to exact class/term identities. Newly found classes are included pending review.',reconcileReportCardInput);
add('post','/school/report-cards/{id}/issue','Issue an immutable report card copy',scope+'Requires reviewed=true, current source hashes/versions, at least one included reviewed result, explicit reasons for exclusions and missing/no-grade acknowledgments. Source book locks serialize against grade review changes. Atomic issue/status/history/command receipt; retry does not create another issue. No family delivery occurs.',issueReportCardInput);
add('post','/school/report-cards/{id}/reopen','Prepare a corrected report card draft',scope+'Keeps every earlier issued snapshot unchanged. A correction requires a new reviewed issue.',reopenReportCardInput);
add('get','/school/report-cards/{id}/issues/{issueId}','Read or download an immutable issued copy',scope+'Optional format=json or csv. Includes original snapshot/hash, source release provenance, latest issue number and current draft/issued state. CSV is formula-safe; JSON attachment uses format=json.');doc.paths['/school/report-cards/{id}/issues/{issueId}'].get.parameters.push({in:'query',name:'format',schema:{type:'string',enum:['csv','json']}});
await writeFile('docs/openapi.json',JSON.stringify(doc,null,2)+'\n');console.log(Object.keys(doc.paths).length+' documented paths');
