import{readFile,writeFile}from'node:fs/promises';import{z}from'zod';import{attendanceReportInput}from'../shared/attendance-reports';import{reportDefinition,saveReportInput}from'../shared/report-library';
const doc=JSON.parse(await readFile('docs/openapi.json','utf8')),base=doc.paths['/report-library'].post;
function add(method:string,path:string,summary:string,description:string,schema?:any){const op:any={operationId:method+'_'+path.replace(/[^a-zA-Z0-9]/g,'_'),summary,description,security:[{Session:[]}],responses:base.responses,parameters:[...path.matchAll(/{([^}]+)}/g)].map(m=>({in:'path',name:m[1],required:true,schema:{type:'string',format:'uuid'}}))};if(schema)op.requestBody={required:true,content:{'application/json':{schema:z.toJSONSchema(schema)}}};doc.paths[path]??={};doc.paths[path][method]=op;}
const scope='Password session and current independent school-office access or current assigned class/unit scope required. Workforce roles alone do not grant school data. ';
add('get','/school/attendance/reports/options','Read scoped attendance report options',scope+'Required unitId/yearId. Returns accessible classes, year bounds, configured plus historical periods and current instructional settings.');doc.paths['/school/attendance/reports/options'].get.parameters=['unitId','yearId'].map(name=>({in:'query',name,required:true,schema:{type:'string',format:'uuid'}}));
add('post','/school/attendance/reports/run','Run longitudinal class-period attendance reporting',scope+'Required period and date window (at most 367 days); optional up-to-50 class group and exact student number. Dates clip to the selected school year through today in the organization timezone. Immutable current revision snapshots preserve captured code meanings and student names. Draft/removed marks never count as recorded absences. Coverage is separately projected only for current homerooms, calendar and configured periods; historical periods do not create new missing-session projections. Repeatable-read source transaction, audit and source hash. Notes off by default. Maximum 20,000 student marks or class-day coverage rows; narrower filters required above limits.',attendanceReportInput);
add('post','/school/attendance/reports/export','Export full selected attendance marks or coverage',scope+'Same source and scope checks as run. format=csv|json; dataset=marks|coverage. CSV is formula-safe, notes excluded unless selected, source hash and generation timestamp included. JSON includes both datasets, interpretation and provenance. Native browser printing prints only the current displayed view/page.',attendanceReportInput);doc.paths['/school/attendance/reports/export'].post.parameters=[{in:'query',name:'format',schema:{type:'string',enum:['csv','json'],default:'csv'}},{in:'query',name:'dataset',schema:{type:'string',enum:['marks','coverage'],default:'marks'}}];
doc.paths['/report-library'].post.requestBody={required:true,content:{'application/json':{schema:z.toJSONSchema(saveReportInput)}}};doc.paths['/report-library/preview'].post.requestBody={required:true,content:{'application/json':{schema:z.toJSONSchema(reportDefinition)}}};
doc.info.description='Implemented workforce, calendar, internal messaging, school records, attendance and longitudinal reports, admissions, class grading, annual report cards, academic timetables, childcare, staff-operated dismissal and private report-library routes. Response objects remain open in this initial contract; canonical runtime validation is in shared contracts and server modules. Optional authenticator MFA, imported financial comparisons and reviewed grade CSV imports are included. Parent arrival and Google integrations remain unimplemented.';
await writeFile('docs/openapi.json',JSON.stringify(doc,null,2)+'\n');console.log(Object.keys(doc.paths).length+' documented paths');
