import { readFile, writeFile } from 'node:fs/promises';
import { z } from 'zod';
import { workbookInspectInput, workbookConvertInput, workbookTemplateInput, workbookInspectResultSchema, workbookConvertResultSchemaFor, workbookKinds, workbookIssueSchema } from '../shared/import-workbooks';
const doc = JSON.parse(await readFile('docs/openapi.json', 'utf8'));
const ref = (name: string) => ({ $ref: '#/components/schemas/' + name });
const json = (schema: unknown) => ({ 'application/json': { schema } });
for (const [name, schema] of Object.entries({ WorkbookInspection: workbookInspectResultSchema, WorkbookConversion: z.union(workbookKinds.map(workbookConvertResultSchemaFor)), WorkbookTemplateQuery: workbookTemplateInput, WorkbookIssue: workbookIssueSchema })) {
  doc.components.schemas[name] = z.toJSONSchema(schema, { io: 'input' });
}
const access = 'Actual current password session required; PIN, bearer and unfinished-account access denied. Staff requires owner, administrator or manager role and rejects unitId and assignmentId; workbook conversion does not authorize proposed staff roles or assignments. Finance requires owner, administrator or finance role and rejects unitId and assignmentId. Every school_* kind requires unitId, rejects assignmentId, and requires current owner/administrator authority or explicit unit membership plus a school-office grant; a teacher assignment alone does not authorize these school imports. Grade_scores requires assignmentId, rejects unitId, and requires current assignment access through the assigned teacher or school-office authority plus an editable gradebook and current captured roster. Current account, role, memberships, grant, MFA and actual session are checked before work and again before publication. Grade access takes the academic lock before account/source locks. Compensation_rates requires userId and jobId, rejects unitId/assignmentId and requires current owner/admin/finance access to the selected assigned pair or retained schedule. Its canonical compensation pair mutex precedes sorted actor/target account, actual session and source locks. Parsing holds no database transaction. One process-local spreadsheet operation is admitted across imports and exports; no distributed semaphore claim. ';
for (const [action, input, result] of [['inspect', workbookInspectInput, 'WorkbookInspection'], ['convert', workbookConvertInput, 'WorkbookConversion']] as const) {
  const op: any = {
    operationId: 'post_import_workbooks_' + action, summary: action === 'inspect' ? 'Inspect a bounded text-cell staff, finance, school, pay-rate or assignment-score workbook' : 'Convert explicitly selected workbook rows to exact destination CSV',
    description: access + 'Canonical base64 for at most 256 KiB. Narrow XLSX subset: text and empty cells only; formulas, numeric/date cells, external relationships and unsupported features reject across every sheet. Explicit selected sheet is required for samples and conversion; header row 1–20. Exact destination headers are required. School and staff headers must retain catalog order and each serialized CSV record is capped at 4096 UTF-8 bytes. Finance and grade_scores keep their exact unordered header sets. Grade_scores allows at most 200 data rows and 20000 UTF-8 bytes per record; Compensation_rates accepts its unique eleven-column set after trimming header whitespace, preserves original column order/text, permits at most 200 rows, caps each encoded record at 10000 UTF-8 bytes and the whole CSV at 64000 UTF-8 bytes/characters. This structural record cap is separate from the existing csv-parse max_record_size setting. Staff, finance and school kinds allow at most 500 data rows; their CSV and grade_scores CSV are capped at 200000 UTF-8 bytes. Original workbook is transient and is not retained. Conversion performs no staff, school, grade, compensation or financial business writes and does not approve an import: submit its CSV through existing staff preview/apply, finance preview/publish, school preview/apply, assignment-score preview/apply, or compensation import-preview/reviewed save with the full destination context. Those validators remain authoritative for identities, versions, timetable, contacts and permissions. Conversion does not assert that uploaded grade or pay record versions equal current versions. Audit fingerprints identify conversion only, not a permanent binding to an editable draft.',
    security: [{ Session: [] }], parameters: [{ in: 'header', name: 'Origin', required: true, schema: { type: 'string' } }, { in: 'header', name: 'X-CSRF-Token', required: true, schema: { type: 'string' } }],
    requestBody: { required: true, content: json(z.toJSONSchema(input, { io: 'input' })) },
    responses: { '200': { description: 'Current-authorized workbook result', content: json(ref(result)) } },
  };
  for (const [code, description] of Object.entries({400:'Malformed request or container',401:'Session expired or changed',403:'Current destination access denied',404:'School unit, assignment or employee/job pair unavailable',409:'Workbook fingerprint changed or grade source is no longer editable/current',413:'Workbook or decompressed/result limit exceeded',422:'Unsupported workbook feature, cell type, headers or captured roster size',429:'Spreadsheet slot occupied or request limit reached',500:'Unexpected failure',503:'Worker timeout or temporary transaction conflict'}))
    op.responses[code] = { description, content: json({ oneOf: [ref('Error'), ref('WorkbookIssue')] }) };
  doc.paths['/import-workbooks/' + action] = { post: op };
}
doc.paths['/import-workbooks/template'] = { get: {
  operationId: 'get_import_workbooks_template', summary: 'Download a text-cell template, populated for the selected assignment or pay record',
  description: access + 'Strict conditional query is defined by WorkbookTemplateQuery: unknown parameters, repeated parameters and supplied rows reject. Staff, finance and six school kinds (students, enrollments, roster, households, household_members and contacts) download blank templates. Grade_scores downloads 1–200 current captured assignment rows with exact identities, book/assignment versions, student names, statuses, points and notes as literal text. Server-generated grade rows only: callers cannot provide rows or headers. Source identity/score fingerprint must remain identical across generation or the download returns 409. Generated text must roundtrip exactly through the accepted workbook subset or explicitly reject; no silently sanitized publication. Grade filename is stjw-assignment-scores-template.xlsx. Compensation_rates downloads stjw-editable-pay-template.xlsx: complete current rates including voided entries with exact employee/job/version/rate identities and literal dates/amounts/booleans/notes. An assigned pair without a record gets an incomplete version-zero starter row without invented pay values. Server-only populated rows must fit all pay conversion limits; oversized complete records reject instead of truncating. Compare exact source/version/assignment/identity fingerprint across generation, returning409 on change. Conversion does not persist the original XLSX; a reviewed compensation save retains only its submitted converted CSV under existing source semantics. Dates, versions and permission booleans must remain text. Formatting cannot restore digits lost before import. Original CSV templates remain available. All successful responses are private, no-store.',
  security: [{ Session: [] }], parameters: [{ in: 'query', name: 'kind', required: true, schema: { type: 'string', enum: workbookKinds } }, { in: 'query', name: 'unitId', required: false, description: 'Required for every school_* kind; forbidden for staff, finance, grade_scores and compensation_rates.', schema: { type: 'string', format: 'uuid' } }, { in: 'query', name: 'assignmentId', required: false, description: 'Required for grade_scores; forbidden for all other kinds.', schema: { type: 'string', format: 'uuid' } }, ...['userId','jobId'].map(name => ({ in: 'query', name, required: false, description: 'Required only for compensation_rates; forbidden for every other kind.', schema: { type: 'string', format: 'uuid' } }))],
  responses: { '200': { description: 'Bounded XLSX template: populated captured assignment scores/pay rates or a blank staff/finance/school template', content: { 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': { schema: { type: 'string', format: 'binary' } } }, headers: { 'X-Workbook-SHA256': { schema: { type: 'string', pattern: '^[a-f0-9]{64}$' } }, 'X-Workbook-Format-Version': { schema: { type: 'string', const: '1' } } } },
    ...Object.fromEntries(['400','401','403','404','409','413','422','429','500','503'].map(code => [code, { description: 'Request, current authorization, grade/pay source freshness or spreadsheet generation unavailable', content: json({ oneOf: [ref('Error'), ref('WorkbookIssue')] }) }])) },
} };
await writeFile('docs/openapi.json', JSON.stringify(doc, null, 2) + '\n');
console.log('Workbook API documented: 3 paths.');
