import {readFile,writeFile} from 'node:fs/promises';import{z}from'zod';import{transferRequestInput,transferDecisionInput}from'../shared/care-transfers';import{dismissalPlanInput}from'../shared/dismissal';
const doc=JSON.parse(await readFile('docs/openapi.json','utf8')),base=doc.paths['/report-library'].post;
function add(method:string,path:string,summary:string,description:string,schema?:any){const op:any={operationId:method+'_'+path.replace(/[^a-zA-Z0-9]/g,'_'),summary,description,security:[{Session:[]}],responses:base.responses,parameters:[...path.matchAll(/{([^}]+)}/g)].map(m=>({in:'path',name:m[1],required:true,schema:{type:'string',format:'uuid'}}))};if(schema)op.requestBody={required:true,content:{'application/json':{schema:z.toJSONSchema(schema)}}};doc.paths[path]??={};doc.paths[path][method]=op;}
const scope='Password sessions only; organization comes from the verified account. Source dismissal access and receiving care assignment are independent. ';
add('post','/dismissal/runs/{id}/entries/{studentId}/care-transfer','Request physical handoff to assigned childcare',scope+'Dismissal staff or school office; today\'s open/current roster, expected present child, office care plan, current care enrollment/program version, no hold/restriction, and another active receiving staff assignment required. Request leaves the child present in dismissal and blocks conflicting source actions. Actor command retry is idempotent.',transferRequestInput);
add('post','/care/transfers/{id}/decision','Accept or cancel a pending childcare handoff',scope+'Accept requires a different currently assigned care staff account and explicit physical receipt, matching program version, current enrollment/capacity/roster/hold checks. Creates care arrival and linked dismissal handoff atomically. Cancel by source dismissal/office or receiving care staff leaves the child in dismissal. Completed evidence is immutable. Retries recheck current access.',transferDecisionInput);
add('get','/care/programs/{id}/transfers','List pending handoffs for a receiving program',scope+'Assigned care staff or school office. canReceive is true only for current assigned program staff; requesting accounts still cannot receive their own handoff. More than 1,000 pending rows is rejected rather than truncated.');
doc.paths['/dismissal/runs/{id}/plans'].post.requestBody.content['application/json'].schema=z.toJSONSchema(dismissalPlanInput);doc.paths['/dismissal/runs/{id}/plans'].post.description+=' Care plans require careProgramId, no busId and current enrollment in a confirmed same-unit program. Pending handoffs must be canceled before plan changes.';
await writeFile('docs/openapi.json',JSON.stringify(doc,null,2)+'\n');console.log(Object.keys(doc.paths).length+' documented paths');
