import { readFile, writeFile } from 'node:fs/promises';
import { z } from 'zod';
import { organizationBrandingCurrentSchema, publishOrganizationBrandingSchema, organizationBrandingReceiptSchema,
  organizationBrandingHistorySchema, organizationBrandingSettingsSchema } from '../shared/organization-branding';
const doc = JSON.parse(await readFile('docs/openapi.json','utf8'));
const ref = (name:string) => ({ $ref: '#/components/schemas/'+name });
const json = (schema:unknown) => ({'application/json':{schema}});
for(const [name,schema] of Object.entries({OrganizationBrandingCurrent:organizationBrandingCurrentSchema, OrganizationBrandingReceipt:organizationBrandingReceiptSchema,
  OrganizationBrandingHistory:organizationBrandingHistorySchema, OrganizationBrandingSettings:organizationBrandingSettingsSchema}))
  doc.components.schemas[name] = z.toJSONSchema(schema,{io:'input'});
const access = 'Actual current password session is required: active account, completed onboarding and enrolled MFA proof. PIN and bearer access are denied. Account/session proof is refreshed under locks and repeated after result serialization and audit before commit. Verified session identity determines organization; caller-supplied actor/organization/scope fields reject. All responses are private, no-store. ';
const errors = Object.fromEntries(Object.entries({400:'Malformed strict input/query',401:'Session expired or changed',403:'Current authority denied',409:'Changed expected version, command mismatch, configured no-op or exhausted version',422:'Stored evidence is inconsistent',429:'Request limit',503:'Temporary transaction contention; retain the identical publication command when retrying'}).map(([status,description])=>[status,{description,content:json(ref('Error'))}]));
doc.paths['/organization/branding'] = {
  get:{operationId:'get_organization_branding',summary:'Read signed-in organization identity and shared style',description:access+'Any current password account can read the current plain identity text and fixed palette/art/depth preset. An absent record is an explicitly unconfigured app starting point with version0, not an inferred official brand. Unexpected query fields reject. Publication does not change personal preferences, legal organization identity, public sign-in, PIN clock, or retained exports.',
    security:[{Session:[]}],responses:{'200':{description:'Current presentation or explicit unpublished app default',content:json(ref('OrganizationBrandingCurrent'))},...errors}},
  post:{operationId:'post_organization_branding',summary:'Publish an owner-reviewed organization style or recover its receipt',description:access+'Current owner only. Strict normalized plain text, nine existing palette IDs, artwork full/subtle/none and boolean depth. No uploads, external asset URLs, CSS or HTML interpretation. A command lock precedes account/session locks; current authorization precedes identical receipt recovery. New publication then serializes the organization version and writes current state, immutable linked history, canonical receipt and metadata audit atomically. Same command/body returns the identical receipt200 even after later publications; changed command body returns409. Preserve the commandId and entire body after transport loss,408,429 or5xx. A first publication may confirm the unchanged app defaults; configured no-op409. Restoring history is a new publication with the current expectedVersion. A successful receipt followed by a failed current refresh remains saved. Personal adoption is a separate explicit preview/save copying only accent/artwork/depth; publishing never applies preferences automatically.',
    security:[{Session:[]}],parameters:[{in:'header',name:'Origin',required:true,schema:{type:'string'}},{in:'header',name:'X-CSRF-Token',required:true,schema:{type:'string'}}],
    requestBody:{required:true,content:json(z.toJSONSchema(publishOrganizationBrandingSchema,{io:'input'}))},responses:{'200':{description:'Identical retained publication receipt on first success or exact retry',content:json(ref('OrganizationBrandingReceipt'))},...errors}},
};
doc.paths['/organization/branding/history'] = {get:{operationId:'get_organization_branding_history',summary:'Read owner-only immutable organization appearance history',description:access+'Current owner only. Descending append-only version keyset pages; beforeVersion is exclusive, limit defaults20 and is bounded1–50. Unknown/repeated queries reject. Newer publications do not remove older history; currentVersion is metadata observed with this response, not a subscription guarantee. Captured actor/reason and before/after snapshots are owner-only. nextBeforeVersion is returned only when another older row exists. No history mutation endpoint.',
  security:[{Session:[]}],parameters:[{in:'query',name:'beforeVersion',schema:{type:'integer',minimum:1,maximum:2147483647}},{in:'query',name:'limit',schema:{type:'integer',minimum:1,maximum:50,default:20}}],
  responses:{'200':{description:'Current-authorized owner history page',content:json(ref('OrganizationBrandingHistory'))},...errors}}};
doc.paths['/me/preferences'].patch.description = access+'Account UPDATE lock precedes session and membership proof. Preserve the existing strict partial preference merge and response; selecting reports as home requires the refreshed current reporting role. Input never gains branding/inheritance keys. Audit and final session proof share the transaction. This endpoint retains last-writer behavior and has no command receipt: after an ambiguous network response, read current authorized preferences and review before submitting again. An organization preset is explicitly copied into a local draft, then saved through this unchanged endpoint.';
const staffAccess = access+'Existing actor/target account UUIDs are canonicalized and locked in sorted order, using actor SHARE and target UPDATE initially, before session/membership proof. Current full target scope and proposed new role/unit/job scope are rechecked; parent units do not grant subgroups. No authorization comes from a cached role. ';
doc.paths['/staff/{id}'].patch.description = staffAccess+'Owner/self edits remain forbidden; administrators cannot manage administrators, managers can manage only employee targets whose every unit is assigned. Target must be clocked out. Proposed active jobs and units are locked and validated. Account/assignment update, target session/token/challenge revocation and audit commit with final actor proof. No command receipt is added; refresh current state after an uncertain outcome.';
doc.paths['/staff/{id}/setup-link'].post.description = staffAccess+'Target must be active and have completed temporary-credential onboarding. Replaces earlier unconsumed setup links in the same transaction; a failed audit/final proof rolls back the replacement. Returns the private one-use24-hour setup URL only after commit. URL is not logged or audited. After an uncertain response, do not assume an earlier link remains valid; explicitly issue a reviewed replacement if needed. No automatic delivery.';
doc.paths['/jobs'].post.description = access+'Current owner/admin/manager with exact explicit unit scope. Actor account/session locks precede unit SHARE; unit existence is checked inside the transaction. Job and audit commit with final actual proof. Existing201{id} response and title/unit input remain; no agent write or command receipt is added.';
await writeFile('docs/openapi.json',JSON.stringify(doc,null,2)+'\n');
console.log('Organization appearance API documented:2 paths/3 operations plus preference/staff proof updates.');
