import { useRef, useState, type CSSProperties } from 'react';
import { ArrowDownToLine, BarChart3, FileSpreadsheet, Filter, PieChart, Printer, Search, SlidersHorizontal } from 'lucide-react';
import type { AccountingReport, AccountingStatementRow } from '../shared/accounting';
import { AccountingAccountSelect } from './accounting-books';
import { AccountingAmount, AccountingEmpty, AccountingLoad, AccountingNotice, AccountingSection, AccountingTable, accountingDate, accountingDecimal, accountingMoney, accountingUnits, useAccountingAction, useAccountingResource, type AccountingContext } from './accounting-ui';

const views=[['trial_balance','Trial balance'],['position','Financial position'],['activities','Activities'],['functional_expenses','Expense functions'],['cash_movement','Cash movement'],['ledger','General ledger']] as const;
type ReportView=typeof views[number][0];
const colors=['#7d65d8','#13988e','#ce8731','#bd5a89','#408dcc','#768f35'];
function magnitude(value:bigint){return value<0n?-value:value;}
function share(value:bigint,total:bigint){return total?Number(magnitude(value)*10000n/total)/100:0;}
export function AccountingStatements({workspace,notify}:AccountingContext) {
  const initialPeriod=workspace.periods.find(p=>p.status==='open')??workspace.periods[0];
  const [from,setFrom]=useState(initialPeriod?.startsOn??''),[to,setTo]=useState(initialPeriod?.endsOn??''),[unitId,setUnitId]=useState(''),[fundId,setFundId]=useState(''),[programId,setProgramId]=useState(''),[grantId,setGrantId]=useState(''),[accountId,setAccountId]=useState(''),[view,setView]=useState<ReportView>('trial_balance'),[search,setSearch]=useState(''),[hideZero,setHideZero]=useState(false),[selectedChart,setSelectedChart]=useState(''),[showCodes,setShowCodes]=useState(false),[showOpening,setShowOpening]=useState(true),[showActivity,setShowActivity]=useState(true);
  const query=new URLSearchParams({from,to,...(unitId?{unitId}:{}),...(fundId?{fundId}:{}),...(programId?{programId}:{}),...(grantId?{grantId}:{}),...(accountId?{accountId}:{})});
  const path=from&&to&&from<=to?'/accounting/reports?'+query:null,resource=useAccountingResource<AccountingReport>(path),action=useAccountingAction(notify);
  const resourceKey=useRef(path);resourceKey.current=path+':'+view;
  const report=resource.data,precision=report?.precision??workspace.config.precision??2;
  const statementRows=report?(view==='position'?report.position:view==='activities'?report.activities:view==='functional_expenses'?report.functionalExpenses:view==='cash_movement'?report.cashMovement:[]):[];
  const chartRows=statementRows.filter(row=>row.type!=='total'&&row.type!=='balance'&&row.key!=='accumulated_activity');
  const plotted=chartRows.length?chartRows:(report?.trialBalance??[]).filter(row=>row.type==='expense').map(row=>({key:row.accountId,label:row.name,type:row.type,amount:accountingDecimal(accountingUnits(row.debit,precision)-accountingUnits(row.credit,precision),precision)}));
  const total=plotted.reduce((sum,row)=>sum+magnitude(accountingUnits(row.amount,precision)),0n);
  let angle=0;const stops=plotted.map((row,index)=>{const start=angle;angle+=share(accountingUnits(row.amount,precision),total);return `${colors[index%colors.length]} ${start}% ${angle}%`;});
  const visibleTrial=(report?.trialBalance??[]).filter(row=>(!hideZero||[row.openingDebit,row.openingCredit,row.debit,row.credit,row.closingDebit,row.closingCredit].some(value=>accountingUnits(value,precision)!==0n))&&[row.name,row.code,row.type].join(' ').toLowerCase().includes(search.toLowerCase())&&(!selectedChart||row.accountId===selectedChart));
  const visibleStatement=statementRows.filter(row=>(!hideZero||accountingUnits(row.amount,precision)!==0n)&&row.label.toLowerCase().includes(search.toLowerCase())&&(!selectedChart||row.key===selectedChart));
  const visibleLedger=(report?.ledger??[]).filter(row=>[row.accountName,row.description,row.reference,row.memo].join(' ').toLowerCase().includes(search.toLowerCase())&&(!hideZero||accountingUnits(row.debit,precision)!==0n||accountingUnits(row.credit,precision)!==0n));
  function changeView(value:ReportView){setView(value);setSelectedChart('');setSearch('');}
  function period(value:string){const found=workspace.periods.find(p=>p.id===value);if(found){setFrom(found.startsOn);setTo(found.endsOn);}}
  async function exportReport(format:'csv'|'xlsx'|'json'){if(!path)return;const captured=path+':'+view;await action.exportFile(path+'&format='+format+'&view='+view,'accounting-'+view.replaceAll('_','-')+'-'+from+'-to-'+to+'.'+format,()=>resourceKey.current===captured);}
  return <AccountingSection title="Financial statements & accountant reports" detail="Choose dates and dimensions, explore the posted books visually, then export readable reports with traceable source detail." actions={report?<><button type="button" disabled={action.busy} onClick={()=>exportReport('xlsx')}><FileSpreadsheet size={16}/>Excel report pack</button><button type="button" disabled={action.busy} onClick={()=>exportReport('csv')}><ArrowDownToLine size={16}/>This report CSV</button><button type="button" onClick={()=>window.print()}><Printer size={16}/>Print this view</button></>:undefined}>
    <div className="accounting-form-grid three accounting-no-print"><label>Start from a period<select value={workspace.periods.find(p=>p.startsOn===from&&p.endsOn===to)?.id??''} onChange={e=>period(e.target.value)}><option value="">Choose period / custom dates</option>{workspace.periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>From<input required type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Through<input required type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></label><label>Report<select value={view} onChange={e=>changeView(e.target.value as ReportView)}>{views.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Community / department<select value={unitId} onChange={e=>setUnitId(e.target.value)}><option value="">Whole organization</option>{workspace.units.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</select></label><AccountingAccountSelect accounts={workspace.accounts} value={accountId} required={false} onChange={setAccountId}/></div>
    <details className="accounting-details accounting-no-print"><summary><SlidersHorizontal size={16}/>Dimensions & reading layout</summary><div className="accounting-stack"><div className="accounting-form-grid three">{[['fund',fundId,setFundId],['program',programId,setProgramId],['grant',grantId,setGrantId]].map(([kind,value,setter])=><label key={String(kind)}>{String(kind)[0].toUpperCase()+String(kind).slice(1)}<select value={value as string} onChange={e=>(setter as (value:string)=>void)(e.target.value)}><option value="">All {kind as string}s</option>{workspace.funds.filter(f=>f.kind===kind).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>)}</div><div className="accounting-filters"><label>Find a report row<input value={search} placeholder="Name, description or account code" onChange={e=>setSearch(e.target.value)}/></label><label className="accounting-check"><input type="checkbox" checked={hideZero} onChange={e=>setHideZero(e.target.checked)}/>Hide zero rows in this view</label><label className="accounting-check"><input type="checkbox" checked={showCodes} onChange={e=>setShowCodes(e.target.checked)}/>Show account codes</label></div>{view==='trial_balance'&&<div className="accounting-actions"><label className="accounting-check"><input type="checkbox" checked={showOpening} onChange={e=>setShowOpening(e.target.checked)}/>Opening balances</label><label className="accounting-check"><input type="checkbox" checked={showActivity} onChange={e=>setShowActivity(e.target.checked)}/>Period debits & credits</label></div>}<p className="accounting-note">Dates, account and dimensions apply to exports. Search, zero-row hiding, chart selection and column toggles customize the on-screen and printed view only. Excel contains the complete report pack for the chosen accounting scope.</p></div></details>
    {!path&&<AccountingNotice>Choose an accounting period or valid start and end dates to generate statements.</AccountingNotice>}
    <AccountingLoad loading={resource.loading} error={resource.error} retry={resource.reload}/>{action.error&&<AccountingNotice tone="error">{action.error}</AccountingNotice>}
    {report&&<><div className="accounting-balance"><span>Period<strong>{accountingDate(report.from)} – {accountingDate(report.to)}</strong></span><span>Basis<strong>{report.basis==='cash'?'Cash':'Accrual'} · {report.currency}</strong></span><span>Posted period debits<strong>{accountingMoney(report.totals.debit,report.currency,report.precision)}</strong></span><span>Posted period credits<strong>{accountingMoney(report.totals.credit,report.currency,report.precision)}</strong></span></div>
      {plotted.length>0&&view!=='ledger'&&<figure className="accounting-stack" style={{margin:0}}><figcaption><strong>{chartRows.length?views.find(v=>v[0]===view)?.[1]:'Expense account activity'}</strong><p className="accounting-note">Chart sizes show the absolute magnitude of posted amounts. Negative signs stay in the labels. Totals and opening/closing balances are excluded. Choose a bar to focus the table.</p></figcaption><div className="accounting-chart-layout"><div className="accounting-donut" aria-hidden="true" style={{background:total>0n?'conic-gradient('+stops.join(',')+')':'var(--border)'}}><div><PieChart size={24}/><strong>{plotted.length}</strong><small>{chartRows.length?'statement categories':'expense accounts'}</small></div></div><div className="accounting-chart-bars">{plotted.slice(0,12).map((row,index)=><button type="button" key={row.key} aria-pressed={selectedChart===row.key} style={{'--bar-tone':colors[index%colors.length]} as CSSProperties} onClick={()=>setSelectedChart(selectedChart===row.key?'':row.key)}><span>{row.label}</span><strong>{accountingMoney(row.amount,report.currency,report.precision)}</strong><i aria-hidden="true"><b style={{width:share(accountingUnits(row.amount,precision),total)+'%'}}/></i><small>{share(accountingUnits(row.amount,precision),total).toFixed(2)}% of absolute category amounts</small></button>)}</div></div>{plotted.length>12&&<p className="accounting-note">The chart shows the first 12 categories; the report table includes all matching rows.</p>}{selectedChart&&<button type="button" onClick={()=>setSelectedChart('')}>Show all table rows</button>}</figure>}
      {view==='trial_balance'?<AccountingTable label="Trial balance"><caption>{views.find(v=>v[0]===view)?.[1]} · {accountingDate(report.from)} – {accountingDate(report.to)} · {report.currency}</caption><thead><tr><th>Account</th>{showOpening&&<><th>Opening debit</th><th>Opening credit</th></>}{showActivity&&<><th>Period debit</th><th>Period credit</th></>}<th>Closing debit</th><th>Closing credit</th></tr></thead><tbody>{visibleTrial.map(row=><tr key={row.accountId}><td><strong>{row.name}</strong><small>{showCodes?row.code+' · ':''}{row.type}</small></td>{showOpening&&<><td><AccountingAmount value={row.openingDebit} workspace={workspace}/></td><td><AccountingAmount value={row.openingCredit} workspace={workspace}/></td></>}{showActivity&&<><td><AccountingAmount value={row.debit} workspace={workspace}/></td><td><AccountingAmount value={row.credit} workspace={workspace}/></td></>}<td><AccountingAmount value={row.closingDebit} workspace={workspace}/></td><td><AccountingAmount value={row.closingCredit} workspace={workspace}/></td></tr>)}</tbody><tfoot><tr><td>Full scope totals</td>{showOpening&&<><td>—</td><td>—</td></>}{showActivity&&<><td><AccountingAmount value={report.totals.debit} workspace={workspace}/></td><td><AccountingAmount value={report.totals.credit} workspace={workspace}/></td></>}<td><AccountingAmount value={report.totals.closingDebit} workspace={workspace}/></td><td><AccountingAmount value={report.totals.closingCredit} workspace={workspace}/></td></tr></tfoot></AccountingTable>:view==='ledger'?<AccountingTable label="General ledger"><caption>Posted journal detail · {report.currency}</caption><thead><tr><th>Date</th><th>Account / entry</th><th>Debit</th><th>Credit</th><th>Reference / note</th></tr></thead><tbody>{visibleLedger.map((row,index)=><tr key={row.journalId+':'+index}><td>{accountingDate(row.date)}</td><td><strong>{row.accountName}</strong><small>{row.description}</small></td><td><AccountingAmount value={row.debit} workspace={workspace}/></td><td><AccountingAmount value={row.credit} workspace={workspace}/></td><td>{row.reference||'—'}<small>{row.memo}</small></td></tr>)}</tbody></AccountingTable>:<AccountingTable label={views.find(v=>v[0]===view)?.[1]??'Statement'}><caption>{views.find(v=>v[0]===view)?.[1]} · {view==='position'?'as of '+accountingDate(report.to):accountingDate(report.from)+' – '+accountingDate(report.to)} · {report.currency}</caption><thead><tr><th>Statement line</th><th>Amount</th></tr></thead><tbody>{visibleStatement.map(row=><tr key={row.key}><td>{row.type==='total'?<strong>{row.label}</strong>:row.label}</td><td><AccountingAmount value={row.amount} workspace={workspace}/></td></tr>)}</tbody></AccountingTable>}
      <details className="accounting-details"><summary>Report basis & review notes</summary><div className="accounting-stack">{report.notices.map(note=><p className="accounting-note" key={note}>{note}</p>)}<button type="button" disabled={action.busy} onClick={()=>exportReport('json')}>Download exact source JSON</button></div></details>
    </>}
  </AccountingSection>;
}
