import {useEffect,useState} from 'react';
import {payrollPresentationHours} from '../shared/payroll-presentation';
import {BadgeDollarSign,Download,Plus,Trash2} from 'lucide-react';
import {PlanningAccount,PlanningAmount,useAccountingPlanning,type PlanningProps} from './AccountingPlanningShared';
const earning=()=>({label:'',quantity:'',rate:'',expenseAccountId:'',fundId:null as string|null});
const employee=()=>({key:crypto.randomUUID(),userId:'',earnings:[earning()],deductions:[] as any[],employerCosts:[] as any[]});
export default function AccountingPayrollPanel({workspace,notify,onDirty}:PlanningProps){
 const ops=useAccountingPlanning(notify),[people,setPeople]=useState<any[]>([]),[runs,setRuns]=useState<any[]>([]),[selected,setSelected]=useState(''),[name,setName]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[payDate,setPayDate]=useState(''),[reason,setReason]=useState(''),[payable,setPayable]=useState(''),[employees,setEmployees]=useState([employee()]),[review,setReview]=useState(''),[actionDate,setActionDate]=useState(''),[cash,setCash]=useState('');
 const accounts=workspace.accounts,currency=workspace.config.currency;
 const load=async()=>{const data=await ops.read('/accounting/payroll');if(data)setRuns(data.rows);};useEffect(()=>{void load();void ops.read('/accounting/payroll/options').then(data=>{if(data)setPeople(data.employees);});},[]);
 const update=(key:string,change:any)=>{setEmployees(old=>old.map(e=>e.key===key?{...e,...change}:e));onDirty(true);};
 const row=runs.find(r=>r.id===selected);
 if(ops.denied)return <p role="alert">Sign in again with accounting access to view payroll preparation.</p>;
 return <section className="planning-section"><header className="planning-heading"><BadgeDollarSign/><div><h2>Payroll preparation</h2><p>Review earnings alongside recorded hours, enter accountant-confirmed deductions, and post approved labor costs.</p></div></header>
 <p className="planning-notice">This workflow calculates quantity × rate and net pay from the amounts you enter. Withholding, overtime, paid breaks, leave, and employer taxes need accountant-confirmed inputs. Recording payment documents an external transaction; it does not send money.</p>
 {ops.error&&<p className="error" role="alert">{ops.error}</p>}
 <form inert={ops.busy} className="planning-card" onChange={()=>onDirty(true)} onSubmit={async e=>{e.preventDefault();const result=await ops.write('/accounting/payroll',{name,start,end,payDate,reason,payableAccountId:payable,employees:employees.map(({key,...p})=>p)});if(result){setEmployees([employee()]);setName('');setReason('');onDirty(false);await load();setSelected(result.id);notify('Payroll draft prepared with a recorded-hours snapshot.');}}}>
 <h3>Prepare a payroll run</h3><div className="planning-form-grid"><label>Run name<input required maxLength={160} value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. October first pay period"/></label><label>Period start<input required type="date" value={start} onChange={e=>setStart(e.target.value)}/></label><label>Period end<input required type="date" value={end} onChange={e=>setEnd(e.target.value)}/></label><label>Pay date<input required type="date" value={payDate} onChange={e=>setPayDate(e.target.value)}/></label><PlanningAccount accounts={accounts} type="liability" label="Net payroll payable account" value={payable} onChange={setPayable}/></div>
 {employees.map((person,index)=><section className="planning-employee" key={person.key}><div className="planning-heading"><h4>Employee {index+1}</h4><button type="button" aria-label={'Remove employee '+(index+1)} disabled={employees.length===1} onClick={()=>{setEmployees(employees.filter(p=>p.key!==person.key));onDirty(true);}}><Trash2 size={16}/></button></div><label>Employee<select aria-label="Employee" required value={person.userId} onChange={e=>update(person.key,{userId:e.target.value})}><option value="">Choose an employee</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <h4>Earnings</h4>{person.earnings.map((line,i)=><div className="planning-earning" key={i}><label>Earning description<input required value={line.label} maxLength={160} placeholder="Regular hours, salary, or other earning" onChange={e=>update(person.key,{earnings:person.earnings.map((l,j)=>j===i?{...l,label:e.target.value}:l)})}/></label><label>Quantity<input required inputMode="decimal" value={line.quantity} placeholder="Hours or units; use 1 for a fixed amount" onChange={e=>update(person.key,{earnings:person.earnings.map((l,j)=>j===i?{...l,quantity:e.target.value}:l)})}/></label><label>Rate · {currency}<input required inputMode="decimal" value={line.rate} onChange={e=>update(person.key,{earnings:person.earnings.map((l,j)=>j===i?{...l,rate:e.target.value}:l)})}/></label><PlanningAccount accounts={accounts} type="expense" label="Earnings expense account" value={line.expenseAccountId} onChange={value=>update(person.key,{earnings:person.earnings.map((l,j)=>j===i?{...l,expenseAccountId:value}:l)})}/><label>Fund<select value={line.fundId??''} onChange={e=>update(person.key,{earnings:person.earnings.map((l,j)=>j===i?{...l,fundId:e.target.value||null}:l)})}><option value="">Unassigned</option>{workspace.funds.filter((f:any)=>f.active&&f.kind==='fund').map((f:any)=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><button type="button" disabled={person.earnings.length===1} onClick={()=>update(person.key,{earnings:person.earnings.filter((_,j)=>i!==j)})}>Remove earning</button></div>)}<button type="button" className="button" onClick={()=>update(person.key,{earnings:[...person.earnings,earning()]})}><Plus size={16}/>Add earning</button>
 <h4>Deductions & withholding</h4><p className="planning-hint">Enter amounts supplied or verified by the accountant. These reduce employee net pay and create a payable.</p>{person.deductions.map((line,i)=><div className="planning-earning" key={i}><label>Description<input required value={line.label} onChange={e=>update(person.key,{deductions:person.deductions.map((l,j)=>j===i?{...l,label:e.target.value}:l)})}/></label><label>Amount<input required inputMode="decimal" value={line.amount} onChange={e=>update(person.key,{deductions:person.deductions.map((l,j)=>j===i?{...l,amount:e.target.value}:l)})}/></label><PlanningAccount accounts={accounts} type="liability" label="Withholding or deduction payable" value={line.liabilityAccountId} onChange={value=>update(person.key,{deductions:person.deductions.map((l,j)=>j===i?{...l,liabilityAccountId:value}:l)})}/><button type="button" onClick={()=>update(person.key,{deductions:person.deductions.filter((_,j)=>i!==j)})}>Remove deduction</button></div>)}<button type="button" className="button" onClick={()=>update(person.key,{deductions:[...person.deductions,{label:'',amount:'',liabilityAccountId:''}]})}><Plus size={16}/>Add deduction</button>
 <h4>Employer costs</h4>{person.employerCosts.map((line,i)=><div className="planning-earning" key={i}><label>Description<input required value={line.label} onChange={e=>update(person.key,{employerCosts:person.employerCosts.map((l,j)=>j===i?{...l,label:e.target.value}:l)})}/></label><label>Amount<input required inputMode="decimal" value={line.amount} onChange={e=>update(person.key,{employerCosts:person.employerCosts.map((l,j)=>j===i?{...l,amount:e.target.value}:l)})}/></label><PlanningAccount accounts={accounts} type="expense" value={line.expenseAccountId} label="Employer expense" onChange={value=>update(person.key,{employerCosts:person.employerCosts.map((l,j)=>j===i?{...l,expenseAccountId:value}:l)})}/><PlanningAccount accounts={accounts} type="liability" value={line.liabilityAccountId} label="Employer cost payable" onChange={value=>update(person.key,{employerCosts:person.employerCosts.map((l,j)=>j===i?{...l,liabilityAccountId:value}:l)})}/><button type="button" onClick={()=>update(person.key,{employerCosts:person.employerCosts.filter((_,j)=>i!==j)})}>Remove employer cost</button></div>)}<button type="button" className="button" onClick={()=>update(person.key,{employerCosts:[...person.employerCosts,{label:'',amount:'',expenseAccountId:'',liabilityAccountId:''}]})}><Plus size={16}/>Add employer cost</button>
 </section>)}<button type="button" className="button" onClick={()=>{setEmployees([...employees,employee()]);onDirty(true);}}><Plus size={16}/>Add employee</button><label>Preparation note<input required minLength={5} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Describe the source of earnings and tax inputs"/></label><button className="button primary" disabled={ops.busy}>Prepare draft & capture recorded hours</button></form>
 <div className="planning-list" aria-label="Payroll preparations">{runs.map(r=><button type="button" className="planning-list-item" key={r.id} aria-pressed={selected===r.id} onClick={()=>{setSelected(r.id);setActionDate(r.payDate);setReview('');}}><strong>{r.name}</strong><span>{r.start} – {r.end} · {r.status}</span><PlanningAmount value={r.payload.totals.net} currency={r.payload.currency}/></button>)}{!runs.length&&<p>No payroll runs prepared yet.</p>}</div>
 {row&&<article className="planning-card"><div className="planning-heading"><h3>{row.name}</h3><span>{row.status}</span><button type="button" className="button" onClick={()=>void ops.exportFile('/accounting/payroll/'+row.id+'/export','reviewed-payroll.csv')}><Download size={16}/>Export payroll CSV</button></div><div className="planning-metrics">{[['gross','Gross earnings'],['deductions','Entered deductions'],['net','Net pay'],['employerCosts','Employer costs']].map(([key,title])=><div key={key}><span>{title}</span><strong><PlanningAmount value={row.payload.totals[key]} currency={row.payload.currency}/></strong></div>)}</div>
 <div className="planning-table-scroll" tabIndex={0}><table><caption>Employee review · {row.start} to {row.end}</caption><thead><tr><th>Employee</th><th>Recorded work hours</th><th>Gross</th><th>Deductions</th><th>Net</th></tr></thead><tbody>{row.payload.employees.map((p:any)=><tr key={p.userId}><th>{p.name}</th><td title={p.recordedWorkHours}>{payrollPresentationHours(p.recordedWorkMicroseconds,2)}</td><td><PlanningAmount value={p.gross}/></td><td><PlanningAmount value={p.deductionsTotal}/></td><td><PlanningAmount value={p.net}/></td></tr>)}</tbody></table></div><details><summary>Review earnings, deductions & source evidence</summary>{row.payload.employees.map((p:any)=><section key={p.userId}><h4>{p.name}</h4>{p.earnings.map((l:any,i:number)=><p key={i}>{l.label}: {l.quantity} × {l.rate} = <PlanningAmount value={l.amount}/></p>)}{p.deductions.map((l:any,i:number)=><p key={i}>{l.label}: <PlanningAmount value={l.amount}/></p>)}{p.employerCosts.map((l:any,i:number)=><p key={i}>Employer · {l.label}: <PlanningAmount value={l.amount}/></p>)}</section>)}<p>Time evidence captured {new Date(row.payload.evidence.capturedAt).toLocaleString()}. Approval checks that the selected time records have not changed.</p></details><p className="planning-notice">{row.payload.notice}</p>
 {row.status!=='voided'&&<div className="planning-actions"><label>Review / transaction note<input minLength={5} value={review} onChange={e=>setReview(e.target.value)}/></label><label>Payment / reversal date<input type="date" value={actionDate} onChange={e=>setActionDate(e.target.value)}/></label><PlanningAccount accounts={accounts} type="asset" cash label="Cash account for recorded payment" value={cash} onChange={setCash}/>
 {(row.status==='draft'?['approve','void']:row.status==='approved'?[workspace.config.basis==='cash'?'pay':'post','void']:row.status==='posted'?['pay','void']:['void']).map(action=><button type="button" className={'button '+(action==='void'?'':'primary')} key={action} disabled={ops.busy||review.trim().length<5||(action==='pay'&&(!cash||!actionDate))} onClick={async()=>{const result=await ops.write('/accounting/payroll/'+row.id+'/'+action,{expectedVersion:row.version,reason:review,reviewed:true,...(actionDate?{date:actionDate}:{}),...(action==='pay'?{cashAccountId:cash}:{})});if(result){await load();setReview('');notify(action==='pay'?'External payment recorded.':action==='void'?'Payroll voided; posted entries reversed.':'Payroll '+(action==='approve'?'approved.':'posted.'));}}}>{action==='approve'?'Approve reviewed payroll':action==='post'?'Post payroll accrual':action==='pay'?'Record external net payment':'Void & reverse payroll'}</button>)}</div>}</article>}
 </section>;
}
