import {useEffect,useRef,useState} from 'react';
import {BarChart3,Download,Plus,Trash2} from 'lucide-react';
import {PlanningAmount,PlanningAccount,useAccountingPlanning,type PlanningProps} from './AccountingPlanningShared';
const blankLine=()=>({key:crypto.randomUUID(),accountId:'',fundId:null as string|null,amount:''});
export default function AccountingBudgetPanel({workspace,notify,onDirty}:PlanningProps){
 const ops=useAccountingPlanning(notify),[rows,setRows]=useState<any[]>([]),[name,setName]=useState(''),[periodId,setPeriod]=useState(''),[reason,setReason]=useState(''),[lines,setLines]=useState([blankLine()]),[selectedId,setSelectedId]=useState(''),[report,setReport]=useState<any>(null),[reviewReason,setReviewReason]=useState(''),request=useRef(0),formRef=useRef<HTMLFormElement>(null),[copySource,setCopySource]=useState('');
 const reload=async()=>{const data=await ops.read('/accounting/budgets');if(data)setRows(data.rows);};useEffect(()=>{void reload();},[]);
 async function inspect(id:string){setSelectedId(id);const n=++request.current;setReport(null);const data=await ops.read('/accounting/budgets/'+id+'/report');if(data&&n===request.current)setReport(data);}
 if(ops.denied)return <p role="alert">Sign in again with accounting access to view budgets.</p>;
 const selectedBudget=rows.find(row=>row.id===selectedId);
 const accounts=workspace.accounts.filter((a:any)=>['revenue','expense'].includes(a.type)),funds=workspace.funds??[];
 function prepareReplacement(source:any){if(!window.confirm('Load this budget into the editor? Unsaved form changes will be replaced. The original budget remains unchanged.'))return;setName((source.name+' — replacement').slice(0,160));setPeriod(source.periodId);setReason('');setLines(source.payload.lines.map((line:any)=>({key:crypto.randomUUID(),accountId:line.accountId,fundId:line.fundId??null,amount:line.amount})));setCopySource(source.name);onDirty(true);formRef.current?.scrollIntoView({block:'start'});formRef.current?.querySelector('input')?.focus({preventScroll:true});}
 const update=(key:string,values:any)=>{setLines(old=>old.map(l=>l.key===key?{...l,...values}:l));onDirty(true);};
 return <section className="planning-section"><header className="planning-heading"><BarChart3/><div><h2>Budgets & planning</h2><p>Build a named budget for a fiscal period, review it, then compare it with posted activity.</p></div></header>{ops.error&&<p role="alert" className="error">{ops.error}</p>}
 <form ref={formRef} inert={ops.busy} className="planning-card" onChange={()=>onDirty(true)} onSubmit={async e=>{e.preventDefault();const result=await ops.write('/accounting/budgets',{name,periodId,reason,lines:lines.map(({key,...l})=>l)});if(result){onDirty(false);setName('');setCopySource('');setReason('');setLines([blankLine()]);await reload();await inspect(result.id);notify('Budget draft saved for review.');}}}>
 <h3>{copySource?'Edit a replacement budget':'Create a budget'}</h3>{copySource&&<p className="planning-notice">Loaded from {copySource}. The original plan remains in history and keeps its status. Review every line, choose an open period and add a note before saving this separate draft. Void the original if the new plan replaces it.</p>}<div className="planning-form-grid"><label>Budget name<input required value={name} maxLength={160} onChange={e=>setName(e.target.value)} placeholder="e.g. School operating plan"/></label><label>Fiscal period<select aria-label="Fiscal period" required value={periodId} onChange={e=>setPeriod(e.target.value)}><option value="">Choose an open period</option>{workspace.periods.filter((p:any)=>p.status==='open').map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div>
 <p className="planning-hint">Each line belongs to one account and one fund. “Unassigned” includes only entries without a fund.</p>
 {lines.map((l,i)=><div className="planning-line" key={l.key}><span className="planning-line-number">{i+1}</span><PlanningAccount accounts={accounts} value={l.accountId} onChange={accountId=>update(l.key,{accountId})}/><label>Fund<select value={l.fundId??''} onChange={e=>update(l.key,{fundId:e.target.value||null})}><option value="">Unassigned</option>{funds.filter((f:any)=>f.active&&f.kind==='fund').map((f:any)=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label><label>Budget · {workspace.config.currency}<input required inputMode="decimal" value={l.amount} onChange={e=>update(l.key,{amount:e.target.value})}/></label><button type="button" aria-label={'Remove budget line '+(i+1)} disabled={lines.length===1} onClick={()=>{setLines(lines.filter(x=>x.key!==l.key));onDirty(true);}}><Trash2 size={16}/></button></div>)}
 <button type="button" className="button" onClick={()=>{setLines([...lines,blankLine()]);onDirty(true);}}><Plus size={16}/>Add account</button><label>Planning note<input required minLength={5} maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="button primary" disabled={ops.busy}>Save budget draft</button></form>
 <div className="planning-list" aria-label="Saved budgets">{rows.map(r=><button type="button" key={r.id} className="planning-list-item" aria-pressed={report?.budget.id===r.id} onClick={()=>void inspect(r.id)}><strong>{r.name}</strong><span>{r.payload.period.name} · {r.status}</span></button>)}{!rows.length&&<p>No budgets yet. Create the first plan above.</p>}</div>
 {selectedBudget&&!report&&ops.error&&<article className="planning-card"><h3>{selectedBudget.name}</h3><button type="button" className="button" disabled={ops.busy} onClick={()=>prepareReplacement(selectedBudget)}>Edit a replacement draft</button><p>{selectedBudget.status==='voided'?'This budget is voided; its original plan remains in history.':'The comparison needs review. You can void this plan and create a replacement with the current accounts.'}</p>{selectedBudget.status!=='voided'&&<><label>Reason for replacing this budget<input value={reviewReason} minLength={5} onChange={e=>setReviewReason(e.target.value)}/></label><button type="button" className="button" disabled={ops.busy||reviewReason.trim().length<5} onClick={async()=>{const result=await ops.write('/accounting/budgets/'+selectedBudget.id+'/void',{expectedVersion:selectedBudget.version,reason:reviewReason,reviewed:true});if(result){setReviewReason('');await reload();notify('Budget voided; original plan retained.');}}}>Void budget for replacement</button></>}</article>}
 {report&&<article className="planning-card"><div className="planning-heading"><h3>{report.budget.name}</h3><button type="button" className="button" disabled={ops.busy} onClick={()=>prepareReplacement(report.budget)}>Edit a replacement draft</button><button className="button" onClick={()=>void ops.exportFile('/accounting/budgets/'+report.budget.id+'/report?format=csv','budget-comparison.csv')}><Download size={16}/>Export comparison</button></div><p>{report.notice}</p>
 <div className="planning-budget-chart" aria-label="Budget versus actual comparison">{report.rows.map((r:any,i:number)=>{const b=Math.abs(Number(r.budget)),a=Math.abs(Number(r.actual)),max=Math.max(b,a,1);return <div key={i}><strong>{r.accountName}</strong><span>{r.fundName}</span><div className="planning-track"><i style={{width:(b/max*100)+'%'}}/><span>Budget <PlanningAmount value={r.budget}/></span></div><div className="planning-track actual"><i style={{width:(a/max*100)+'%'}}/><span>Actual <PlanningAmount value={r.actual}/></span></div></div>;})}</div>
 <div className="planning-table-scroll" tabIndex={0}><table><caption>Posted activity · {report.currency}</caption><thead><tr><th>Account</th><th>Fund</th><th>Budget</th><th>Actual</th><th>Actual − budget</th></tr></thead><tbody>{report.rows.map((r:any,i:number)=><tr key={i}><th>{r.accountName}</th><td>{r.fundName}</td><td><PlanningAmount value={r.budget}/></td><td><PlanningAmount value={r.actual}/></td><td><PlanningAmount value={r.variance}/></td></tr>)}</tbody></table></div>
 {report.budget.status!=='voided'&&<div className="planning-actions"><label>Review note<input value={reviewReason} minLength={5} onChange={e=>setReviewReason(e.target.value)} placeholder="Record your review or reason for voiding"/></label>{(report.budget.status==='draft'?['approve','void']:['void']).map(action=><button key={action} className={'button '+(action==='approve'?'primary':'')} disabled={ops.busy||reviewReason.trim().length<5} onClick={async()=>{const result=await ops.write('/accounting/budgets/'+report.budget.id+'/'+action,{expectedVersion:report.budget.version,reason:reviewReason,reviewed:true});if(result){await reload();await inspect(result.id);setReviewReason('');notify(action==='approve'?'Budget approved.':'Budget voided; history retained.');}}}>{action==='approve'?'Approve reviewed budget':'Void budget'}</button>)}</div>}</article>}
 </section>;
}
