import { useEffect, useState } from 'react';
import { Check, CheckCircle2, Layers3, Plus, Save, Settings2, Trash2 } from 'lucide-react';
import { api } from './api';
import { accountTypes, accountingModules, cashFlowCategories, functionalCategories, type AccountingAccount, type AccountingFund, type AccountingJournal, type JournalLineInput } from '../shared/accounting';
import { AccountingAmount, AccountingEmpty, AccountingNotice, AccountingSection, AccountingTable, accountingDate, accountingDecimal, accountingMoney, accountingUnits, localToday, useAccountingAction, type AccountingContext } from './accounting-ui';

const moduleInfo: Record<string, {title:string; detail:string}> = {
  ledger: {title:'Books & statements',detail:'Accounts, funds, balanced journals, period controls and traceable financial reports.'},
  payables: {title:'Bills & vendors',detail:'Review bills, record payments made elsewhere, issue credits and see what is due.'},
  receivables: {title:'Invoices & billing',detail:'Create family or customer invoices, record receipts, credits and refunds.'},
  banking: {title:'Bank reconciliation',detail:'Preview a statement CSV, match posted cash entries and reconcile balances.'},
  budgets: {title:'Budgets & planning',detail:'Set period budgets, approve versions and compare the books with your plan.'},
  payroll: {title:'Payroll preparation',detail:'Review configured earnings and hours; prepare accountant exports and postings.'},
};
export function AccountingSettings({workspace,notify,onDirty,refresh}:AccountingContext) {
  const config=workspace.config;
  const [form,setForm]=useState({currency:config.currency??'',precision:config.precision===null?'':String(config.precision),basis:config.basis??'',month:config.fiscalStartMonth===null?'':String(config.fiscalStartMonth),day:config.fiscalStartDay===null?'':String(config.fiscalStartDay),modules:config.configured?config.modules:['ledger']});
  const [reviewed,setReviewed]=useState(false),action=useAccountingAction(notify);
  function change(patch:Partial<typeof form>){setForm(value=>({...value,...patch}));setReviewed(false);onDirty(true);}
  async function save(event:React.FormEvent){event.preventDefault();const result=await action.run(()=>api('/accounting/config',{expectedRevision:config.revision,currency:form.currency.trim().toUpperCase(),precision:Number(form.precision),basis:form.basis,fiscalStartMonth:Number(form.month),fiscalStartDay:Number(form.day),modules:form.modules}),'Accounting choices saved.');if(result){onDirty(false);refresh();}}
  return <AccountingSection title="Your accounting settings" detail="Review the starter choices with the person responsible for the books. Each workflow can be enabled independently."><form inert={action.busy} className="accounting-stack" onSubmit={save}>
    {!config.reviewed&&<AccountingNotice>Starter defaults are ready to use: US dollars, two decimal places, accrual accounting and a January–December fiscal year. Change any choice here before entering records if your organization uses different settings.</AccountingNotice>}
    <div className="accounting-form-grid three">
      <label>Currency code<input required aria-label="Accounting currency" value={form.currency} minLength={3} maxLength={3} pattern="[A-Za-z]{3}" placeholder="For example, USD" onChange={e=>change({currency:e.target.value.toUpperCase()})}/><small>One explicit currency for this set of books.</small></label>
      <label>Amount precision<select required value={form.precision} onChange={e=>change({precision:e.target.value})}><option value="">Choose precision</option>{[0,1,2,3,4].map(n=><option key={n} value={n}>{n} decimal places{n===2?' · cents':''}</option>)}</select><small>Every amount must fit this precision.</small></label>
      <label>Accounting basis<select required value={form.basis} onChange={e=>change({basis:e.target.value})}><option value="">Choose accounting basis</option><option value="cash">Cash basis</option><option value="accrual">Accrual basis</option></select><small>Cash records income and expense with payment. Accrual records them when invoices and bills are issued.</small></label>
      <label>Fiscal year starts in<select required value={form.month} onChange={e=>change({month:e.target.value})}><option value="">Choose month</option>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{new Intl.DateTimeFormat('en-US',{month:'long',timeZone:'UTC'}).format(new Date(Date.UTC(2026,i,1)))}</option>)}</select></label>
      <label>Fiscal start day<input required type="number" min={1} max={31} value={form.day} placeholder="Choose day" onChange={e=>change({day:e.target.value})}/></label>
    </div>
    <AccountingNotice tone="warning">Currency, precision and basis can be changed before financial records exist. After records exist, those settings are protected to preserve the books; changing them requires a separately reviewed migration. Fiscal-year changes do not rewrite existing period dates. Enabling a workflow does not create rates, fee rules, opening balances or a bank connection.</AccountingNotice>
    <div><h4>Choose the workflows you want</h4><div className="accounting-module-grid">{accountingModules.map(key=><article key={key} className={'accounting-module-card '+(form.modules.includes(key)?'enabled':'')}><label className="accounting-check"><input type="checkbox" checked={form.modules.includes(key)} disabled={key==='ledger'} onChange={()=>change({modules:form.modules.includes(key)?form.modules.filter(value=>value!==key):[...form.modules,key]})}/>{moduleInfo[key].title}{key==='ledger'&&<span className="accounting-status">Required</span>}</label><p>{moduleInfo[key].detail}</p></article>)}</div></div>
    <label className="accounting-check"><input required type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed these settings and want to use them for the organization’s books.</label>
    {action.error&&<AccountingNotice tone="error">{action.error}</AccountingNotice>}
    <div className="accounting-actions"><button type="submit" className="primary" disabled={!reviewed||action.busy}><Save size={17}/>{action.busy?'Saving…':config.configured?'Save accounting settings':'Create accounting workspace'}</button></div>
  </form></AccountingSection>;
}

export function AccountingAccountSelect({accounts,value,onChange,label='Account',required=true,filter}:{accounts:AccountingAccount[];value:string;onChange:(value:string)=>void;label?:string;required?:boolean;filter?:(account:AccountingAccount)=>boolean}) {
  return <label>{label}<select aria-label={label} required={required} value={value} onChange={e=>onChange(e.target.value)}><option value="">{required?'Choose account':'All accounts'}</option>{accounts.filter(a=>a.active&&(!filter||filter(a))).map(a=><option key={a.id} value={a.id}>{a.name} · {a.code}</option>)}</select></label>;
}
export function AccountingDimensions({workspace,line,onChange,extended=false}:{workspace:AccountingContext['workspace'];line:Partial<JournalLineInput>;onChange:(patch:Partial<JournalLineInput>)=>void;extended?:boolean}) {
  return <div className="accounting-line-dimensions"><label>Community / department<select value={line.unitId??''} onChange={e=>onChange({unitId:e.target.value||undefined})}><option value="">Organization-wide</option>{workspace.units.map(unit=><option key={unit.id} value={unit.id}>{unit.name}</option>)}</select></label>{(['fund',...(extended?['program','grant']:[])] as const).map(kind=><label key={kind}>{kind[0].toUpperCase()+kind.slice(1)}<select value={line[(kind+'Id') as keyof JournalLineInput]??''} onChange={e=>onChange({[kind+'Id']:e.target.value||undefined})}><option value="">Unassigned</option>{workspace.funds.filter(f=>f.active&&f.kind===kind).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>)}</div>;
}

export function AccountingBooks(context:AccountingContext) {
  const {workspace,notify,onDirty,refresh}=context;
  const [tab,setTab]=useState<'accounts'|'funds'|'periods'>('accounts'),[editing,setEditing]=useState(false),[account,setAccount]=useState<AccountingAccount|null>(null),[fund,setFund]=useState<AccountingFund|null>(null);
  const [period,setPeriod]=useState<{id:string;name:string;startsOn:string;endsOn:string}>({id:crypto.randomUUID(),name:'',startsOn:'',endsOn:''}),[periodRevision,setPeriodRevision]=useState<number|null>(null),[periodAction,setPeriodAction]=useState<{id:string;revision:number;status:'open'|'closed';name:string}|null>(null),[reason,setReason]=useState('');
  const action=useAccountingAction(notify);
  function newAccount(){setAccount({id:crypto.randomUUID(),code:'',name:'',type:'asset',isCash:false,cashFlowCategory:'unclassified',functionalCategory:'unclassified',active:true,revision:0});setEditing(true);}
  function newFund(){setFund({id:crypto.randomUUID(),code:'',name:'',kind:'fund',restriction:'unrestricted',purpose:'',active:true,allowedAccountIds:[],allowedUnitIds:[],startsOn:null,endsOn:null,revision:0});setEditing(true);}
  function start(){if(tab==='accounts')newAccount();else if(tab==='funds')newFund();else{setPeriod({id:crypto.randomUUID(),name:'',startsOn:'',endsOn:''});setPeriodRevision(null);setEditing(true);}}
  function updateAccount(patch:Partial<AccountingAccount>){setAccount(value=>value?{...value,...patch}:null);onDirty(true);}
  function updateFund(patch:Partial<AccountingFund>){setFund(value=>value?{...value,...patch}:null);onDirty(true);}
  async function save(event:React.FormEvent){event.preventDefault();let result;if(tab==='accounts'&&account){const{revision,...body}=account;result=await action.run(()=>api('/accounting/accounts',{...body,expectedRevision:revision}),'Account saved.');}else if(tab==='funds'&&fund){const{revision,...body}=fund;result=await action.run(()=>api('/accounting/funds',{...body,expectedRevision:revision}),'Dimension saved.');}else if(periodRevision===null)result=await action.run(()=>api('/accounting/periods',period),'Accounting period created.');else{const{id,...body}=period;result=await action.run(()=>api('/accounting/periods/'+id,{...body,expectedRevision:periodRevision}),'Accounting period updated.');}if(result){onDirty(false);setEditing(false);refresh();}}
  function cancel(){if(!window.confirm('Discard this unsaved form?'))return;setEditing(false);setPeriodAction(null);onDirty(false);}
  async function changePeriod(event:React.FormEvent){event.preventDefault();if(!periodAction)return;const result=await action.run(()=>api('/accounting/periods/'+periodAction.id+'/status',{expectedRevision:periodAction.revision,status:periodAction.status,reason,commandId:crypto.randomUUID()}),'Period '+(periodAction.status==='closed'?'closed.':'reopened.'));if(result){setPeriodAction(null);onDirty(false);refresh();}}
  return <AccountingSection title="Organize your books" detail="Choose meaningful account names, define funds and programs, and control when transactions can be posted." actions={!editing&&!periodAction?<button type="button" onClick={start}><Plus size={17}/>Add {tab==='accounts'?'account':tab==='funds'?'fund / program':'period'}</button>:undefined}>
    {!editing&&!periodAction&&<div className="accounting-actions" role="group" aria-label="Book setup sections">{(['accounts','funds','periods'] as const).map(key=><button type="button" key={key} aria-pressed={tab===key} className={tab===key?'primary':''} onClick={()=>setTab(key)}>{key==='accounts'?'Chart of accounts':key==='funds'?'Funds, programs & grants':'Accounting periods'}</button>)}</div>}
    {action.error&&<AccountingNotice tone="error">{action.error}</AccountingNotice>}
    {periodAction?<form inert={action.busy} onSubmit={changePeriod} className="accounting-stack"><h4>{periodAction.status==='closed'?'Close':'Reopen'} {periodAction.name}</h4><AccountingNotice tone="warning">{periodAction.status==='closed'?'Closing prevents new postings and reversals dated in this period. Resolve outstanding drafts and review the books first.':'Reopening allows further accounting entries in this period and records your reason in the audit history.'}</AccountingNotice><label>Reason<textarea required minLength={3} maxLength={1000} value={reason} onChange={e=>{setReason(e.target.value);onDirty(true);}}/></label><div className="accounting-actions"><button type="submit" className="primary" disabled={action.busy}>Confirm {periodAction.status==='closed'?'close':'reopen'}</button><button type="button" onClick={cancel}>Cancel</button></div></form>:editing?<form inert={action.busy} onSubmit={save} className="accounting-stack">
      {tab==='accounts'&&account&&<><div className="accounting-form-grid"><label>Account name<input required maxLength={120} value={account.name} onChange={e=>updateAccount({name:e.target.value})}/></label><label>Account code<input required maxLength={30} value={account.code} onChange={e=>updateAccount({code:e.target.value})}/></label><label>Account type<select value={account.type} onChange={e=>updateAccount({type:e.target.value as AccountingAccount['type'],isCash:false})}>{accountTypes.map(type=><option key={type} value={type}>{type[0].toUpperCase()+type.slice(1)}</option>)}</select></label><label>Cash-flow classification<select value={account.cashFlowCategory} onChange={e=>updateAccount({cashFlowCategory:e.target.value as AccountingAccount['cashFlowCategory']})}>{cashFlowCategories.map(type=><option key={type} value={type}>{type==='unclassified'?'Unclassified · review needed':type[0].toUpperCase()+type.slice(1)}</option>)}</select></label><label>Expense function<select value={account.functionalCategory} onChange={e=>updateAccount({functionalCategory:e.target.value as AccountingAccount['functionalCategory']})}>{functionalCategories.map(type=><option key={type} value={type}>{type==='unclassified'?'Unclassified · review needed':type[0].toUpperCase()+type.slice(1)}</option>)}</select></label><div><label className="accounting-check"><input type="checkbox" checked={account.isCash} disabled={account.type!=='asset'} onChange={e=>updateAccount({isCash:e.target.checked})}/>Cash / bank account</label><label className="accounting-check"><input type="checkbox" checked={account.active} onChange={e=>updateAccount({active:e.target.checked})}/>Active for new entries</label></div></div><p className="accounting-note">Classification drives statements. An unclassified account remains visible for review. Existing posted transactions keep their accounting history.</p></>}
      {tab==='funds'&&fund&&<><div className="accounting-form-grid"><label>Name<input required maxLength={120} value={fund.name} onChange={e=>updateFund({name:e.target.value})}/></label><label>Code<input required maxLength={30} value={fund.code} onChange={e=>updateFund({code:e.target.value})}/></label><label>Dimension type<select value={fund.kind} onChange={e=>updateFund({kind:e.target.value as AccountingFund['kind']})}><option value="fund">Fund</option><option value="program">Program</option><option value="grant">Grant</option></select></label><label>Restriction<select value={fund.restriction} onChange={e=>updateFund({restriction:e.target.value as AccountingFund['restriction']})}><option value="unrestricted">Unrestricted</option><option value="restricted">Restricted</option></select></label><label>Available from<input type="date" value={fund.startsOn??''} onChange={e=>updateFund({startsOn:e.target.value||null})}/></label><label>Available through<input type="date" value={fund.endsOn??''} onChange={e=>updateFund({endsOn:e.target.value||null})}/></label><label className="accounting-wide">Purpose / restriction<textarea required={fund.restriction==='restricted'} maxLength={1000} value={fund.purpose} onChange={e=>updateFund({purpose:e.target.value})}/></label></div><details className="accounting-details"><summary>Limit eligible accounts and communities</summary><div className="accounting-form-grid"><fieldset><legend>Accounts · none selected allows all</legend>{workspace.accounts.filter(a=>a.active).map(a=><label className="accounting-check" key={a.id}><input type="checkbox" checked={fund.allowedAccountIds.includes(a.id)} onChange={()=>updateFund({allowedAccountIds:fund.allowedAccountIds.includes(a.id)?fund.allowedAccountIds.filter(id=>id!==a.id):[...fund.allowedAccountIds,a.id]})}/>{a.name}</label>)}</fieldset><fieldset><legend>Communities · none selected allows all</legend>{workspace.units.map(u=><label className="accounting-check" key={u.id}><input type="checkbox" checked={fund.allowedUnitIds.includes(u.id)} onChange={()=>updateFund({allowedUnitIds:fund.allowedUnitIds.includes(u.id)?fund.allowedUnitIds.filter(id=>id!==u.id):[...fund.allowedUnitIds,u.id]})}/>{u.name}</label>)}</fieldset></div></details><label className="accounting-check"><input type="checkbox" checked={fund.active} onChange={e=>updateFund({active:e.target.checked})}/>Active for new entries</label></>}
      {tab==='periods'&&<><div className="accounting-form-grid"><label className="accounting-wide">Period name<input required maxLength={120} value={period.name} placeholder="For example, October 2026" onChange={e=>{setPeriod({...period,name:e.target.value});onDirty(true);}}/></label><label>First day<input required type="date" value={period.startsOn} onChange={e=>{setPeriod({...period,startsOn:e.target.value});onDirty(true);}}/></label><label>Last day<input required type="date" value={period.endsOn} min={period.startsOn} onChange={e=>{setPeriod({...period,endsOn:e.target.value});onDirty(true);}}/></label></div>{periodRevision!==null&&<AccountingNotice>Period dates can be adjusted before journals or budgets depend on them. Existing closed periods must be reopened before editing.</AccountingNotice>}</>}
      <div className="accounting-actions"><button className="primary" type="submit" disabled={action.busy}><Save size={16}/>Save {tab==='accounts'?'account':tab==='funds'?'dimension':'period'}</button><button type="button" onClick={cancel}>Cancel</button></div>
    </form>:<>
      {tab==='accounts'&&(workspace.accounts.length?<AccountingTable label="Chart of accounts"><thead><tr><th>Name</th><th>Type</th><th>Reporting</th><th>Status</th><th>Manage</th></tr></thead><tbody>{workspace.accounts.map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>{a.code}</small></td><td>{a.type}{a.isCash&&<small>Cash / bank</small>}</td><td>{a.cashFlowCategory}<small>Function: {a.functionalCategory}</small></td><td>{a.active?'Active':'Inactive'}</td><td><button type="button" onClick={()=>{setAccount(a);setEditing(true);}}>Edit account</button></td></tr>)}</tbody></AccountingTable>:<AccountingEmpty title="Add your first account" detail="Use the organization’s reviewed chart of accounts. Opening balances are entered through balanced journals." onCreate={newAccount} createLabel="Add account"/>)}
      {tab==='funds'&&(workspace.funds.length?<div className="accounting-list-grid">{workspace.funds.map(f=><article className="accounting-record-card" key={f.id}><header><h4>{f.name}</h4><span className="accounting-status">{f.kind}</span></header><p>{f.purpose||'No purpose note entered.'}</p><div className="accounting-record-meta"><span>{f.restriction}</span><span>{f.active?'Active':'Inactive'}</span><span>{f.allowedAccountIds.length?f.allowedAccountIds.length+' eligible accounts':'All eligible accounts'}</span></div><button type="button" onClick={()=>{setFund(f);setEditing(true);}}>Edit {f.kind}</button></article>)}</div>:<AccountingEmpty title="Organize the purpose of each amount" detail="Funds, programs and grants are explicit dimensions chosen by your accounting team." onCreate={newFund} createLabel="Add fund, program or grant"/>)}
      {tab==='periods'&&(workspace.periods.length?<AccountingTable label="Accounting periods"><thead><tr><th>Period</th><th>Dates</th><th>Status</th><th>Manage</th></tr></thead><tbody>{workspace.periods.map(p=><tr key={p.id}><td><strong>{p.name}</strong>{p.reason&&<small>{p.reason}</small>}</td><td>{accountingDate(p.startsOn)} – {accountingDate(p.endsOn)}</td><td><span className={'accounting-status '+p.status}>{p.status}</span></td><td><div className="accounting-actions">{p.status==='open'&&<button type="button" onClick={()=>{setPeriod({id:p.id,name:p.name,startsOn:p.startsOn,endsOn:p.endsOn});setPeriodRevision(p.revision);setEditing(true);}}>Edit period</button>}<button type="button" onClick={()=>{setPeriodAction({id:p.id,revision:p.revision,status:p.status==='open'?'closed':'open',name:p.name});setReason('');}}>{p.status==='open'?'Close period':'Reopen period'}</button></div></td></tr>)}</tbody></AccountingTable>:<AccountingEmpty title="Define an open accounting period" detail="Posting dates must fall within an explicitly open period. Periods cannot overlap." onCreate={start} createLabel="Add accounting period"/>)}
    </>}
  </AccountingSection>;
}

const blankLine=():JournalLineInput=>({accountId:'',debit:'0',credit:'0',memo:''});
export function AccountingJournals({workspace,notify,onDirty,refresh,guardNavigation}:AccountingContext) {
  const [draft,setDraft]=useState<{id:string;revision:number;date:string;description:string;reference:string;lines:JournalLineInput[]}|null>(null),[selected,setSelected]=useState<AccountingJournal|null>(null),[reverse,setReverse]=useState(false),[reason,setReason]=useState(''),[date,setDate]=useState(localToday()),[reviewed,setReviewed]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState('all');
  const [discard,setDiscard]=useState(false),action=useAccountingAction(notify),precision=workspace.config.precision??2;
  const current=selected?workspace.journals.find(j=>j.id===selected.id)??selected:null;
  let debit=0n,credit=0n,valid=true;
  for(const line of draft?.lines??[]){try{debit+=accountingUnits(line.debit,precision);credit+=accountingUnits(line.credit,precision);}catch{valid=false;}}
  function start(){setDraft({id:crypto.randomUUID(),revision:0,date:localToday(),description:'',reference:'',lines:[blankLine(),blankLine()]});setSelected(null);setReviewed(false);}
  function update(patch:Partial<NonNullable<typeof draft>>){setDraft(value=>value?{...value,...patch}:null);onDirty(true);setReviewed(false);}
  function updateLine(index:number,patch:Partial<JournalLineInput>){if(draft)update({lines:draft.lines.map((line,i)=>i===index?{...line,...patch}:line)});}
  async function save(event:React.FormEvent){event.preventDefault();if(!draft)return;const {revision,...body}=draft;const result=await action.run(()=>api<AccountingJournal>('/accounting/journals',{...body,expectedRevision:revision}),'Journal draft saved.');if(result){onDirty(false);setDraft(null);setSelected(result);refresh();}}
  async function post(){if(!current||!reviewed)return;const result=await action.run(()=>api('/accounting/journals/'+current.id+'/post',{expectedRevision:current.revision,commandId:crypto.randomUUID()}),'Journal posted to the books.');if(result){setSelected(null);setReviewed(false);onDirty(false);refresh();}}
  async function reverseJournal(event:React.FormEvent){event.preventDefault();if(!current)return;const result=await action.run(()=>api('/accounting/journals/'+current.id+'/reverse',{expectedRevision:current.revision,date,reason,commandId:crypto.randomUUID()}),'Reversal posted. The original entry is preserved.');if(result){setReverse(false);setSelected(null);onDirty(false);refresh();}}
  async function discardJournal(event:React.FormEvent){event.preventDefault();if(!current)return;const result=await action.run(()=>api('/accounting/journals/'+current.id,{expectedRevision:current.revision,reason,commandId:crypto.randomUUID()},'DELETE'),'Unused draft discarded with an audit record.');if(result){setDiscard(false);setSelected(null);onDirty(false);refresh();}}
  const filtered=workspace.journals.filter(j=>(status==='all'||j.status===status)&&[j.description,j.reference].join(' ').toLowerCase().includes(search.toLowerCase()));
  return <AccountingSection title="Journals & opening balances" detail="Prepare a balanced entry, review its lines, then post it. Corrections use an explicit reversal so the original stays traceable." actions={!draft&&!current?<button type="button" onClick={start}><Plus size={17}/>New journal</button>:undefined}>
    {action.error&&<AccountingNotice tone="error">{action.error}</AccountingNotice>}
    {draft?<form inert={action.busy} className="accounting-stack" onSubmit={save}><div className="accounting-form-grid"><label>Entry date<input required type="date" value={draft.date} onChange={e=>update({date:e.target.value})}/></label><label>Reference<input maxLength={120} value={draft.reference} onChange={e=>update({reference:e.target.value})} placeholder="Optional reference"/></label><label className="accounting-wide">Description<input required maxLength={500} value={draft.description} onChange={e=>update({description:e.target.value})}/></label></div>
      {draft.lines.map((line,index)=><article key={index} className="accounting-line-card"><header><strong>Line {index+1}</strong><button type="button" disabled={draft.lines.length<=2} aria-label={'Remove journal line '+(index+1)} onClick={()=>update({lines:draft.lines.filter((_,i)=>i!==index)})}><Trash2 size={16}/></button></header><div className="accounting-line-grid"><AccountingAccountSelect accounts={workspace.accounts} value={line.accountId} onChange={accountId=>updateLine(index,{accountId})}/><label>Debit<input inputMode="decimal" required value={line.debit} onChange={e=>updateLine(index,{debit:e.target.value})}/></label><label>Credit<input inputMode="decimal" required value={line.credit} onChange={e=>updateLine(index,{credit:e.target.value})}/></label></div><AccountingDimensions workspace={workspace} line={line} extended onChange={patch=>updateLine(index,patch)}/><div className="accounting-form-grid"><label>Line note<input maxLength={500} value={line.memo??''} onChange={e=>updateLine(index,{memo:e.target.value})}/></label><label>Cash-flow classification<select value={line.cashFlowCategory??''} onChange={e=>updateLine(index,{cashFlowCategory:(e.target.value||undefined) as JournalLineInput['cashFlowCategory']})}><option value="">Use account classification</option>{cashFlowCategories.map(value=><option key={value} value={value}>{value}</option>)}</select></label></div></article>)}
      <div className="accounting-actions"><button type="button" disabled={draft.lines.length>=200} onClick={()=>update({lines:[...draft.lines,blankLine()]})}><Plus size={16}/>Add line</button></div>
      <div className="accounting-balance" role="status"><span>Debits<strong>{valid?accountingMoney(accountingDecimal(debit,precision),workspace.config.currency??'',precision):'Check amounts'}</strong></span><span>Credits<strong>{valid?accountingMoney(accountingDecimal(credit,precision),workspace.config.currency??'',precision):'Check amounts'}</strong></span><span>Difference<strong>{valid?accountingMoney(accountingDecimal(debit-credit,precision),workspace.config.currency??'',precision):'—'}</strong></span>{valid&&debit===credit&&debit>0n&&<span><CheckCircle2 size={22}/>Balanced</span>}</div>
      <p className="accounting-note">Enter each amount on one side only. Saving a draft does not change account balances; posting requires a separate review.</p><div className="accounting-actions"><button type="submit" className="primary" disabled={action.busy||!valid||debit!==credit||debit<=0n}><Save size={16}/>Save balanced draft</button><button type="button" onClick={()=>{if(window.confirm('Discard this unsaved journal?')){setDraft(null);onDirty(false);}}}>Cancel</button></div>
    </form>:current?<div className="accounting-stack"><div className="accounting-actions"><button type="button" onClick={()=>{if(guardNavigation&&!guardNavigation())return;setSelected(null);setReverse(false);setDiscard(false);onDirty(false);}}>Back to journals</button><span className={'accounting-status '+current.status}>{current.reversedBy?'Reversed':current.status}</span></div><h4>{current.description}</h4><p className="accounting-note">{accountingDate(current.date)}{current.reference?' · '+current.reference:''} · {current.sourceType==='manual'?'Manual entry':current.sourceType.replaceAll('_',' ')}</p><AccountingTable label="Journal review"><thead><tr><th>Account</th><th>Debit</th><th>Credit</th><th>Details</th></tr></thead><tbody>{current.lines.map((line,index)=><tr key={line.id??index}><td>{line.accountName}<small>{line.accountCode}</small></td><td><AccountingAmount value={line.debit} workspace={workspace}/></td><td><AccountingAmount value={line.credit} workspace={workspace}/></td><td>{line.memo||'—'}<small>{workspace.units.find(u=>u.id===line.unitId)?.name??'Organization-wide'}</small>{[line.fundId,line.programId,line.grantId].filter(Boolean).map(id=><small key={id}>{workspace.funds.find(f=>f.id===id)?.name??'Historical dimension'}</small>)}</td></tr>)}</tbody></AccountingTable>
      {current.status==='draft'&&!discard?<><label className="accounting-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed the date, accounts, dimensions and amounts for posting.</label><div className="accounting-actions"><button type="button" className="primary" disabled={!reviewed||action.busy} onClick={post}><Check size={16}/>Post journal</button><button type="button" onClick={()=>{setDraft({id:current.id,revision:current.revision,date:current.date,description:current.description,reference:current.reference,lines:current.lines.map(({id,accountCode,accountName,...line})=>line)});setSelected(null);}}>Edit draft</button></div></>:!current.reversedBy&&!current.reversalOf&&current.sourceType==='manual'&&!reverse?<button type="button" onClick={()=>{setReverse(true);setDate(localToday());setReason('');}}>Prepare reversal</button>:null}
      {current.status==='draft'&&current.sourceType==='manual'&&!discard&&<button type="button" onClick={()=>{setDiscard(true);setReason('');}}>Discard unused draft</button>}
      {discard&&<form inert={action.busy} className="accounting-stack" onSubmit={discardJournal}><AccountingNotice tone="warning">This removes an unused manual draft and keeps an audit snapshot. Posted entries must be corrected with a reversal.</AccountingNotice><label>Reason<textarea required minLength={3} maxLength={1000} value={reason} onChange={e=>{setReason(e.target.value);onDirty(true);}}/></label><div className="accounting-actions"><button type="submit" className="danger" disabled={action.busy}>Confirm discard draft</button><button type="button" onClick={()=>{setDiscard(false);setReason('');onDirty(false);}}>Keep draft</button></div></form>}
      {reverse&&<form inert={action.busy} className="accounting-stack" onSubmit={reverseJournal}><AccountingNotice tone="warning">A reversal posts the opposite of every line in a valid open period. It does not erase this entry.</AccountingNotice><label>Reversal date<input required type="date" value={date} onChange={e=>{setDate(e.target.value);onDirty(true);}}/></label><label>Reason<textarea required minLength={3} maxLength={1000} value={reason} onChange={e=>{setReason(e.target.value);onDirty(true);}}/></label><button type="submit" className="danger" disabled={action.busy}>Post reversal</button></form>}
    </div>:<><div className="accounting-filters"><label>Find an entry<input value={search} placeholder="Description or reference" onChange={e=>setSearch(e.target.value)}/></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All entries</option><option value="draft">Drafts</option><option value="posted">Posted</option></select></label></div>{workspace.journalsTruncated&&<AccountingNotice>The journal list is limited to recent entries. Use dated statements to review older activity.</AccountingNotice>}{filtered.length?<div className="accounting-list-grid">{filtered.map(j=><article className="accounting-record-card" key={j.id}><header><h4>{j.description}</h4><span className={'accounting-status '+j.status}>{j.reversedBy?'Reversed':j.status}</span></header><p>{accountingDate(j.date)}{j.reference?' · '+j.reference:''}</p><div className="accounting-record-meta"><span>{j.lines.length} lines</span><span>{j.sourceType.replaceAll('_',' ')}</span></div><button type="button" onClick={()=>{setSelected(j);setReviewed(false);}}>Review entry</button></article>)}</div>:<AccountingEmpty title={workspace.journals.length?'No matching journals':'Your books start with a reviewed entry'} detail="Use a balanced opening journal for approved starting balances, then post day-to-day activity." onCreate={start} createLabel="Create journal draft"/>}</>}
  </AccountingSection>;
}
