import { ArrowDown, ArrowUp, BarChart3, Check, Filter, Layers3, RotateCcw, Search, SlidersHorizontal } from 'lucide-react';
import type { CSSProperties } from 'react';
import type { FinanceLine } from '../shared/finance';
import { financeColumnLabels, financeDefaultView, financeGroups, financeDecimal, financeMagnitudePercent, financeRowKindLabels, financeViewColumns, financeVisibleLines, formatFinanceAmount, type FinanceViewColumn, type FinanceViewOptions } from '../shared/finance-presentation';

const colors = ['#7666d8', '#15928d', '#d68a2e', '#b65a83', '#428ac5', '#85923f'];
export function FinanceViewTable({ rows, currency, columns, decimalPlaces=2 }: { rows: FinanceLine[]; currency: string; columns: FinanceViewColumn[]; decimalPlaces?:2|4 }) {
  return <table className="finance-table finance-readable-table"><caption>Imported source lines · {currency} · display: {decimalPlaces} decimal places</caption><thead><tr>{columns.map(column=><th key={column} scope="col">{financeColumnLabels[column]}{column==='amount'?' · '+currency:''}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.lineCode}>{columns.map(column=><td key={column} className={column==='amount'?'finance-amount':''} title={column==='amount'?'Exact source amount: '+row.amount:undefined}>{column==='amount'?formatFinanceAmount(row.amount,'',decimalPlaces):column==='rowKind'?financeRowKindLabels[row.rowKind]:row[column]||'—'}</td>)}</tr>)}</tbody></table>;
}
export default function FinanceReportStudio({ lines, currency, view, onChange }: { lines: FinanceLine[]; currency: string; view: FinanceViewOptions; onChange:(value:FinanceViewOptions)=>void }) {
  const groups=financeGroups(lines), totalMagnitude=groups.reduce((sum,row)=>sum+row.magnitude,0n), visible=financeVisibleLines(lines,view);
  const selected=financeGroups(visible), net=selected.reduce((sum,row)=>sum+row.net,0n), detailCount=selected.reduce((sum,row)=>sum+row.count,0);
  const names=[...new Set(lines.map(row=>row.group))].sort((a,b)=>a.localeCompare(b));
  let angle=0;
  const wedges=groups.map((row,index)=>{const start=angle;angle+=financeMagnitudePercent(row.magnitude,totalMagnitude);return `${colors[index%colors.length]} ${start}% ${angle}%`;});
  function toggle(column:FinanceViewColumn){onChange({...view,columns:view.columns.includes(column)?view.columns.filter(value=>value!==column):[...view.columns,column]});}
  function move(index:number,step:number){const columns=[...view.columns];[columns[index],columns[index+step]]=[columns[index+step],columns[index]];onChange({...view,columns});}
  return <section className="finance-studio" aria-label="Customize financial report">
    <div className="finance-studio-title"><span aria-hidden="true"><SlidersHorizontal size={23}/></span><div><h3>Make this report yours</h3><p>Choose what to review, then print or download this view.</p></div></div>
    <div className="finance-view-presets" role="group" aria-label="Financial report view templates">
      <button type="button" onClick={()=>onChange(financeDefaultView())}><Layers3 size={16}/>Readable overview</button>
      <button type="button" onClick={()=>onChange({...financeDefaultView(),rowKind:'detail',sort:'amount_desc',columns:['lineLabel','group','amount']})}><BarChart3 size={16}/>Detail review</button>
      <button type="button" onClick={()=>onChange({...financeDefaultView(),columns:['lineLabel','amount','group','rowKind','note','lineCode']})}>Source evidence</button>
    </div>
    <div className="finance-studio-filters"><label>Find a line<span><Search size={16}/><input aria-label="Search financial report lines" value={view.search} maxLength={160} placeholder="Name, group, code or note" onChange={event=>onChange({...view,search:event.target.value})}/></span></label>
      <label>Group<select value={view.group===undefined?'all':String(names.indexOf(view.group))} onChange={event=>onChange({...view,group:event.target.value==='all'?undefined:names[Number(event.target.value)]})}><option value="all">All groups</option>{names.map((name,index)=><option key={name} value={index}>{name||'Ungrouped'}</option>)}</select></label>
      <label>Line types<select value={view.rowKind} onChange={event=>onChange({...view,rowKind:event.target.value as FinanceViewOptions['rowKind']})}><option value="all">All source lines</option><option value="detail">Detail only</option><option value="subtotal">Subtotals only</option><option value="total">Totals only</option></select></label>
      <label>Order<select value={view.sort} onChange={event=>onChange({...view,sort:event.target.value as FinanceViewOptions['sort']})}><option value="source">Original source order</option><option value="label">Line name</option><option value="amount_desc">Amount: highest first</option><option value="amount_asc">Amount: lowest first</option></select></label>
      <label>Decimal places<select value={view.decimalPlaces} onChange={event=>onChange({...view,decimalPlaces:Number(event.target.value) as 2|4})}><option value={2}>2 · everyday reading</option><option value={4}>4 · source precision</option></select></label>
    </div>
    <details className="finance-column-settings"><summary>Choose and arrange columns · {view.columns.length} shown</summary><div className="finance-column-choices">{financeViewColumns.map(column=><label key={column}><input type="checkbox" checked={view.columns.includes(column)} disabled={column==='lineLabel'||column==='amount'} onChange={()=>toggle(column)}/>{financeColumnLabels[column]}{(column==='lineLabel'||column==='amount')&&<small>Required</small>}</label>)}</div><ol>{view.columns.map((column,index)=><li key={column}><span>{financeColumnLabels[column]}</span><button type="button" aria-label={'Move '+financeColumnLabels[column]+' earlier'} disabled={index===0} onClick={()=>move(index,-1)}><ArrowUp size={15}/></button><button type="button" aria-label={'Move '+financeColumnLabels[column]+' later'} disabled={index===view.columns.length-1} onClick={()=>move(index,1)}><ArrowDown size={15}/></button></li>)}</ol></details>
    <div className="finance-view-summary" role="status"><span><Filter size={16}/>{visible.length} of {lines.length} source lines</span><span>{detailCount} detail lines · {formatFinanceAmount(financeDecimal(net),currency,view.decimalPlaces)} net detail sum</span><button type="button" onClick={()=>onChange(financeDefaultView())}><RotateCcw size={15}/>Reset view</button></div>
    <div className="finance-group-explorer"><div className="finance-group-donut" style={{background:totalMagnitude>0n?`conic-gradient(${wedges.join(',')})`:'var(--border)'}} aria-hidden="true"><div><Layers3 size={24}/><strong>{groups.length}</strong><small>detail groups</small></div></div><div className="finance-group-content"><h4>Explore the source groups</h4><p>Chart shares use absolute detail amounts from the full source. Negative and positive amounts both contribute; subtotals and totals are excluded. This is not a breakdown of profit or cash.</p><div className="finance-group-bars">{groups.slice(0,12).map((row,index)=><button type="button" key={row.group} aria-pressed={view.group===row.group} style={{'--finance-group-color':colors[index%colors.length]} as CSSProperties} onClick={()=>onChange({...view,group:view.group===row.group?undefined:row.group,rowKind:'detail'})}><span>{row.group||'Ungrouped'}{view.group===row.group&&<Check size={15}/>}</span><strong>{formatFinanceAmount(financeDecimal(row.net),currency,view.decimalPlaces)}</strong><i aria-hidden="true"><b style={{width:financeMagnitudePercent(row.magnitude,totalMagnitude)+'%'}}/></i><small>{row.count} detail lines · {financeMagnitudePercent(row.magnitude,totalMagnitude).toFixed(2)}% of absolute amounts</small></button>)}</div>{groups.length>12&&<p>Showing the 12 largest groups. Choose any group in the filter above.</p>}{!groups.length&&<p>No detail lines in this source. Its subtotal and total rows remain available in the table.</p>}</div></div>
    <p className="finance-view-footnote">This view's CSV and printout use the selected {view.decimalPlaces} decimal places. Display rounding follows exact aggregation; full-source downloads retain the original precision. No currency conversion or accounting classification is applied.</p>
  </section>;
}
