import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { DateTime } from 'luxon';
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, History, Pencil, Plus, RefreshCw, Search, Target, Upload, Users } from 'lucide-react';
import { api } from './api';
import { Badge, Empty } from './components';
import StaffSchedule from './StaffSchedule';
import { planningQuery, type CoverageRule, type HoursTarget, type PlanningWorkspace } from '../shared/staff-planning';
import { PlanningHistoryDialog, PlanningRuleEditor, PlanningTargetEditor } from './SchedulePlanningEditors';
import { PlanningAssignmentPreview } from './SchedulePlanningPreview';
import { filledPercent, planningDate, planningError, planningRange, planningTime, staffHours, usePlanningAccess, type PlanningAccess, type PlanningRangeMode } from './SchedulePlanningShared';
import './schedule-planning.css';

export type SchedulePlanningTarget = {jobId?:string;userId?:string;unitId?:string;mode?:'coverage'|'rules'|'targets'|'assigned'};
type Props = PlanningAccess & {
  me:any; staff:any[]; jobs:any[]; rows:any[]; week:string; zone:string;
  onWeek:(value:string)=>void;onChanged:()=>Promise<void>;notify:(message:string,error?:boolean)=>void;
  onDirty:(value:boolean)=>void;onRequests:(scheduleId:string,requestId?:string)=>void;
  onImport?:()=>void;onManageEmployeeJobs?:(person:any)=>void;
  initialTarget?:SchedulePlanningTarget|null;onConsumeTarget?:()=>void;
};
type Tab = NonNullable<SchedulePlanningTarget['mode']>;
type Editor = {kind:'rule';row?:CoverageRule}|{kind:'target';row?:HoursTarget}|{kind:'preview'}|{kind:'history';type:'rules'|'targets';id:string;title:string};
export default function SchedulePlanning(props:Props) {
  const manage = ['developer','owner','admin','manager'].includes(props.me.actor.role) && props.me.actor.mode === 'password';
  return manage ? <ManagementPlanning {...props}/> : <StaffSchedule {...props}/>;
}
function ManagementPlanning(props:Props) {
  const [tab,setTab] = useState<Tab>(props.initialTarget?.mode ?? 'coverage');
  const [mode,setMode] = useState<PlanningRangeMode>('week'), [anchor,setAnchor] = useState(props.week);
  const [range,setRange] = useState(()=>planningRange(props.week,'week')!);
  const [jobId,setJobId] = useState(props.initialTarget?.jobId ?? ''), [unitId,setUnitId] = useState(props.initialTarget?.unitId ?? ''), [userId,setUserId] = useState(props.initialTarget?.userId ?? ''), [search,setSearch] = useState('');
  const [workspace,setWorkspace] = useState<PlanningWorkspace|null>(null), [loading,setLoading] = useState(true), [error,setError] = useState(''), [generation,setGeneration] = useState(0);
  const [editor,setEditor] = useState<Editor|null>(null), [editorDirty,setEditorDirty] = useState(false), [assignedDirty,setAssignedDirty] = useState(false), [blocked,setBlocked] = useState(false);
  const [showArchived,setShowArchived] = useState(false), [visibleCount,setVisibleCount] = useState(40), [expandedWindows,setExpandedWindows] = useState(false);
  const access = usePlanningAccess(props), accessRef = useRef(access); accessRef.current=access;
  const request = useRef(0), dialogOwner = useRef(0), firstTarget = useRef(props.initialTarget);
  const dirty = editorDirty || assignedDirty;
  const dirtyRef = useRef(dirty);dirtyRef.current=dirty;
  const blockedRef = useRef(blocked);blockedRef.current=blocked;
  useEffect(()=>{props.onDirty(dirty);return()=>props.onDirty(false);},[dirty,props.onDirty]);
  useEffect(()=>()=>{request.current+=1;dialogOwner.current+=1;},[]);
  const query = useMemo(()=>({start:range.start,end:range.end,...(jobId?{jobId}:{})}),[range.start,range.end,jobId]);
  useEffect(()=>{
    const serial=++request.current,controller=new AbortController();setLoading(true);setError('');setWorkspace(current=>current&&current.query.start===query.start&&current.query.end===query.end&&(current.query.jobId??'')===(query.jobId??'')?current:null);
    const checked=planningQuery.safeParse(query);
    if(!checked.success){setError(checked.error.issues[0]?.message ?? 'Choose a valid date range.');setLoading(false);return;}
    void api<PlanningWorkspace>(`/schedules/planning?${new URLSearchParams(checked.data)}`,undefined,'GET',controller.signal).then(value=>{if(serial===request.current && accessRef.current.current())setWorkspace(value);}).catch(cause=>{if(serial===request.current && accessRef.current.current() && !accessRef.current.reject(cause))setError(planningError(cause));}).finally(()=>{if(serial===request.current && accessRef.current.current())setLoading(false);});
    return()=>{controller.abort();request.current+=1;};
  },[query,generation,props.rows,props.jobs,props.staff]);
  const discard = useCallback(()=>{
    if(blockedRef.current){props.notify("Wait for the current action to finish, or retry its unconfirmed result before leaving.",true);return false;}
    if(dirtyRef.current && !window.confirm('Discard your unsaved schedule changes before leaving this view?'))return false;
    dialogOwner.current+=1;setEditor(null);setEditorDirty(false);setAssignedDirty(false);props.onDirty(false);return true;
  },[props.onDirty,props.notify]);
  useEffect(()=>{
    if(!props.initialTarget)return;
    if(firstTarget.current === props.initialTarget){firstTarget.current=null;props.onConsumeTarget?.();return;}
    if(!discard()){props.onConsumeTarget?.();return;}
    setTab(props.initialTarget.mode ?? 'coverage');setJobId(props.initialTarget.jobId ?? '');setUnitId(props.initialTarget.unitId ?? '');setUserId(props.initialTarget.userId ?? '');setSearch('');setVisibleCount(40);props.onConsumeTarget?.();
  },[props.initialTarget,props.onConsumeTarget,discard]);
  const mutateView=(action:()=>void)=>{if(discard()){action();setVisibleCount(40);setExpandedWindows(false);}};
  const open=(next:Editor)=>{if(discard()){setEditor(next);setEditorDirty(false);}};
  const close=()=>{dialogOwner.current+=1;setEditor(null);setEditorDirty(false);props.onDirty(false);};
  const saved=async()=>{if(!access.current())return;setGeneration(value=>value+1);try{await props.onChanged();}catch(cause){if(access.current())props.notify(`Saved. Refresh the schedule to see the latest data: ${planningError(cause)}`,true);}};
  const reloadForConflict=async()=>{const serial=++request.current;try{const value=await api<PlanningWorkspace>(`/schedules/planning?${new URLSearchParams(query)}`);if(serial===request.current&&access.current())setWorkspace(value);}catch(cause){if(access.current())access.reject(cause);throw cause;}};
  const refresh=()=>{if(!dirtyRef.current){setGeneration(value=>value+1);}};
  const units=Array.from(new Map((workspace?.jobs ?? []).map(job=>[job.unitId,job.unitName])).entries());
  const matchingJobs=(workspace?.jobs ?? []).filter(job=>(!unitId||job.unitId===unitId)&&(!jobId||job.id===jobId));
  const visibleJobs=matchingJobs.filter(job=>!search||`${job.title} ${job.unitName}`.toLowerCase().includes(search.toLowerCase())||((tab==='coverage'||tab==='rules')&&(workspace?.rules??[]).some(rule=>rule.jobId===job.id&&rule.label.toLowerCase().includes(search.toLowerCase()))));
  const visibleIds=new Set(visibleJobs.map(job=>job.id));
  const occurrences=(workspace?.occurrences ?? []).filter(row=>visibleIds.has(row.jobId)&&(!search||`${row.label} ${workspace?.jobs.find(job=>job.id===row.jobId)?.title} ${workspace?.jobs.find(job=>job.id===row.jobId)?.unitName}`.toLowerCase().includes(search.toLowerCase())));
  const rules=(workspace?.rules ?? []).filter(row=>matchingJobs.some(job=>job.id===row.jobId)&&(!search||`${row.label} ${workspace?.jobs.find(job=>job.id===row.jobId)?.title} ${workspace?.jobs.find(job=>job.id===row.jobId)?.unitName}`.toLowerCase().includes(search.toLowerCase()))&&(showArchived||row.active));
  const targets=(workspace?.hoursTargets ?? []).filter(row=>visibleIds.has(row.jobId)&&(showArchived||row.active));
  const totals=occurrences.filter(row=>!row.conflict).reduce((sum,row)=>({required:sum.required+BigInt(row.requiredMicroseconds),filled:sum.filled+BigInt(row.filledMicroseconds),gap:sum.gap+BigInt(row.uncoveredMicroseconds),excess:sum.excess+BigInt(row.excessMicroseconds)}),{required:0n,filled:0n,gap:0n,excess:0n});
  const days=Array.from(occurrences.filter(row=>!row.conflict).reduce((map,row)=>{const date=DateTime.fromISO(row.date),key=mode==='year'?date.toFormat('yyyy-MM'):row.date;const previous=map.get(key)??{key,date:row.date,required:0n,filled:0n,gap:0n,excess:0n,count:0};previous.required+=BigInt(row.requiredMicroseconds);previous.filled+=BigInt(row.filledMicroseconds);previous.gap+=BigInt(row.uncoveredMicroseconds);previous.excess+=BigInt(row.excessMicroseconds);previous.count+=1;map.set(key,previous);return map;},new Map<string,{key:string;date:string;required:bigint;filled:bigint;gap:bigint;excess:bigint;count:number}>()).values());
  const allScheduleRows=(workspace?.schedules??[]).map(row=>({id:row.id,user_id:row.userId,employee_name:row.employeeName,job_id:row.jobId,job_title:row.jobTitle,unit_id:row.unitId,unit_name:row.unitName,starts_at:row.startsAt,ends_at:row.endsAt,note:row.note,version:row.version,status:row.status,updated_at:row.updatedAt,cancelled_at:row.cancelledAt}));
  const currentDialog=dialogOwner.current;
  const editorProps={jobs:workspace?.jobs??[],start:range.start,zone:workspace?.timezone??props.zone,jobId:jobId||undefined,onClose:close,onSaved:saved,onReload:reloadForConflict,onDirty:setEditorDirty,onBlocked:setBlocked,isSessionCurrent:()=>access.current()&&dialogOwner.current===currentDialog,onSessionExpired:props.onSessionExpired};
  function rangeMode(next:PlanningRangeMode,date=anchor){const value=planningRange(date,next);if(value){setMode(next);setAnchor(date);setRange(value);}}
  const move=(direction:number)=>mutateView(()=>{const unit=mode==='custom'?'day':mode;const date=DateTime.fromISO(anchor).plus({[unit]:direction}).toISODate()!;rangeMode(mode,date);});
  if(access.accessDenied)return <p role="alert">Your access changed. Reopen the workspace to refresh your permissions.</p>;
  return <section className="schedule-planning" aria-label="Schedule planning">
    <header className="planning-heading"><div><span className="planning-eyebrow"><CalendarDays size={16}/>Workforce planning</span><h2>Right people. Right time.</h2><p>See coverage, set job needs, then review and assign employee shifts.</p></div><div className="planning-heading-actions">{props.onImport&&<button className="button secondary" onClick={()=>{if(discard())props.onImport?.();}}><Upload size={17}/>Upload schedule</button>}<button className="button primary" disabled={!workspace||loading||!rules.some(row=>row.active)} onClick={()=>open({kind:'preview'})}><Users size={17}/>Review & assign</button></div></header>
    <nav className="planning-tabs" aria-label="Schedule views">{([{id:'coverage',name:'Coverage',icon:Users},{id:'rules',name:'Staffing rules',icon:CalendarDays},{id:'targets',name:'Hours targets',icon:Target},{id:'assigned',name:'Assigned shifts',icon:Clock3}] as const).map(item=><button key={item.id} className={tab===item.id?'active':''} aria-pressed={tab===item.id} onClick={()=>mutateView(()=>setTab(item.id))}><item.icon size={17}/>{item.name}</button>)}</nav>
    <div className="planning-filters"><div className="planning-range-modes" aria-label="Date range size">{(['day','week','month','year','custom'] as const).map(value=><button key={value} className={mode===value?'active':''} aria-pressed={mode===value} onClick={()=>mutateView(()=>rangeMode(value))}>{value[0].toUpperCase()+value.slice(1)}</button>)}</div>
      <div className="planning-filter-grid"><div className="planning-date-controls">{mode!=='custom'&&<button className="icon-button" aria-label={`Previous ${mode}`} onClick={()=>move(-1)}><ChevronLeft size={18}/></button>}<label>{mode==='custom'?'From':'Date'}<input aria-label="Planning date" type="date" value={mode==='custom'?range.start:anchor} onChange={e=>{if(e.target.value)mutateView(()=>mode==='custom'?setRange(value=>({...value,start:e.target.value})):rangeMode(mode,e.target.value));}}/></label>{mode==='custom'?<label>Through<input aria-label="Planning through date" type="date" value={range.end} onChange={e=>{if(e.target.value)mutateView(()=>setRange(value=>({...value,end:e.target.value})));}}/></label>:<button className="icon-button" aria-label={`Next ${mode}`} onClick={()=>move(1)}><ChevronRight size={18}/></button>}</div>
      <label>Community<select aria-label="Planning community" value={unitId} onChange={e=>mutateView(()=>{setUnitId(e.target.value);setJobId('');})}><option value="">All communities</option>{units.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>
      <label>Job<select aria-label="Planning job" value={jobId} onChange={e=>mutateView(()=>setJobId(e.target.value))}><option value="">All jobs</option>{(workspace?.jobs??[]).filter(job=>!unitId||job.unitId===unitId).map(job=><option key={job.id} value={job.id}>{job.title}{!unitId?` · ${job.unitName}`:''}{!job.active?' (archived)':''}</option>)}</select></label>
      <label>{tab==='assigned'?'Employee':'Highlight employee'}<select aria-label="Planning employee" value={userId} onChange={e=>mutateView(()=>setUserId(e.target.value))}><option value="">All employees</option>{(workspace?.employees??[]).map(person=><option key={person.id} value={person.id}>{person.name}</option>)}</select></label>
      <label className="planning-search"><span><Search size={14}/>Search</span><input aria-label="Search schedule planning" value={search} placeholder={tab==='assigned'?'Name, job or note':tab==='targets'?'Job or community':'Job, community or rule'} onChange={e=>{if(!dirtyRef.current)setSearch(e.target.value);}} disabled={dirty}/></label>
      <button className="button secondary" disabled={loading||dirty} onClick={refresh}><RefreshCw size={16}/>{loading?'Loading…':'Refresh'}</button></div>
      <p className="planning-scope">{planningDate(range.start)}–{planningDate(range.end)} · {workspace?.timezone??props.zone}{jobId?` · ${workspace?.jobs.find(job=>job.id===jobId)?.title??'Selected job'}`:''}{unitId?` · ${workspace?.jobs.find(job=>job.unitId===unitId)?.unitName??'Selected community'}`:''}{userId?` · ${tab==='assigned'?'Employee':'Highlighting'}: ${workspace?.employees.find(person=>person.id===userId)?.name??'Selected employee'}${tab!=='assigned'?'; coverage still counts every assigned employee.':''}`:''}</p>
    </div>
    {error&&<div className="planning-callout"><p role="alert" className="form-error">{error}</p><button className="button secondary" onClick={refresh}>Retry schedule</button></div>}
    {loading&&<p className="planning-loading" role="status">Loading the selected schedule and staffing needs…</p>}
    {workspace&&<>
      {workspace.warnings.length>0&&<details className="planning-callout"><summary>{workspace.warnings.length} planning {workspace.warnings.length===1?'notice needs':'notices need'} review</summary>{workspace.warnings.map((warning,index)=><p key={index}>{planningDate(warning.date)} · {warning.message}</p>)}</details>}
      {tab==='coverage'&&<>
        <div className="planning-metrics">{[{label:'Staff-hours needed',value:totals.required,kind:'needed',icon:Target,help:'Required people × coverage duration'},{label:'Staff-hours filled',value:totals.filled,kind:'filled',icon:Users,help:'Assigned coverage, capped at the requirement'},{label:'Unfilled staff-hours',value:totals.gap,kind:'gap',icon:Clock3,help:'Places that still need an employee'},{label:'Extra staff-hours',value:totals.excess,kind:'extra',icon:Plus,help:'Scheduled coverage above the requirement'}].map(metric=><article key={metric.kind} className={`planning-metric ${metric.kind}`}><metric.icon size={23}/><span>{metric.label}</span><strong>{staffHours(metric.value)} <small>h</small></strong><p>{metric.help}</p></article>)}</div>
        <p className="planning-help">Conflicting rules are excluded from totals until resolved. Staff-hours count every required place: two people for three hours means six staff-hours. They are separate from employee clocked hours and job hours targets.</p>
        {!occurrences.length?<div className="planning-zero"><Empty title={rules.some(row=>row.active)?'No coverage windows in this view':'Set the staffing needs for a job'} detail={rules.some(row=>row.active)?'Change the dates or filters, or review notices for skipped dates. No requirement in this view is not a confirmation of full coverage.':'Add a reusable rule with the time window and number of people needed. Then choose employees in Review & assign.'}/><button className="button primary" onClick={()=>open({kind:'rule'})}><Plus size={17}/>Add staffing rule</button></div>:<>
          <div className="planning-section-title"><div><h3>{mode==='year'?'Coverage by month':'Coverage at a glance'}</h3><p>Open a {mode==='year'?'month':'day'} for specific times and people.</p></div><Badge tone={totals.gap>0n?'warning':'success'}>{totals.gap>0n?'Open places remain':'Defined coverage filled'}</Badge></div>
          <div className="planning-day-board">{days.map(day=><button key={day.key} className={`planning-day ${day.gap>0n?'has-gap':'filled'}`} onClick={()=>mutateView(()=>rangeMode(mode==='year'?'month':'day',day.date))}><span>{DateTime.fromISO(day.date).toFormat(mode==='year'?'LLLL yyyy':'ccc, LLL d')}</span><strong>{staffHours(day.filled)} / {staffHours(day.required)} h</strong><div className="planning-bar" aria-hidden="true"><i style={{width:`${Math.min(100,filledPercent(day.filled,day.required))}%`}}/></div><small>{day.gap>0n?`${staffHours(day.gap)} staff-hours unfilled`:'Coverage filled'}{day.excess>0n?` · ${staffHours(day.excess)} h extra`:''}</small></button>)}</div>
          <div className="planning-section-title"><div><h3>Coverage windows ({occurrences.length})</h3><p>Counts are checked throughout each window, including partial shifts.</p></div>{(mode==='month'||mode==='year')&&<button className="button secondary" aria-expanded={expandedWindows} onClick={()=>setExpandedWindows(value=>!value)}>{expandedWindows?'Hide coverage windows':'Show coverage windows'}</button>}</div>
          {(!(mode==='month'||mode==='year')||expandedWindows)&&<>
          <div className="planning-occurrences">{occurrences.slice(0,visibleCount).map(row=>{const job=workspace.jobs.find(job=>job.id===row.jobId),highlight=userId&&row.slices.some(slice=>slice.employeeIds.includes(userId));return <article key={row.id} className={`planning-occurrence ${highlight?'highlight':''}`}><header><div><h4>{job?.title}</h4><p>{job?.unitName} · {row.label}</p></div><Badge tone={row.conflict||BigInt(row.uncoveredMicroseconds)>0n?'warning':'success'}>{row.conflict?'Resolve overlapping rules':BigInt(row.uncoveredMicroseconds)>0n?'Needs people':'Filled'}</Badge></header><p className="planning-window">{planningTime(row.startsAt,workspace.timezone)}–{planningTime(row.endsAt,workspace.timezone)} · <strong>{row.staffCount} {row.staffCount===1?'person':'people'} needed</strong></p><div className="planning-bar" aria-label={`${staffHours(row.filledMicroseconds)} of ${staffHours(row.requiredMicroseconds)} required staff-hours filled`}><i style={{width:`${Math.min(100,filledPercent(row.filledMicroseconds,row.requiredMicroseconds))}%`}}/></div><p>{staffHours(row.uncoveredMicroseconds)} h unfilled · {staffHours(row.excessMicroseconds)} h extra{highlight?' · Highlighted employee assigned':''}</p><details><summary>See people and exact coverage times</summary>{row.slices.map((slice,index)=><div className={`planning-slice ${slice.missing?'has-gap':''}`} key={index}><strong>{planningTime(slice.startsAt,workspace.timezone)}–{planningTime(slice.endsAt,workspace.timezone)}</strong><span>{slice.assigned} of {slice.required} people assigned{slice.missing?` · ${slice.missing} missing`:''}{slice.excess?` · ${slice.excess} extra`:''}</span><p>{slice.employeeIds.map(id=>workspace.employees.find(person=>person.id===id)?.name??'Retained employee').join(', ')||'No employees assigned'}</p></div>)}</details></article>;})}</div>
          {occurrences.length>visibleCount&&<button className="button secondary" onClick={()=>setVisibleCount(value=>value+80)}>Show more coverage windows ({occurrences.length-visibleCount} remaining)</button>}
          </>}
        </>}
      </>}
      {(tab==='rules'||tab==='targets')&&<>
        <div className="planning-section-title"><div><h3>{tab==='rules'?'Reusable staffing rules':'Job hours targets'}</h3><p>{tab==='rules'?'Choose how many people are needed together. Editing a rule leaves already assigned shifts unchanged.':'Compare scheduled staff-hours with a separate job planning target. Targets do not set employee clock allowances.'}</p></div><button className="button primary" onClick={()=>open({kind:tab==='rules'?'rule':'target'})}><Plus size={16}/>Add {tab==='rules'?'staffing rule':'hours target'}</button></div>
        <label className="planning-check"><input type="checkbox" checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/>Include archived {tab==='rules'?'rules':'targets'}</label>
        <div className="planning-rule-list">{tab==='rules'?rules.map(row=>{const job=workspace.jobs.find(job=>job.id===row.jobId);return <article key={row.id}><div><Badge tone={row.active?'success':'neutral'}>{row.active?'Active':'Archived'}</Badge><h4>{row.label}</h4><p>{job?.title} · {job?.unitName}</p><strong>{row.staffCount} {row.staffCount===1?'person':'people'} · {row.startsLocal}–{row.endsLocal}{row.endDayOffset?' next day':''}</strong><p>Every {row.interval} {({daily:'day(s)',weekly:'week(s)',monthly:'month(s)',yearly:'year(s)'})[row.frequency]}{row.frequency==='weekly'?` · ${row.weekdays.map(day=>['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][day-1]).join(', ')}`:''}</p><small>{planningDate(row.startDate)}–{row.endDate?planningDate(row.endDate):'No end date'}</small></div><div className="planning-row-actions"><button className="button secondary" onClick={()=>open({kind:'rule',row})}><Pencil size={15}/>Edit rule</button><button className="button secondary" onClick={()=>open({kind:'history',type:'rules',id:row.id,title:row.label})}><History size={15}/>History</button></div></article>;}):targets.map(row=>{const job=workspace.jobs.find(job=>job.id===row.jobId);return <article key={row.id}><div><Badge tone={row.active?'success':'neutral'}>{row.active?'Active':'Archived'}</Badge><h4>{job?.title}</h4><p>{job?.unitName}</p><strong>{row.hours} hours per {row.period}</strong><p>{planningDate(row.effectiveFrom)}–{row.effectiveThrough?planningDate(row.effectiveThrough):'No end date'}</p></div><div className="planning-row-actions"><button className="button secondary" onClick={()=>open({kind:'target',row})}><Pencil size={15}/>Edit target</button><button className="button secondary" onClick={()=>open({kind:'history',type:'targets',id:row.id,title:`${job?.title??'Job'} target`})}><History size={15}/>History</button></div></article>;})}</div>
        {!(tab==='rules'?rules:targets).length&&<Empty title={tab==='rules'?'No staffing rules in this view':'No hours targets in this view'} detail="Choose another filter or add the job’s first configuration. Nothing is published automatically."/>}
        {tab==='targets'&&workspace.targetPeriods.filter(row=>visibleIds.has(row.jobId)).length>0&&<><div className="planning-section-title"><div><h3>Scheduled hours against targets</h3><p>Full target-period boundaries are shown. Partial periods are flagged; targets are never prorated.</p></div></div><div className="planning-target-periods">{workspace.targetPeriods.filter(row=>visibleIds.has(row.jobId)).slice(0,visibleCount).map(row=><article key={`${row.targetId}-${row.start}`}><header><h4>{workspace.jobs.find(job=>job.id===row.jobId)?.title}</h4>{row.partial&&<Badge tone="warning">Partial period</Badge>}</header><p>{planningDate(row.start)}–{planningDate(row.end)}</p><strong>{staffHours(row.scheduledMicroseconds)} <small>/ {row.targetHours} h scheduled</small></strong><div className="planning-bar" aria-hidden="true"><i style={{width:`${Math.min(100,filledPercent(row.scheduledMicroseconds,row.targetMicroseconds))}%`}}/></div><p>{BigInt(row.deltaMicroseconds)>0n?`${staffHours(row.deltaMicroseconds)} h above target`:BigInt(row.deltaMicroseconds)<0n?`${staffHours(-BigInt(row.deltaMicroseconds))} h below target`:'Target met'}</p></article>)}</div>{workspace.targetPeriods.filter(row=>visibleIds.has(row.jobId)).length>visibleCount&&<button className="button secondary" onClick={()=>setVisibleCount(value=>value+80)}>Show more target periods</button>}</>}
      </>}
      {tab==='assigned'&&<StaffSchedule {...props} rows={allScheduleRows} range={range} filters={{unitId,jobId,userId,search}} onDirty={setAssignedDirty} onBlocked={setBlocked} onChanged={saved} onManageEmployeeJobs={person=>{if(discard())props.onManageEmployeeJobs?.(person);}}/>}
      <p className="planning-footnote">{workspace.notice} Last checked {DateTime.fromISO(workspace.asOf).setZone(workspace.timezone).toFormat('LLL d, h:mm a')}.</p>
    </>}
    {editor?.kind==='rule'&&<PlanningRuleEditor {...editorProps} row={editor.row}/>}
    {editor?.kind==='target'&&<PlanningTargetEditor {...editorProps} row={editor.row}/>}
    {editor?.kind==='history'&&<PlanningHistoryDialog {...editorProps} kind={editor.type} id={editor.id} title={editor.title}/>}
    {editor?.kind==='preview'&&<PlanningAssignmentPreview {...editorProps} query={query} rules={rules.filter(row=>row.active)} onSaved={async count=>{props.notify(`${count} employee shifts assigned.`);await saved();}}/>}
  </section>;
}
