import {useEffect,useMemo,useRef,useState} from 'react';
import {ArrowRight,Search,Sparkles,WifiOff,Clock3,Users,Wallet,CalendarDays,Mail,GraduationCap,HeartHandshake,ShieldCheck,FileBarChart2,Settings2,History,BookOpen,FileClock,LayoutDashboard,Coffee} from 'lucide-react';
import {DateTime} from 'luxon';
import {Modal} from './components';
import {availableDestinations,findDestinations,type WorkspaceDestination} from '../shared/workspace-shortcuts';
const icons={overview:LayoutDashboard,clock:Clock3,'time-records':History,payroll:Wallet,staff:Users,schedule:CalendarDays,calendar:CalendarDays,messages:Mail,school:GraduationCap,care:HeartHandshake,dismissal:ShieldCheck,requests:FileClock,reports:FileBarChart2,audit:ShieldCheck,workspace:BookOpen,settings:Settings2};
export function WorkspaceTools({me,onNavigate}:{me:any;onNavigate:(id:WorkspaceDestination['id'])=>boolean}) {
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[offline,setOffline]=useState(!navigator.onLine),input=useRef<HTMLInputElement>(null);
 const items=useMemo(()=>availableDestinations(me.actor,Boolean(me.permissions.report)),[me.actor.mode,me.actor.role,me.permissions.report]);
 const found=findDestinations(items,query);
 useEffect(()=>{const changed=()=>setOffline(!navigator.onLine);window.addEventListener('online',changed);window.addEventListener('offline',changed);return()=>{window.removeEventListener('online',changed);window.removeEventListener('offline',changed);};},[]);
 useEffect(()=>{const handler=(event:KeyboardEvent)=>{if(event.isComposing||event.repeat||!(event.metaKey||event.ctrlKey)||event.key.toLowerCase()!=='k'||me.actor.mode!=='password')return;if(document.querySelector('dialog[open],[aria-modal="true"]'))return;event.preventDefault();setQuery('');setOpen(true);};document.addEventListener('keydown',handler);return()=>document.removeEventListener('keydown',handler);},[me.actor.mode]);
 useEffect(()=>{setOpen(false);setQuery('');},[me.actor.id,me.actor.org_id,me.actor.mode,me.actor.role,me.actor.csrf]);
 return <>{offline&&<span className="connection-notice" role="status"><WifiOff size={16}/><span>Device offline · changes need a connection</span></span>}{me.actor.mode==='password'&&<button className="quick-jump-trigger" aria-label="Quick jump" aria-haspopup="dialog" onClick={()=>{setQuery('');setOpen(true);}}><Search size={17}/><span>Quick jump</span><kbd>Ctrl K</kbd></button>}
 {open&&<Modal title="Where would you like to go?" onClose={()=>setOpen(false)}><div className="quick-jump"><div className="quick-jump-intro"><span className="quick-jump-art" aria-hidden="true"><Sparkles size={27}/></span><p>Your workspace, one shortcut away.<small>Search pages and tasks. Account permissions still apply.</small></p></div><label className="quick-jump-search"><Search size={19}/><span className="visually-hidden">Search workspace destinations</span><input ref={input} autoFocus value={query} placeholder="Find a page…" onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='ArrowDown'){e.preventDefault();input.current?.closest('.quick-jump')?.querySelector<HTMLButtonElement>('.quick-jump-item')?.focus();}}}/></label><p className="quick-jump-count" role="status">{found.length} {found.length===1?'destination':'destinations'}</p><div className="quick-jump-results" role="list" aria-label="Workspace destinations" onKeyDown={e=>{if(!['ArrowDown','ArrowUp','Home','End'].includes(e.key))return;const buttons=[...e.currentTarget.querySelectorAll<HTMLButtonElement>('button')],index=buttons.indexOf(document.activeElement as HTMLButtonElement);if(index<0)return;e.preventDefault();if(e.key==='ArrowUp'&&index===0){input.current?.focus();return;}buttons[e.key==='Home'?0:e.key==='End'?buttons.length-1:Math.max(0,Math.min(buttons.length-1,index+(e.key==='ArrowDown'?1:-1)))]?.focus();}}>{found.map(item=>{const Icon=icons[item.id];return <div role="listitem" key={item.id}><button className={'quick-jump-item tint-'+item.tone} onClick={()=>{if(onNavigate(item.id))setOpen(false);}}><span className="quick-jump-icon"><Icon size={21}/></span><span><strong>{item.label}</strong><small>{item.description}</small></span><ArrowRight size={17}/></button></div>;})}{!found.length&&<p className="quick-jump-empty">No matching page. Try “clock,” “calendar” or “settings.”</p>}</div><p className="quick-jump-help">↑ ↓ to explore · Enter to open · Esc to close</p></div></Modal>}</>;
}
export type TeamBoardState={receivedAt:string|null;unavailable:boolean;asOf?:string};
export function LiveTeam({rows,zone,state}:{rows:any[];zone:string;state?:TeamBoardState}) {
 const [filter,setFilter]=useState<'all'|'work'|'break'>('all'),[page,setPage]=useState(0);
 const visible=rows.filter(row=>filter==='all'||row.kind===filter),lastPage=Math.max(0,Math.ceil(visible.length/8)-1),current=Math.min(page,lastPage);
 const unavailable=state?.unavailable,loading=state&&!state.receivedAt&&!unavailable;
 return <section className="live-team" aria-label="Current team activity"><header><div><span className="eyebrow"><span className="team-presence-dot"/> PEOPLE IN MOTION</span><h2>Your team, right now.</h2><p>Latest received board · all permitted communities, separate from the report filters.</p></div><div className="team-filters" role="group" aria-label="Team activity filter">{(['all','work','break'] as const).map(kind=><button aria-pressed={filter===kind} key={kind} onClick={()=>{setFilter(kind);setPage(0);}}>{kind==='all'?'Everyone':kind==='work'?'Working':'On break'}<span>{unavailable||loading?'—':kind==='all'?rows.length:rows.filter(row=>row.kind===kind).length}</span></button>)}</div></header>
 {unavailable?<p className="team-unavailable" role="status">Team activity could not refresh. The next workspace refresh will retry.</p>:loading?<p role="status">Loading team activity…</p>:visible.length?<div className="team-people">{visible.slice(current*8,(current+1)*8).map(row=><article className={'team-person '+(row.kind==='break'?'on-break':'working')} key={row.user_id}><span className="team-person-symbol" aria-hidden="true">{row.kind==='break'?<Coffee size={21}/>:<Clock3 size={21}/>}</span><div><strong>{row.name}</strong><p>{row.job_title}</p><small>{row.unit_name}</small></div><span className="team-person-state">{row.kind==='break'?'On break':'Working'}<small>Since {DateTime.fromISO(row.segment_started_at).setZone(zone).toFormat('h:mm a')}</small></span></article>)}</div>:<div className="team-empty"><Clock3 aria-hidden="true"/><p>{rows.length?'Nobody matches this status.':'No one is clocked in on this board.'}<small>Clock actions appear after the workspace refreshes.</small></p></div>}
 {visible.length>8&&!unavailable&&<div className="team-pages"><button disabled={current===0} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current+1} of {lastPage+1}</span><button disabled={current===lastPage} onClick={()=>setPage(current+1)}>Next</button></div>}
 {state?.receivedAt&&!unavailable&&<p className="team-received">Last received {DateTime.fromISO(state.receivedAt).setZone(zone).toFormat('h:mm:ss a')} · refreshes with the workspace about every 30 seconds.</p>}</section>;
}
