import {after,before,test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {connectDatabase,migrate,type Database,type Queryable,type Row} from '../server/db';
import {initialize} from '../server/seed';
import {digest,opaqueToken,type Actor} from '../server/security';
import {getAttentionPolicy,saveAttentionPolicy,readAttentionPolicy} from '../server/attention-policy';
import {attentionExceeded,attentionPolicyInput,defaultAttentionRules,defaultAttentionPolicy,periodAttention} from '../shared/attention-policy';
import {aggregateAllowance,type AllowanceSchedule} from '../server/workforce-overview';
import {aggregateSegmentsV2} from '../server/reports-v2';
import {canonicalWorkforceUtc,type WorkforceSourceRowV2} from '../shared/workforce-reports-v2';
import {allowancePeriodSchema} from '../shared/workforce-overview';

const status=(code:number)=>(error:any)=>error?.status===code;
let db:Database,org:string;
before(async()=>{db=await connectDatabase();await migrate(db);await initialize(db,{demo:false,ownerEmail:'attention.owner@example.test'});org=(await db.query('SELECT id FROM organizations')).rows[0].id;});
after(async()=>{await db?.close();});
async function account(role='admin',targetOrg=org){const id=randomUUID(),raw=opaqueToken(),hash=digest(raw),email=id+'@example.test',name='Synthetic attention '+role;await db.query('INSERT INTO users(id,org_id,email,name,role) VALUES($1,$2,$3,$4,$5)',[id,targetOrg,email,name,role]);await db.query("INSERT INTO sessions(token_hash,org_id,user_id,mode,csrf,expires_at) VALUES($1,$2,$3,'password',$4,clock_timestamp()+interval '1 hour')",[hash,targetOrg,id,opaqueToken()]);return {hash,actor:{id,org_id:targetOrg,email,name,role,mode:'password',unit_ids:[]} as Actor};}
const rules=(minutes:number)=>({...defaultAttentionRules,overSchedule:{enabled:true,afterMinutes:minutes}});
async function change(who:Awaited<ReturnType<typeof account>>,minutes=5){const current=await getAttentionPolicy(db,who.actor,who.hash);return {expectedVersion:current.policy.version,commandId:randomUUID(),rules:rules(minutes)};}
function probe(action:(tx:Queryable,sql:string,params:any[])=>Promise<void>):Database{return {...db,transaction:<T>(run:(tx:Queryable)=>Promise<T>)=>db.transaction(tx=>run({query:async<R extends Row=Row>(sql:string,params:any[]=[])=>{const result=await tx.query<R>(sql,params);await action(tx,sql,params);return result;}}))};}

test('default shared rules preserve current attention without writing data on read',async()=>{const admin=await account(),result=await getAttentionPolicy(db,admin.actor,admin.hash);assert.deepEqual(result,{policy:defaultAttentionPolicy(),canEdit:true});assert.equal((await db.query('SELECT * FROM workforce_attention_policy')).rows.length,0);});
test('thresholds use exact minutes and strictly greater-than comparison',()=>{assert.equal(attentionExceeded(60_000_000n,{enabled:true,afterMinutes:1}),false);assert.equal(attentionExceeded(60_000_001n,{enabled:true,afterMinutes:1}),true);assert.equal(attentionExceeded(1n,{enabled:true,afterMinutes:0}),true);assert.equal(attentionExceeded(600_000_000n,{enabled:false,afterMinutes:0}),false);for(const afterMinutes of [-1,0.5,1441,Infinity])assert.equal(attentionPolicyInput.safeParse({expectedVersion:0,commandId:randomUUID(),rules:rules(afterMinutes)}).success,false);});
test('only current administrators, owners and developers save shared settings',async()=>{for(const role of ['admin','owner','developer']){const user=await account(role),input=await change(user);const result=await saveAttentionPolicy(db,user.actor,user.hash,input);assert.equal(result.canEdit,true);assert.equal(result.policy.version,input.expectedVersion+1);assert.equal(result.policy.updatedByName,user.actor.name);assert.match(result.policy.updatedAt!,/\.\d{6}Z$/);}for(const role of ['manager','finance','employee']){const user=await account(role);await assert.rejects(saveAttentionPolicy(db,user.actor,user.hash,{expectedVersion:0,commandId:randomUUID(),rules:rules(0)}),status(403));if(role==='employee')await assert.rejects(getAttentionPolicy(db,user.actor,user.hash),status(403));else assert.equal((await getAttentionPolicy(db,user.actor,user.hash)).canEdit,false);}});
test('missing, revoked, PIN, changed-role and pending-onboarding authority cannot save',async()=>{const user=await account(),input=await change(user);await assert.rejects(saveAttentionPolicy(db,user.actor,undefined,input),status(401));await assert.rejects(saveAttentionPolicy(db,{...user.actor,mode:'pin'},user.hash,input),status(403));await assert.rejects(saveAttentionPolicy(db,{...user.actor,mode:'api'},user.hash,input),status(403));await db.query("UPDATE users SET role='employee' WHERE id=$1",[user.actor.id]);await assert.rejects(saveAttentionPolicy(db,user.actor,user.hash,input),status(403));await db.query("UPDATE users SET role='admin',password_hash='synthetic-unusable-password',pin_hash='synthetic-unusable-pin',requires_credential_change=true,require_password_change=true WHERE id=$1",[user.actor.id]);await assert.rejects(saveAttentionPolicy(db,user.actor,user.hash,input),status(403));await db.query('UPDATE users SET requires_credential_change=false,require_password_change=false WHERE id=$1',[user.actor.id]);await db.query('DELETE FROM sessions WHERE token_hash=$1',[user.hash]);await assert.rejects(saveAttentionPolicy(db,user.actor,user.hash,input),status(401));});
test('concurrent same commands write one version, history and audit; changed retries are rejected',async()=>{const user=await account(),input=await change(user,7),responses=await Promise.all([saveAttentionPolicy(db,user.actor,user.hash,input),saveAttentionPolicy(db,user.actor,user.hash,input)]);assert.deepEqual(responses.map(value=>value.replayed).sort(),[false,true]);assert.equal(responses[0].policy.version,responses[1].policy.version);assert.equal((await db.query('SELECT version FROM workforce_attention_history WHERE org_id=$1 AND actor_id=$2 AND command_id=$3',[org,user.actor.id,input.commandId])).rows.length,1);assert.equal((await db.query("SELECT id FROM audit_events WHERE actor_id=$1 AND action='workforce.attention_policy_updated'",[user.actor.id])).rows.length,1);await assert.rejects(saveAttentionPolicy(db,user.actor,user.hash,{...input,rules:rules(8)}),status(409));const newer=await saveAttentionPolicy(db,user.actor,user.hash,await change(user,10));assert.ok(newer.policy.version>responses[0].policy.version);assert.deepEqual((await saveAttentionPolicy(db,user.actor,user.hash,input)).policy,responses[0].policy);});
test('concurrent different administrators cannot overwrite a newer revision',async()=>{const first=await account(),second=await account(),one=await change(first,20),two={...one,commandId:randomUUID(),rules:rules(25)};const results=await Promise.allSettled([saveAttentionPolicy(db,first.actor,first.hash,one),saveAttentionPolicy(db,second.actor,second.hash,two)]);assert.equal(results.filter(value=>value.status==='fulfilled').length,1);const rejected=results.find(value=>value.status==='rejected') as PromiseRejectedResult;assert.equal(rejected.reason.status,409);});
test('history and audit roll back when the exact session expires before commit',async()=>{const user=await account(),input=await change(user,35),before=await readAttentionPolicy(db,org);let expired=false;const wrapped=probe(async(tx,sql,params)=>{if(sql.includes('INSERT INTO audit_events')&&params[3]==='workforce.attention_policy_updated'){expired=true;await tx.query("UPDATE sessions SET expires_at=clock_timestamp()-interval '1 second' WHERE token_hash=$1",[user.hash]);}});await assert.rejects(saveAttentionPolicy(wrapped,user.actor,user.hash,input),status(401));assert.equal(expired,true);assert.deepEqual(await readAttentionPolicy(db,org),before);assert.equal((await db.query('SELECT version FROM workforce_attention_history WHERE actor_id=$1',[user.actor.id])).rows.length,0);assert.equal((await db.query('SELECT id FROM audit_events WHERE actor_id=$1',[user.actor.id])).rows.length,0);});
test('audit write failure rolls back the policy and immutable history',async()=>{const user=await account(),input=await change(user,40),before=await readAttentionPolicy(db,org);const wrapped=probe(async(_tx,sql)=>{if(sql.includes('INSERT INTO audit_events'))throw new Error('Synthetic audit failure');});await assert.rejects(saveAttentionPolicy(wrapped,user.actor,user.hash,input),/Synthetic audit failure/);assert.deepEqual(await readAttentionPolicy(db,org),before);assert.equal((await db.query('SELECT version FROM workforce_attention_history WHERE actor_id=$1',[user.actor.id])).rows.length,0);});
test('retained history is immutable and current policy requires sequential versions',async()=>{const user=await account(),saved=await saveAttentionPolicy(db,user.actor,user.hash,await change(user,45));await assert.rejects(db.query('DELETE FROM workforce_attention_history WHERE org_id=$1 AND version=$2',[org,saved.policy.version]));await assert.rejects(db.query("UPDATE workforce_attention_history SET after_snapshot='{}' WHERE org_id=$1 AND version=$2",[org,saved.policy.version]));await assert.rejects(db.query('DELETE FROM workforce_attention_policy WHERE org_id=$1',[org]));await assert.rejects(db.query('UPDATE workforce_attention_policy SET version=version+2 WHERE org_id=$1',[org]));const history=(await db.query('SELECT before_snapshot,after_snapshot FROM workforce_attention_history WHERE org_id=$1 AND version=$2',[org,saved.policy.version])).rows[0];assert.equal(history.before_snapshot.version,saved.policy.version-1);assert.deepEqual(history.after_snapshot,saved.policy);});
test('organization settings are isolated and a mismatched organization/session is rejected',async()=>{const other=randomUUID();await db.query("INSERT INTO organizations(id,name,timezone) VALUES($1,'Synthetic other organization','UTC')",[other]);const user=await account('admin',other),main=await readAttentionPolicy(db,org);assert.deepEqual((await getAttentionPolicy(db,user.actor,user.hash)).policy,defaultAttentionPolicy());await saveAttentionPolicy(db,user.actor,user.hash,await change(user,15));assert.deepEqual(await readAttentionPolicy(db,org),main);await assert.rejects(getAttentionPolicy(db,{...user.actor,org_id:org},user.hash),status(403));});

const employee=randomUUID(),job=randomUUID(),unit=randomUUID(),hour=3_600_000_000n;
function segment(date:string,from:string,to:string,changes:Partial<WorkforceSourceRowV2>={}):WorkforceSourceRowV2{return {id:randomUUID(),shift_id:randomUUID(),revision:1,user_id:employee,employee_name:'Synthetic flag worker',job_id:job,job_title:'Synthetic job',unit_id:unit,unit_name:'Synthetic unit',kind:'work',started_at:canonicalWorkforceUtc(`${date}T${from}Z`),ended_at:canonicalWorkforceUtc(`${date}T${to}Z`),...changes};}
function schedule(date:string):AllowanceSchedule{return {id:randomUUID(),version:1,userId:employee,employeeName:'Synthetic flag worker',jobId:job,jobTitle:'Synthetic job',unitId:unit,unitName:'Synthetic unit',startsAt:`${date}T09:00:00.000000Z`,endsAt:`${date}T17:00:00.000000Z`};}
function compare(rows:WorkforceSourceRowV2[],schedules:AllowanceSchedule[],minutes=5){const report=aggregateSegmentsV2(rows,{start:'2026-09-21',end:'2026-09-23',group:'day'},'UTC','2026-09-24T00:00:00.000000Z');return aggregateAllowance(report,schedules,{...defaultAttentionPolicy(),version:2,rules:{overSchedule:{enabled:true,afterMinutes:minutes},outsideSchedule:{enabled:true,afterMinutes:minutes}}});}
test('daily thresholds never add small days into a false multi-day flag or erase earlier flags',()=>{const result=compare([segment('2026-09-21','09:00:00','17:04:00'),segment('2026-09-22','09:00:00','17:04:00'),segment('2026-09-23','09:00:00','16:00:00')],['2026-09-21','2026-09-22','2026-09-23'].map(schedule));assert.equal(result.totals.aboveScheduledMicroseconds,String(8n*60_000_000n));assert.deepEqual(periodAttention(result),{overScheduleDays:0,outsideScheduleDays:0});const exceeded=compare([segment('2026-09-21','09:00:00','17:05:00.000001'),segment('2026-09-22','09:00:00','16:00:00')],['2026-09-21','2026-09-22'].map(schedule));assert.deepEqual(periodAttention(exceeded,{userId:employee}),{overScheduleDays:1,outsideScheduleDays:1});assert.equal(periodAttention(exceeded,{date:'2026-09-22'}).overScheduleDays,0);});
test('all job hours share the daily allowance while outside-job schedule time remains a separate rule',()=>{const result=compare([segment('2026-09-21','09:00:00','13:00:00'),segment('2026-09-21','13:00:00','17:00:00',{job_id:randomUUID(),job_title:'Different synthetic job'})],[schedule('2026-09-21')]);assert.equal(result.totals.workMicroseconds,String(8n*hour));assert.deepEqual(periodAttention(result),{overScheduleDays:0,outsideScheduleDays:1});});
test('turning flags off preserves every exact duration and never treats breaks as work',()=>{const rows=[segment('2026-09-21','08:00:00','09:00:00',{kind:'break'}),segment('2026-09-21','09:00:00','18:00:00')],report=aggregateSegmentsV2(rows,{start:'2026-09-21',end:'2026-09-23',group:'day'},'UTC','2026-09-24T00:00:00.000000Z'),scheduled=[schedule('2026-09-21')];const normal=aggregateAllowance(report,scheduled),off=aggregateAllowance(report,scheduled,{...defaultAttentionPolicy(),rules:{overSchedule:{enabled:false,afterMinutes:0},outsideSchedule:{enabled:false,afterMinutes:0}}});assert.deepEqual(off.totals,normal.totals);assert.deepEqual(off.jobs,normal.jobs);assert.deepEqual(off.people,normal.people);assert.equal(off.totals.breakMicroseconds,String(hour));assert.deepEqual(periodAttention(off),{overScheduleDays:0,outsideScheduleDays:0});});
test('captured rules survive response serialization and legacy snapshots keep original highlights',()=>{const current=compare([segment('2026-09-21','09:00:00','17:04:00')],[schedule('2026-09-21')]),captured=allowancePeriodSchema.parse(JSON.parse(JSON.stringify(current)));assert.equal(captured.attention?.policy.rules.overSchedule.afterMinutes,5);assert.equal(periodAttention(captured).overScheduleDays,0);const {attention:_,...legacy}=captured;assert.equal(periodAttention(allowancePeriodSchema.parse(legacy)).overScheduleDays,1);assert.deepEqual(periodAttention(captured,{userId:randomUUID()}),{overScheduleDays:0,outsideScheduleDays:0});});
